;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        fill-paragraph
        forward-sexp
        kill-region
        my/org-insert-key
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-ctrl-c-star
        org-delete-char
        org-end-of-line
        org-kill-line
        org-metaleft
        org-metaright
        org-open-line
        org-self-insert-command
        org-yank
        paredit-backward
        paredit-close-square
        paredit-forward-delete
        paredit-kill
        paredit-open-square
        paredit-semicolon
        sp-remove-active-pair-overlay
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
