;;;; Emacs Bookmark Format Version 1 ;;;; -*- coding: utf-8 -*- 
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("Digital Currency.org"
 (filename . "~/Org/Wiki/Economy/Currency/Digital Currency/Digital Currency.org")
 (front-context-string . "#+TITLE: Digital")
 (rear-context-string)
 (position . 1))
("Economy.org"
 (filename . "~/Org/Wiki/Economy/Economy.org")
 (front-context-string . "#+TITLE: Economy")
 (rear-context-string)
 (position . 1))
("UNIX.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/UNIX/UNIX.org")
 (front-context-string . "#+TITLE: UNIX\n\n*")
 (rear-context-string)
 (position . 1))
("Discourse.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Discourse.org")
 (front-context-string . "#+TITLE: Discour")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Kung Fu/Data/Books/武术入门 - 陈耀佳.pdf"
 (filename . "~/Org/Wiki/Kung Fu/Data/Books/武术入门 - 陈耀佳.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("EMMS.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/EMMS.org")
 (front-context-string . "#+TITLE: EMMS\n\n*")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Softwares/Data/Docs/Selenium 中文文档.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Data/Docs/Selenium 中文文档.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.6591639871382636)
 (handler . pdf-view-bookmark-jump-handler))
("Internet Companies.org"
 (filename . "~/Org/Wiki/Internet/Internet Companies/Internet Companies.org")
 (front-context-string . "#+TITLE: Interne")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Clojure in Small Pieces.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Clojure in Small Pieces.pdf")
 (position . 1)
 (page . 3)
 (slice)
 (size . 4.033986928104575)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("Scratch.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Scratch/Scratch.org")
 (front-context-string . "#+TITLE: Scratch")
 (rear-context-string)
 (position . 1))
("SQL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/SQL.org")
 (front-context-string . "#+TITLE: SQL\n\n* ")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Thought/诸子百家/道家/Data/Books/道德经 Tao Te Ching.pdf"
 (filename . "~/Org/Wiki/Thought/诸子百家/道家/Data/Books/道德经 Tao Te Ching.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.47821466524973427)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Thought/诸子百家/道家/Data/Books/老子 《道德经》 zh.pdf"
 (filename . "~/Org/Wiki/Thought/诸子百家/道家/Data/Books/老子 《道德经》 zh.pdf")
 (position . 1)
 (page . 8)
 (slice 0.126261 0.062886 0.755882 0.897981)
 (size . fit-width)
 (origin 0.0 . 0.4032258064516129)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Thought/诸子百家/道家/Data/Books/老子 《道德经》.pdf"
 (filename . "~/Org/Wiki/Thought/诸子百家/道家/Data/Books/老子 《道德经》.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.7332624867162593)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/XQuery/Data/Books/XQuery, 2nd Edition.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/XQuery/Data/Books/XQuery, 2nd Edition.pdf")
 (position . 1)
 (page . 31)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("Cryptology.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Cryptology/Cryptology.org")
 (front-context-string . "#+TITLE: Cryptol")
 (rear-context-string)
 (position . 1))
("youtube-dl.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/youtube-dl.org")
 (front-context-string . "#+TITLE: youtube")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Implementations/Voice/Voice Interface/Data/Books/Programming Voice Interface.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Voice/Voice Interface/Data/Books/Programming Voice Interface.pdf")
 (position . 1)
 (page . 9)
 (slice 0.115873 0.083761 0.768254 0.8762840000000001)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("My Shell Script Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/Data/Manuals/My Shell Script Syntax Reference/My Shell Script Syntax Reference.org")
 (front-context-string . "#+TITLE: My Shel")
 (rear-context-string)
 (position . 1))
("cURL.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/cURL.org")
 (front-context-string . "#+TITLE: cURL\n\n*")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Implementations/Computer Vision/Data/Books/Deep Learning for Computer Vision with Python.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Computer Vision/Data/Books/Deep Learning for Computer Vision with Python.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Web Development with Clojure: Build Bulletproof Web Apps with Less Code.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Web Development with Clojure: Build Bulletproof Web Apps with Less Code.pdf")
 (position . 1)
 (page . 57)
 (slice)
 (size . 3.3611111111111116)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Softwares/Data/Docs/Nextcloud Manual.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Data/Docs/Nextcloud Manual.pdf")
 (position . 1)
 (page . 25)
 (slice 0.086111 0.020455 0.8277780000000001 0.955303)
 (size . fit-width)
 (origin 0.0 . 0.36474164133738607)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Softwares/data/docs/cgdb.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/data/docs/cgdb.pdf")
 (position . 1)
 (page . 3)
 (slice 0.122059 0.038131000000000005 0.7558819999999999 0.878283)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("tmux.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/tmux.org")
 (front-context-string . "#+TITLE: tmux\n\n*")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Implementations/Voice/Voice Machine Learning/data/ed/553e7a-fc0e-47c3-995a-c3177bfc9fea/Neural Voice Cloning with a Few Samples.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Voice/Voice Machine Learning/data/ed/553e7a-fc0e-47c3-995a-c3177bfc9fea/Neural Voice Cloning with a Few Samples.pdf")
 (position . 1)
 (page . 11)
 (slice 0.06486900000000001 0.034343 0.8457520000000001 0.879546)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Practical Clojure.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Practical Clojure.pdf")
 (position . 1)
 (page . 4)
 (slice 0.08055599999999999 0.07860400000000001 0.8351850000000001 0.817267)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Clojure Applied: From Practice to Practitioner.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Clojure Applied: From Practice to Practitioner.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Code/Emacs/org-mode/doc/orgguide.pdf"
 (filename . "~/Code/Emacs/org-mode/doc/orgguide.pdf")
 (position . 1)
 (page . 4)
 (slice 0.122059 0.038131000000000005 0.7575160000000001 0.793687)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Softwares/Nginx/Data/Books/Nginx HTTP Server, 3rd Edition.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Nginx/Data/Books/Nginx HTTP Server, 3rd Edition.pdf")
 (position . 1)
 (page . 57)
 (slice 0.151471 0.097475 0.6986920000000001 0.782323)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Softwares/Nginx/Data/Books/Nginx 中文官方文档.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Nginx/Data/Books/Nginx 中文官方文档.pdf")
 (position . 1)
 (page . 212)
 (slice 0.079202 0 0.841596 1)
 (size . fit-width)
 (origin 0.0 . 0.3811944091486658)
 (handler . pdf-view-bookmark-jump-handler))
("Dired.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/Dired.org")
 (front-context-string . "#+TITLE: Dired\n\n")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Data/Manuals/My Incanter Reference/data/images/pdf-demo.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Data/Manuals/My Incanter Reference/data/images/pdf-demo.pdf")
 (position . 1)
 (page)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("Debug Emacs and Emacs Lisp.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Manuals/Debug Emacs and Emacs Lisp/Debug Emacs and Emacs Lisp.org")
 (front-context-string . "#+TITLE: Debug E")
 (rear-context-string)
 (position . 1))
("Social Intercourse.org"
 (filename . "~/Org/Wiki/Sociology/Social Intercourse/Social Intercourse.org")
 (front-context-string . "#+TITLE: Social ")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/.emacs.d/Org-mode/ob-clojure/kk.pdf"
 (filename . "~/.emacs.d/Org-mode/ob-clojure/kk.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/data/68/e71eb4-5da4-4920-92b8-2422cb75e7e1/clj-for-datascience.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/data/68/e71eb4-5da4-4920-92b8-2422cb75e7e1/clj-for-datascience.pdf")
 (position . 1)
 (page . 30)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.29871977240398295)
 (handler . pdf-view-bookmark-jump-handler))
("clj-new.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/clj-new.org")
 (front-context-string . "* Intro\n\nGenerat")
 (rear-context-string)
 (position . 1))
("Sex Knowledge.org"
 (filename . "~/Org/Wiki/Sexology/Sexual Intercourse/Sex Knowledge/Sex Knowledge.org")
 (front-context-string . "#+TITLE: Sex Kno")
 (rear-context-string)
 (position . 1))
("Sex Positions.org"
 (filename . "~/Org/Wiki/Sexology/Sexual Intercourse/Sex Knowledge/Sex Positions/Sex Positions.org")
 (front-context-string . "#+TITLE: Sex Pos")
 (rear-context-string)
 (position . 1))
("LGBTQ.org"
 (filename . "~/Org/Wiki/LGBTQ/LGBTQ.org")
 (front-context-string . "#+TITLE: LGBTQ\n\n")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Sexology/Sexual Intercourse/Sex Positions/Data/Books/你不可不做的爱爱101式 - 王聪霖 (全彩版).pdf"
 (filename . "~/Org/Wiki/Sexology/Sexual Intercourse/Sex Positions/Data/Books/你不可不做的爱爱101式 - 王聪霖 (全彩版).pdf")
 (position . 1)
 (page . 40)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("Poems Collection.org"
 (filename . "~/Org/Wiki/Literature/Poem/Data/Poems Collection/Poems Collection.org")
 (front-context-string . "#+TITLE: Poems C")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Clojure Data Structures and Algorithms Cookbook.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Clojure Data Structures and Algorithms Cookbook.pdf")
 (position . 1)
 (page . 16)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/Data/Docs/calc-qref.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/Data/Docs/calc-qref.pdf")
 (position . 1)
 (page . 4)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.18533772652388797)
 (handler . pdf-view-bookmark-jump-handler))
("Calc.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/Calc.org")
 (front-context-string . "#+TITLE: Calc\n\n*")
 (rear-context-string)
 (position . 1))
("Kubernetes.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Kubernetes/Kubernetes.org")
 (front-context-string . "#+TITLE: Kuberne")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Implementations/Cryptology/Data/Cryptology Methods/FontCode/data/docs/fontcode.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Cryptology/Data/Cryptology Methods/FontCode/data/docs/fontcode.pdf")
 (position . 1)
 (page . 4)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("Internet Privacy.org"
 (filename . "~/Org/Wiki/Internet/Internet Privacy/Internet Privacy.org")
 (front-context-string . "#+TITLE: Interne")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Learning JavaScript, 3rd Edition.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Learning JavaScript, 3rd Edition.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Learning JavaScript: A Hand-On Guide to the Fundamentals of Modern JavaScript.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Learning JavaScript: A Hand-On Guide to the Fundamentals of Modern JavaScript.pdf")
 (position . 1)
 (page . 10)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.20664505672609398)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Head First JavaScript Programming.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Head First JavaScript Programming.pdf")
 (position . 1)
 (page . 472)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Head first JavaScript.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Head first JavaScript.pdf")
 (position . 1)
 (page . 79)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Mathematics/Data/Books/数学指南.pdf"
 (filename . "~/Org/Wiki/Mathematics/Data/Books/数学指南.pdf")
 (position . 1)
 (page . 6)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/SQLite/Data/Books/SQLite权威指南.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/SQLite/Data/Books/SQLite权威指南.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/SQLite/Data/Books/SQLite学习手册.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/SQLite/Data/Books/SQLite学习手册.pdf")
 (position . 1)
 (page . 3)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.26057401812688824)
 (handler . pdf-view-bookmark-jump-handler))
("C++.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C++/C++.org")
 (front-context-string . "#+TITLE: C++ Pro")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Open Source/Data/Manuals/My Open Source Tools Usage Manual/data/36/4d6df5-c60b-4553-9b7b-7093b12bbb06/开源世界旅行手册.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Open Source/Data/Manuals/My Open Source Tools Usage Manual/data/36/4d6df5-c60b-4553-9b7b-7093b12bbb06/开源世界旅行手册.pdf")
 (position . 1)
 (page . 2)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/深入浅出JavaScript.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/深入浅出JavaScript.pdf")
 (position . 1)
 (page . 224)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("Deep Learning.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Artificial Intelligence/Deep Learning/Deep Learning.org")
 (front-context-string . "#+TITLE: Deep Le")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Emacs/Data/Books/GNU Emacs Lisp 编程入门.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Books/GNU Emacs Lisp 编程入门.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Learn JavaScript.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Books/Learn JavaScript.pdf")
 (position . 1)
 (page . 41)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.25862068965517243)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/Org mode/data/3c/395b56-1959-4976-af71-067e5047c4ef/org-teaching handbook.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/Org mode/data/3c/395b56-1959-4976-af71-067e5047c4ef/org-teaching handbook.pdf")
 (position . 1)
 (page . 2)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.22641509433962262)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Clojure for the Brave and True.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Books/Clojure for the Brave and True.pdf")
 (position . 1)
 (page . 84)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("My Python Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Data/Manuals/My Python Examples/My Python Examples.org")
 (front-context-string . "#+TITLE: My Pyth")
 (rear-context-string)
 (position . 1))
("My Python Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Data/Manuals/My Python Language Syntax Reference/My Python Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Pyth")
 (rear-context-string)
 (position . 1))
("My Poems Collection.org"
 (filename . "~/Org/Wiki/Literature/Poem/Data/Manuals/My Poems Collection/My Poems Collection.org")
 (front-context-string . "#+TITLE: My Poem")
 (rear-context-string)
 (position . 1))
("Magit.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/Magit/Magit.org")
 (front-context-string . "#+TITLE: Magit\n\n")
 (rear-context-string)
 (position . 1))
("My Data Structures Manual.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Data Structure/Data/Manuals/My Data Structures Manual/My Data Structures Manual.org")
 (front-context-string . "#+TITLE: My Data")
 (rear-context-string)
 (position . 1))
("Octave.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Octave/Octave.org")
 (front-context-string . "#+TITLE: Octave ")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Crack/Data/Crack Methods/Web Crack Methods/XSS/Data/Books/那些年我们一起学XSS.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Crack/Data/Crack Methods/Web Crack Methods/XSS/Data/Books/那些年我们一起学XSS.pdf")
 (position . 1)
 (page . 62)
 (slice 0.077521 0 0.843277 1)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Operating System/Linux/Linux Distributions/Kali Linux/Data/Books/Kali Linux 中文文档.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Distributions/Kali Linux/Data/Books/Kali Linux 中文文档.pdf")
 (position . 1)
 (page . 3)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("CIDER.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/CIDER.org")
 (front-context-string . "#+TITLE: CIDER\n\n")
 (rear-context-string)
 (position . 1))
("Emacs Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/Emacs Packages.org")
 (front-context-string . "#+TITLE: Emacs m")
 (rear-context-string)
 (position . 1))
("TRAMP.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Emacs Packages/TRAMP.org")
 (front-context-string . "#+TITLE: TRAMP\n\n")
 (rear-context-string)
 (position . 1))
("org-capture-last-stored-marker"
 (filename . "~/Org/Contacts/Contacts.org")
 (front-context-string . "** 周熠\n   :PROPER")
 (rear-context-string . "9:38]\n   :END:\n\n")
 (position . 73823))
("org-refile-last-stored"
 (filename . "~/Org/Contacts/Contacts.org")
 (front-context-string . "** 周熠\n   :PROPER")
 (rear-context-string . "9:38]\n   :END:\n\n")
 (position . 73823))
("org-capture-last-stored"
 (filename . "~/Org/Contacts/Contacts.org")
 (front-context-string . "* 周熠\n  :PROPERTI")
 (rear-context-string . ":03]\n    :END:\n\n")
 (position . 136564))
("PDF-LAST-VIEWED: /tmp/mu-1000/b53469b1/3/test.pdf"
 (filename .
           #("/tmp/mu-1000/b53469b1/3/test.pdf" 0 32
             (face ivy-virtual)))
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.12355848434925865)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Algorithm/Data/Books/算法的乐趣.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Algorithm/Data/Books/算法的乐趣.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Implementations/Virtual Machine/data/76/4bc5e5-63ae-4c0e-8fd9-273854a1c9d1/Implementing a virtual machine in C.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Virtual Machine/data/76/4bc5e5-63ae-4c0e-8fd9-273854a1c9d1/Implementing a virtual machine in C.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Data Structure/Data/Books/大话数据结构.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Data Structure/Data/Books/大话数据结构.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("TeX.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/TeX/TeX.org")
 (front-context-string . "#+TITLE: TeX\n\n* ")
 (rear-context-string)
 (position . 1))
("Programming Languages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Programming Languages.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
("Nginx.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Nginx/Nginx.org")
 (front-context-string . "#+TITLE: Nginx\n\n")
 (rear-context-string)
 (position . 1))
("Visual Studio Code.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Visual Studio Code.org")
 (front-context-string . "#+TITLE: Visual ")
 (rear-context-string)
 (position . 1))
("Datomic.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Datomic/Datomic.org")
 (front-context-string . "#+TITLE: Datomic")
 (rear-context-string)
 (position . 1))
("IntelliJ IDEA.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/IntelliJ IDEA.org")
 (front-context-string . "* Intro\n\n\n\n** Fe")
 (rear-context-string)
 (position . 1))
("Linux Configurations.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Linux Configurations.org")
 (front-context-string . "#+TITLE: Linux C")
 (rear-context-string)
 (position . 1))
("clj-http.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/clj-http.org")
 (front-context-string . "* Intro\n\nAn idio")
 (rear-context-string)
 (position . 1))
("Computer Science.org"
 (filename . "~/Org/Wiki/Computer Technology/Computer Science/Computer Science.org")
 (front-context-string . "#+TITLE: Compute")
 (rear-context-string)
 (position . 1))
("Data Mining.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Data Science/Data Mining/Data Mining.org")
 (front-context-string . "#+TITLE: Data Mi")
 (rear-context-string)
 (position . 1))
("Linux Administration.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Administration/Linux Administration.org")
 (front-context-string . "#+TITLE: Linux A")
 (rear-context-string)
 (position . 1))
("How to Find Data.org"
 (filename . "~/Org/Wiki/How to Find Data/How to Find Data.org")
 (front-context-string . "#+TITLE: How to ")
 (rear-context-string)
 (position . 1))
("My Lisp Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Data/Manuals/My Lisp Syntax Reference/My Lisp Syntax Reference.org")
 (front-context-string . "#+TITLE: My Lisp")
 (rear-context-string)
 (position . 1))
("REST.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Web/Web Technologies/HTTP/REST/REST.org")
 (front-context-string . "#+TITLE: REST\n\n*")
 (rear-context-string)
 (position . 1))
("My Git Collaboration Manual.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Git/Data/Manuals/My Git Collaboration Manual/My Git Collaboration Manual.org")
 (front-context-string . "#+TITLE: My Git ")
 (rear-context-string)
 (position . 1))
("Open Community.org"
 (filename . "~/Org/Wiki/Organization/Open Community/Open Community.org")
 (front-context-string . "#+TITLE: Open Co")
 (rear-context-string)
 (position . 1))
("My Arduino Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Dev Board/Single Board Computer/Arduino/Data/Manuals/My Arduino Syntax Reference/My Arduino Syntax Reference.org")
 (front-context-string . "#+TITLE: My Ardu")
 (rear-context-string)
 (position . 1))
("My Arduino Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Dev Board/Single Board Computer/Arduino/Data/Manuals/My Arduino Examples/My Arduino Examples.org")
 (front-context-string . "#+TITLE: My Ardu")
 (rear-context-string)
 (position . 1))
("Terraform.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Terraform/Terraform.org")
 (front-context-string . "#+TITLE: Terrafo")
 (rear-context-string)
 (position . 1))
("My MySQL Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/MySQL/Data/Manuals/My MySQL Syntax Reference/My MySQL Syntax Reference.org")
 (front-context-string . "#+TITLE: My MySQ")
 (rear-context-string)
 (position . 1))
("Quantum Programming.org"
 (filename . "~/Org/Wiki/Physics/Quantum Theory/Quantum Information System/Quantum Computer/Quantum Computation/Quantum Programming/Quantum Programming.org")
 (front-context-string . "#+TITLE: Quantum")
 (rear-context-string)
 (position . 1))
("Quantum Computation.org"
 (filename . "~/Org/Wiki/Physics/Quantum Theory/Quantum Information System/Quantum Computer/Quantum Computation/Quantum Computation.org")
 (front-context-string . "#+TITLE: Quantum")
 (rear-context-string)
 (position . 1))
("ElasticSearch.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/ElasticSearch/ElasticSearch.org")
 (front-context-string . "* Intro\n\nOpen So")
 (rear-context-string)
 (position . 1))
("HTTP.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Network/Network Protocols/HTTP/HTTP.org")
 (front-context-string . "#+TITLE: HTTP\n\n*")
 (rear-context-string)
 (position . 1))
("Web Technologies.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Web/Web Technologies/Web Technologies.org")
 (front-context-string . "#+TITLE: Web Tec")
 (rear-context-string)
 (position . 1))
("My HTML Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/HTML/Data/Manuals/My HTML Examples/My HTML Examples.org")
 (front-context-string . "#+TITLE: My HTML")
 (rear-context-string)
 (position . 1))
("My Common Lisp Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Common Lisp/Data/Manuals/My Common Lisp Examples.org")
 (front-context-string . "#+TITLE: My Comm")
 (rear-context-string)
 (position . 1))
("Masturbation.org"
 (filename . "~/Org/Wiki/Sexology/Masturbation/Masturbation.org")
 (front-context-string . "#+TITLE: Masturb")
 (rear-context-string)
 (position . 1))
(#("My Clothes Manual.org" 0 1
   (idx 11))
 (filename . "~/Org/Wiki/Clothes/Data/Manuals/My Clothes Manual/My Clothes Manual.org")
 (front-context-string . "#+TITLE: My Clot")
 (rear-context-string)
 (position . 1))
(#("My Clothes Reference.org" 0 1
   (idx 12))
 (filename . "~/Org/Wiki/Clothes/Data/Manuals/My Clothes Reference/My Clothes Reference.org")
 (front-context-string . "#+TITLE: My Clot")
 (rear-context-string)
 (position . 1))
(#("ImageMagick.org" 0 1
   (idx 16))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/ImageMagick.org")
 (front-context-string . "#+TITLE: ImageMa")
 (rear-context-string)
 (position . 1))
(#("Web Scraping.org" 0 1
   (idx 17))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Web/Web Technologies/Web Scraping/Web Scraping.org")
 (front-context-string . "#+TITLE: Web Scr")
 (rear-context-string)
 (position . 1))
(#("My Common Lisp Syntax Reference.org" 0 1
   (idx 24))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Common Lisp/Data/Manuals/My Common Lisp Syntax Reference.org")
 (front-context-string . "#+TITLE: My Comm")
 (rear-context-string)
 (position . 1))
(#("My CSS Style Examples.org" 0 1
   (idx 25))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/CSS/Data/Manuals/My CSS Style Examples/My CSS Style Examples.org")
 (front-context-string . "#+TITLE: My CSS ")
 (rear-context-string)
 (position . 1))
(#("Data Analysis.org" 0 1
   (idx 31))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Data Science/Data Analysis/Data Analysis.org")
 (front-context-string . "#+TITLE: Data An")
 (rear-context-string)
 (position . 1))
(#("Growth Hacker.org" 0 1
   (idx 32))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Growth Hacker/Growth Hacker.org")
 (front-context-string . "#+TITLE: Growth ")
 (rear-context-string)
 (position . 1))
(#("GCC.org" 0 1
   (idx 37))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/GCC.org")
 (front-context-string . "#+TITLE: GCC\n\n* ")
 (rear-context-string)
 (position . 1))
(#("My Chinese Government Administration Manual.org" 0 1
   (idx 40))
 (filename . "~/Org/Wiki/Countries/China/Chinese Government/Data/Manuals/My Chinese Government Administration Manual/My Chinese Government Administration Manual.org")
 (front-context-string . "#+TITLE: My Chin")
 (rear-context-string)
 (position . 1))
(#("My Government Policy Usage Manual.org" 0 1
   (idx 41))
 (filename . "~/Org/Wiki/Government/Policy/Data/Manuals/My Government Policy Usage Manual/My Government Policy Usage Manual.org")
 (front-context-string . "#+TITLE: My Gove")
 (rear-context-string)
 (position . 1))
(#("Logistics.org" 0 1
   (idx 46))
 (filename . "~/Org/Wiki/Logistics/Logistics.org")
 (front-context-string . "#+TITLE: Logisti")
 (rear-context-string)
 (position . 1))
(#("My Liked Love.org" 0 1
   (idx 48))
 (filename . "~/Org/Wiki/Love/Data/Manuals/My Liked Love/My Liked Love.org")
 (front-context-string . "#+TITLE: My Like")
 (rear-context-string)
 (position . 1))
(#("Programming Language Design.org" 0 1
   (idx 53))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Programming Language Design/Programming Language Design.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
(#("Firefox Addons.org" 0 1
   (idx 54))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Firefox/Firefox Addons/Firefox Addons.org")
 (front-context-string . "#+TITLE: Firefox")
 (rear-context-string)
 (position . 1))
(#("Spice.org" 0 1
   (idx 56))
 (filename . "~/Org/Wiki/Botany/Spice/Spice.org")
 (front-context-string . "#+TITLE: Spice\n\n")
 (rear-context-string)
 (position . 1))
(#("R Packages.org" 0 1
   (idx 65))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/R/Data/R Packages/R Packages.org")
 (front-context-string . "#+TITLE: R Packa")
 (rear-context-string)
 (position . 1))
(#("Ubuntu.org" 0 1
   (idx 68))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Distributions/Ubuntu/Ubuntu.org")
 (front-context-string . "#+TITLE: Ubuntu ")
 (rear-context-string)
 (position . 1))
(#("Debian.org" 0 1
   (idx 69))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Distributions/Debian/Debian.org")
 (front-context-string . "#+TITLE: Debian ")
 (rear-context-string)
 (position . 1))
(#("Quantum Computer.org" 0 1
   (idx 72))
 (filename . "~/Org/Wiki/Physics/Quantum Theory/Quantum Information System/Quantum Computer/Quantum Computer.org")
 (front-context-string . "#+TITLE: Quantum")
 (rear-context-string)
 (position . 1))
(#("My Computer Technology Glossary.org" 0 1
   (idx 76))
 (filename . "~/Org/Wiki/Computer Technology/Data/Manuals/My Computer Technology Glossary/My Computer Technology Glossary.org")
 (front-context-string . "#+TITLE: My Comp")
 (rear-context-string)
 (position . 1))
(#("My Programming Glossary.org" 0 1
   (idx 77))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Data/Manuals/My Programming Glossary/My Programming Glossary.org")
 (front-context-string . "#+TITLE: My Prog")
 (rear-context-string)
 (position . 1))
(#("shadowsocks.org" 0 1
   (idx 86))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/shadowsocks.org")
 (front-context-string . "#+TITLE: shadows")
 (rear-context-string)
 (position . 1))
(#("SSH.org" 0 1
   (idx 91))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/SSH.org")
 (front-context-string . "#+TITLE: SSH\n\n* ")
 (rear-context-string)
 (position . 1))
(#("My Kung Fu Manual.org" 0 1
   (idx 97))
 (filename . "~/Org/Wiki/Kung Fu/Data/Manuals/My Kung Fu Manual/My Kung Fu Manual.org")
 (front-context-string . "#+TITLE: My Kung")
 (rear-context-string)
 (position . 1))
(#("Products Manual.org" 0 1
   (idx 100))
 (filename . "~/Org/Products Manual/Products Manual.org")
 (front-context-string . "#+TITLE: Product")
 (rear-context-string)
 (position . 1))
(#("Arduino.org" 0 1
   (idx 102))
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Dev Board/Single Board Computer/Arduino/Arduino.org")
 (front-context-string . "#+TITLE: Arduino")
 (rear-context-string)
 (position . 1))
(#("Raspberry Pi.org" 0 1
   (idx 103))
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Dev Board/Single Board Computer/Raspberry Pi/Raspberry Pi.org")
 (front-context-string . "#+TITLE: Raspber")
 (rear-context-string)
 (position . 1))
(#("Single Board Computer.org" 0 1
   (idx 104))
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Dev Board/Single Board Computer/Single Board Computer.org")
 (front-context-string . "#+TITLE: Single ")
 (rear-context-string)
 (position . 1))
(#("My Communication Skills Manual.org" 0 1
   (idx 105))
 (filename . "~/Org/Wiki/Self Enhancement/Communication/Data/Manuals/My Communication Skills Manual/My Communication Skills Manual.org")
 (front-context-string . "#+TITLE: My Comm")
 (rear-context-string)
 (position . 1))
(#("Dev Board.org" 0 1
   (idx 106))
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Dev Board/Dev Board.org")
 (front-context-string . "#+TITLE: Dev Boa")
 (rear-context-string)
 (position . 1))
(#("Stock.org" 0 1
   (idx 110))
 (filename . "~/Org/Wiki/Investing and Financing/Stock/Stock.org")
 (front-context-string . "\n\n* Intro\n\n\n** S")
 (rear-context-string)
 (position . 15))
(#("Revenge.org.gpg" 0 1
   (idx 118))
 (filename . "~/Org/Revenge/Revenge.org.gpg")
 (front-context-string . "#+TITLE: Revenge")
 (rear-context-string)
 (position . 1))
(#("Social Engineering.org" 0 1
   (idx 123))
 (filename . "~/Org/Wiki/Computer Technology/Crack/Data/Crack Methods/Social Engineering/Social Engineering.org")
 (front-context-string . "#+TITLE: Social ")
 (rear-context-string)
 (position . 1))
(#("Music.org" 0 1
   (idx 131))
 (filename . "~/Org/Wiki/Music/Music.org")
 (front-context-string . "#+TITLE: Music\n\n")
 (rear-context-string)
 (position . 1))
(#("UserScript.org" 0 1
   (idx 135))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Web/Web Technologies/UserScript/UserScript.org")
 (front-context-string . "#+TITLE: UserScr")
 (rear-context-string)
 (position . 1))
(#("BlackArch Linux.org" 0 1
   (idx 137))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Distributions/BlackArch Linux.org")
 (front-context-string . "#+TITLE: BlackAr")
 (rear-context-string)
 (position . 1))
(#("Embedded.org" 0 1
   (idx 138))
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Embedded/Embedded.org")
 (front-context-string . "#+TITLE: Embedde")
 (rear-context-string)
 (position . 1))
(#("Cyber Security.org" 0 1
   (idx 148))
 (filename . "~/Org/Wiki/Computer Technology/Cyber Security/Cyber Security.org")
 (front-context-string . "#+TITLE: Cyber S")
 (rear-context-string)
 (position . 1))
(#("My Linux Manual.org" 0 1
   (idx 149))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Data/Manuals/My Linux Manual/My Linux Manual.org")
 (front-context-string . "#+TITLE: My Linu")
 (rear-context-string)
 (position . 1))
(#("quicklisp.org" 0 1
   (idx 153))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Common Lisp/Data/Common Lisp Packages/quicklisp.org")
 (front-context-string . "#+TITLE: QuickLi")
 (rear-context-string)
 (position . 1))
(#("My GIMP Reference.org" 0 1
   (idx 156))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/GIMP/Data/Manuals/My GIMP Reference/My GIMP Reference.org")
 (front-context-string . "#+TITLE: My GIMP")
 (rear-context-string)
 (position . 1))
(#("GIMP.org" 0 1
   (idx 157))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/GIMP/GIMP.org")
 (front-context-string . "#+TITLE: GIMP\n\n*")
 (rear-context-string)
 (position . 1))
(#("Linux Troubleshooting.org" 0 1
   (idx 159))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Data/Manuals/Linux Troubleshooting/Linux Troubleshooting.org")
 (front-context-string . "#+TITLE: Linux T")
 (rear-context-string)
 (position . 1))
(#("Peer-to-Peer.org" 0 1
   (idx 160))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Network/Peer-to-Peer/Peer-to-Peer.org")
 (front-context-string . "#+TITLE: Peer-to")
 (rear-context-string)
 (position . 1))
(#("My Chinese Policy Reference.org" 0 1
   (idx 164))
 (filename . "~/Org/Wiki/Countries/China/Chinese Policy/Data/Manuals/My Chinese Policy Reference/My Chinese Policy Reference.org")
 (front-context-string . "#+TITLE: My Chin")
 (rear-context-string)
 (position . 1))
(#("Internet of Things.org" 0 1
   (idx 165))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Network/Internet of Things/Internet of Things.org")
 (front-context-string . "#+TITLE: Interne")
 (rear-context-string)
 (position . 1))
(#("My HTML Language Syntax Reference.org" 0 1
   (idx 166))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/HTML/Data/Manuals/My HTML Language Syntax Reference/My HTML Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My HTML")
 (rear-context-string)
 (position . 1))
(#("Quantum Information System.org" 0 1
   (idx 168))
 (filename . "~/Org/Wiki/Physics/Quantum Theory/Quantum Information System/Quantum Information System.org")
 (front-context-string . "#+TITLE: Quantum")
 (rear-context-string)
 (position . 1))
(#("Container.org" 0 1
   (idx 171))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Container/Container.org")
 (front-context-string . "#+TITLE: Contain")
 (rear-context-string)
 (position . 1))
(#("Chinese Censorship.org" 0 1
   (idx 173))
 (filename . "~/Org/Wiki/Countries/China/Chinese Censorship/Chinese Censorship.org")
 (front-context-string . "#+TITLE: China C")
 (rear-context-string)
 (position . 1))
(#("My Chinese Policy Usage Manual.org" 0 1
   (idx 174))
 (filename . "~/Org/Wiki/Countries/China/Chinese Policy/Data/Manuals/My Chinese Policy Usage Manual/My Chinese Policy Usage Manual.org")
 (front-context-string . "#+TITLE: My Chin")
 (rear-context-string)
 (position . 1))
(#("Chinese Policy.org" 0 1
   (idx 175))
 (filename . "~/Org/Wiki/Countries/China/Chinese Policy/Chinese Policy.org")
 (front-context-string . "#+TITLE: Chinese")
 (rear-context-string)
 (position . 1))
(#("Chinese Government.org" 0 1
   (idx 176))
 (filename . "~/Org/Wiki/Countries/China/Chinese Government/Chinese Government.org")
 (front-context-string . "#+TITLE: Chinese")
 (rear-context-string)
 (position . 1))
(#("Chinese Law.org" 0 1
   (idx 177))
 (filename . "~/Org/Wiki/Countries/China/Chinese Law/Chinese Law.org")
 (front-context-string . "#+TITLE: Chinese")
 (rear-context-string)
 (position . 1))
(#("My Chinese Law Database.org" 0 1
   (idx 178))
 (filename . "~/Org/Wiki/Countries/China/Chinese Law/Data/Manuals/My Chinese Law Database/My Chinese Law Database.org")
 (front-context-string . "#+TITLE: My Chin")
 (rear-context-string)
 (position . 1))
(#("China.org" 0 1
   (idx 180))
 (filename . "~/Org/Wiki/Countries/China/China.org")
 (front-context-string . "#+TITLE: China\n\n")
 (rear-context-string)
 (position . 1))
(#("GDB.org" 0 1
   (idx 182))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/GDB.org")
 (front-context-string . "#+TITLE: GDB\n\n* ")
 (rear-context-string)
 (position . 1))
(#("Machine Learning.org" 0 1
   (idx 183))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Artificial Intelligence/Machine Learning/Machine Learning.org")
 (front-context-string . "#+TITLE: Machine")
 (rear-context-string)
 (position . 1))
(#("Arch Linux.org" 0 1
   (idx 184))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Distributions/Arch Linux/Arch Linux.org")
 (front-context-string . "#+TITLE: Arch Li")
 (rear-context-string)
 (position . 1))
(#("Ethereum.org" 0 1
   (idx 185))
 (filename . "~/Org/Wiki/Economy/Currency/Digital Currency/Digital Currency Variants/Ethereum/Ethereum.org")
 (front-context-string . "#+TITLE: Ethereu")
 (rear-context-string)
 (position . 1))
(#("Bitcoin.org" 0 1
   (idx 186))
 (filename . "~/Org/Wiki/Economy/Currency/Digital Currency/Digital Currency Variants/Bitcoin/Bitcoin.org")
 (front-context-string . "#+TITLE: Bitcoin")
 (rear-context-string)
 (position . 1))
(#("Policy.org" 0 1
   (idx 190))
 (filename . "~/Org/Wiki/Government/Policy/Policy.org")
 (front-context-string . "#+TITLE: Policy\n")
 (rear-context-string)
 (position . 1))
(#("Scheme.org" 0 1
   (idx 192))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Scheme/Scheme.org")
 (front-context-string . "#+TITLE: Scheme ")
 (rear-context-string)
 (position . 1))
(#("Chrome Extensions.org" 0 1
   (idx 196))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Chrome/Data/Chrome Extensions/Chrome Extensions.org")
 (front-context-string . "#+TITLE: Chrome ")
 (rear-context-string)
 (position . 1))
(#("Kali Linux.org" 0 1
   (idx 197))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Distributions/Kali Linux/Kali Linux.org")
 (front-context-string . "#+TITLE: Kali Li")
 (rear-context-string)
 (position . 1))
(#("Sports.org" 0 1
   (idx 201))
 (filename . "~/Org/Wiki/Sports/Sports.org")
 (front-context-string . "#+TITLE: Sports\n")
 (rear-context-string)
 (position . 1))
(#("Skateboard.org" 0 1
   (idx 202))
 (filename . "~/Org/Wiki/Sports/Skateboard/Skateboard.org")
 (front-context-string . "#+TITLE: Skatebo")
 (rear-context-string)
 (position . 1))
(#("Disease Database.org" 0 1
   (idx 206))
 (filename . "~/Org/Wiki/Medicine/Disease/Disease Database/Disease Database.org")
 (front-context-string . "#+TITLE: Disease")
 (rear-context-string)
 (position . 1))
(#("Disease.org" 0 1
   (idx 207))
 (filename . "~/Org/Wiki/Medicine/Disease/Disease.org")
 (front-context-string . "#+TITLE: Disease")
 (rear-context-string)
 (position . 1))
(#("Porn.org" 0 1
   (idx 208))
 (filename . "~/Org/Wiki/Pornography/Porn/Porn.org")
 (front-context-string . "#+TITLE: Porn\n\n*")
 (rear-context-string)
 (position . 1))
(#("Thought.org" 0 1
   (idx 215))
 (filename . "~/Org/Wiki/Thought/Thought.org")
 (front-context-string . "#+TITLE: Thought")
 (rear-context-string)
 (position . 1))
(#("local accounts.org" 0 1
   (idx 216))
 (filename . "~/Org/Accounts/local accounts.org")
 (front-context-string . "#+TITLE: locally")
 (rear-context-string)
 (position . 1))
(#("Product.org" 0 1
   (idx 224))
 (filename . "~/Org/Wiki/Commercial Science/Product/Product.org")
 (front-context-string . "#+TITLE: Product")
 (rear-context-string)
 (position . 1))
(#("Command Line.org" 0 1
   (idx 225))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Command Line/Command Line.org")
 (front-context-string . "#+TITLE: Command")
 (rear-context-string)
 (position . 1))
(#("Reverse Engineering.org" 0 1
   (idx 227))
 (filename . "~/Org/Wiki/Computer Technology/Hack/Reverse Engineering/Reverse Engineering.org")
 (front-context-string . "#+TITLE: Reverse")
 (rear-context-string)
 (position . 1))
(#("Data Visualization.org" 0 1
   (idx 228))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Data Science/Data Visualization/Data Visualization.org")
 (front-context-string . "#+TITLE: Data Vi")
 (rear-context-string)
 (position . 1))
(#("Sexology.org" 0 1
   (idx 230))
 (filename . "~/Org/Wiki/Sexology/Sexology.org")
 (front-context-string . "#+TITLE: Sexolog")
 (rear-context-string)
 (position . 1))
(#("My Genetics Reference.org" 0 1
   (idx 231))
 (filename . "~/Org/Wiki/Biology/Genetics/Data/Manuals/My Genetics Reference/My Genetics Reference.org")
 (front-context-string . "#+TITLE: My Gene")
 (rear-context-string)
 (position . 1))
(#("codox.org" 0 1
   (idx 234))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/codox.org")
 (front-context-string . "#+TITLE: codox\n\n")
 (rear-context-string)
 (position . 1))
(#("Jupyter.org" 0 1
   (idx 235))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Jupyter.org")
 (front-context-string . "#+TITLE: Jupyter")
 (rear-context-string)
 (position . 1))
(#("IPython.org" 0 1
   (idx 236))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Data/Python Packages/IPython/IPython.org")
 (front-context-string . "#+TITLE: IPython")
 (rear-context-string)
 (position . 1))
(#("Open Source Hardware.org" 0 1
   (idx 238))
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Open Source Hardware/Open Source Hardware.org")
 (front-context-string . "#+TITLE: Open So")
 (rear-context-string)
 (position . 1))
(#("Programming Mathematics.org" 0 1
   (idx 239))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Programming Mathematics/Programming Mathematics.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
(#("Thinking.org" 0 1
   (idx 240))
 (filename . "~/Org/Wiki/Self Enhancement/Thinking/Thinking.org")
 (front-context-string . "#+TITLE: Thinkin")
 (rear-context-string)
 (position . 1))
(#("Blockchain.org" 0 1
   (idx 241))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Blockchain/Blockchain.org")
 (front-context-string . "#+TITLE: Blockch")
 (rear-context-string)
 (position . 1))
(#("Interpersonal Relationship.org" 0 1
   (idx 245))
 (filename . "~/Org/Wiki/Sociology/Social Intercourse/Interpersonal Relationship/Interpersonal Relationship.org")
 (front-context-string . "#+TITLE: Interpe")
 (rear-context-string)
 (position . 1))
(#("Hardware Programming.org" 0 1
   (idx 249))
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Hardware Programming/Hardware Programming.org")
 (front-context-string . "#+TITLE: Hardwar")
 (rear-context-string)
 (position . 1))
(#("Hardware.org" 0 1
   (idx 251))
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Hardware.org")
 (front-context-string . "#+TITLE: Hardwar")
 (rear-context-string)
 (position . 1))
(#("Graphviz.org" 0 1
   (idx 255))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Graphviz/Graphviz.org")
 (front-context-string . "#+TITLE: Graphvi")
 (rear-context-string)
 (position . 1))
(#("API.org" 0 1
   (idx 260))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/API/API.org")
 (front-context-string . "#+TITLE: API\n\n* ")
 (rear-context-string)
 (position . 1))
(#("Network.org" 0 1
   (idx 261))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Network/Network.org")
 (front-context-string . "#+TITLE: Network")
 (rear-context-string)
 (position . 1))
(#("Programmable Music.org" 0 1
   (idx 264))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Electric Music/Programmable Music/Programmable Music.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
(#("Electric Music.org" 0 1
   (idx 265))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Electric Music/Electric Music.org")
 (front-context-string . "#+TITLE: Electri")
 (rear-context-string)
 (position . 1))
(#("Artificial Intelligence.org" 0 1
   (idx 267))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Artificial Intelligence/Artificial Intelligence.org")
 (front-context-string . "#+TITLE: Artific")
 (rear-context-string)
 (position . 1))
(#("Qt.org" 0 1
   (idx 269))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/GUI/frameworks/Qt/Qt.org")
 (front-context-string . "#+TITLE: Qt\n\n* I")
 (rear-context-string)
 (position . 1))
(#("Data Science.org" 0 1
   (idx 271))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Data Science/Data Science.org")
 (front-context-string . "#+TITLE: Data Sc")
 (rear-context-string)
 (position . 1))
(#("Web.org" 0 1
   (idx 272))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Web/Web.org")
 (front-context-string . "#+TITLE: Web Imp")
 (rear-context-string)
 (position . 1))
(#("Implementations.org" 0 1
   (idx 273))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Implementations.org")
 (front-context-string . "#+TITLE: Impleme")
 (rear-context-string)
 (position . 1))
(#("GnuPG.org" 0 1
   (idx 274))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/GnuPG.org")
 (front-context-string . "#+TITLE: GnuPG\n\n")
 (rear-context-string)
 (position . 1))
(#("Markdown.org" 0 1
   (idx 275))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Markdown/Markdown.org")
 (front-context-string . "#+TITLE: Markdow")
 (rear-context-string)
 (position . 1))
(#("Testing.org" 0 1
   (idx 281))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Testing/Testing.org")
 (front-context-string . "#+TITLE: Testing")
 (rear-context-string)
 (position . 1))
(#("Program Design.org" 0 1
   (idx 282))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Program Design/Program Design.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
(#("Programming Glossary.org" 0 1
   (idx 283))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Data/Manuals/Programming Glossary/Programming Glossary.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
(#("Distributed Programming.org" 0 1
   (idx 288))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Programming Paradigms/Distributed Programming/Distributed Programming.org")
 (front-context-string . "#+TITLE: Distrib")
 (rear-context-string)
 (position . 1))
(#("gnuplot.org" 0 1
   (idx 290))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/gnuplot/gnuplot.org")
 (front-context-string . "#+TITLE: gnuplot")
 (rear-context-string)
 (position . 1))
(#("Overtone.org" 0 1
   (idx 291))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Overtone.org")
 (front-context-string . "#+TITLE: Overton")
 (rear-context-string)
 (position . 1))
(#("Investing and Financing.org" 0 1
   (idx 292))
 (filename . "~/Org/Wiki/Investing and Financing/Investing and Financing.org")
 (front-context-string . "#+TITLE: Investi")
 (rear-context-string)
 (position . 1))
(#("My Argumentation Manual.org" 0 1
   (idx 295))
 (filename . "~/Org/Wiki/Reasoning Science/Logic/Argumentation/Data/Manuals/My Argumentation Manual/My Argumentation Manual.org")
 (front-context-string . "#+TITLE: My Argu")
 (rear-context-string)
 (position . 1))
(#("Make Love.org" 0 1
   (idx 298))
 (filename . "~/Org/Wiki/Love/Make Love/Make Love.org")
 (front-context-string . "#+TITLE: Make Lo")
 (rear-context-string)
 (position . 1))
(#("Photograph.org" 0 1
   (idx 299))
 (filename . "~/Org/Wiki/Photograph/Photograph.org")
 (front-context-string . "#+TITLE: Photogr")
 (rear-context-string)
 (position . 1))
(#("Theology.org" 0 1
   (idx 300))
 (filename . "~/Org/Wiki/Religion/Theology/Theology.org")
 (front-context-string . "#+TITLE: Theolog")
 (rear-context-string)
 (position . 1))
(#("Logic.org" 0 1
   (idx 302))
 (filename . "~/Org/Wiki/Reasoning Science/Logic/Logic.org")
 (front-context-string . "#+TITLE: Logic\n\n")
 (rear-context-string)
 (position . 1))
(#("Linux Distributions.org" 0 1
   (idx 306))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Distributions/Linux Distributions.org")
 (front-context-string . "#+TITLE: Linux D")
 (rear-context-string)
 (position . 1))
(#("Work.org" 0 1
   (idx 308))
 (filename . "~/Org/Wiki/Work/Work.org")
 (front-context-string . "#+TITLE: Work\n\n*")
 (rear-context-string)
 (position . 1))
(#("DevOps.org" 0 1
   (idx 310))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/DevOps/DevOps.org")
 (front-context-string . "#+TITLE: DevOps\n")
 (rear-context-string)
 (position . 1))
(#("Male and Female.org" 0 1
   (idx 315))
 (filename . "~/Org/Wiki/Sociology/Male and Female/Male and Female.org")
 (front-context-string . "#+TITLE: Male an")
 (rear-context-string)
 (position . 1))
(#("Sociology.org" 0 1
   (idx 316))
 (filename . "~/Org/Wiki/Sociology/Sociology.org")
 (front-context-string . "#+TITLE: Sociolo")
 (rear-context-string)
 (position . 1))
(#("Knowledge Management.org" 0 1
   (idx 317))
 (filename . "~/Org/Wiki/Self Enhancement/Knowledge Management/Knowledge Management.org")
 (front-context-string . "#+TITLE: Knowled")
 (rear-context-string)
 (position . 1))
(#("Leadership.org" 0 1
   (idx 322))
 (filename . "~/Org/Wiki/Self Enhancement/Leadership/Leadership.org")
 (front-context-string . "#+TITLE: Leaders")
 (rear-context-string)
 (position . 1))
(#("My Algorithm Manual.org" 0 1
   (idx 326))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Algorithm/Data/Manuals/My Algorithm Manual/My Algorithm Manual.org")
 (front-context-string . "#+TITLE: My Algo")
 (rear-context-string)
 (position . 1))
(#("Boot.org" 0 1
   (idx 331))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Boot.org")
 (front-context-string . "#+TITLE: Boot\n\n*")
 (rear-context-string)
 (position . 1))
(#("Leiningen.org" 0 1
   (idx 332))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Leiningen.org")
 (front-context-string . "#+TITLE: Leining")
 (rear-context-string)
 (position . 1))
(#("ClojureScript Packages.org" 0 1
   (idx 336))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/Data/ClojureScript Packages/ClojureScript Packages.org")
 (front-context-string . "#+TITLE: Clojure")
 (rear-context-string)
 (position . 1))
(#("Quantum Theory.org" 0 1
   (idx 339))
 (filename . "~/Org/Wiki/Physics/Quantum Theory/Quantum Theory.org")
 (front-context-string . "#+TITLE: Quantum")
 (rear-context-string)
 (position . 1))
(#("Philosophy.org" 0 1
   (idx 344))
 (filename . "~/Org/Wiki/Philosophy/Philosophy.org")
 (front-context-string . "#+TITLE: Philoso")
 (rear-context-string)
 (position . 1))
(#("KDE.org" 0 1
   (idx 349))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/KDE/KDE.org")
 (front-context-string . "#+TITLE: KDE\n\n* ")
 (rear-context-string)
 (position . 1))
(#("Software Development.org" 0 1
   (idx 352))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Software Development/Software Development.org")
 (front-context-string . "#+TITLE: Softwar")
 (rear-context-string)
 (position . 1))
(#("Linux Kernel.org" 0 1
   (idx 355))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Kernel/Linux Kernel.org")
 (front-context-string . "#+TITLE: Linux K")
 (rear-context-string)
 (position . 1))
(#("OpenWrt.org" 0 1
   (idx 357))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/OpenWrt/OpenWrt.org")
 (front-context-string . "#+TITLE: OpenWrt")
 (rear-context-string)
 (position . 1))
(#("iOS.org" 0 1
   (idx 358))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/iOS/iOS.org")
 (front-context-string . "#+TITLE: iOS\n\n* ")
 (rear-context-string)
 (position . 1))
(#("Android.org" 0 1
   (idx 359))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Android/Android.org")
 (front-context-string . "#+TITLE: Android")
 (rear-context-string)
 (position . 1))
(#("Microsoft Windows.org" 0 1
   (idx 360))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Microsoft Windows/Microsoft Windows.org")
 (front-context-string . "#+TITLE: Microso")
 (rear-context-string)
 (position . 1))
(#("GNU.org" 0 1
   (idx 361))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/GNU/GNU.org")
 (front-context-string . "#+TITLE: GNU Ope")
 (rear-context-string)
 (position . 1))
(#("macOS.org" 0 1
   (idx 362))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/macOS/macOS.org")
 (front-context-string . "#+TITLE: macOS\n\n")
 (rear-context-string)
 (position . 1))
(#("Linux.org" 0 1
   (idx 364))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux.org")
 (front-context-string . "#+TITLE: GNU/Lin")
 (rear-context-string)
 (position . 1))
(#("Lisp Machines.org" 0 1
   (idx 366))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Lisp Machines/Lisp Machines.org")
 (front-context-string . "#+TITLE: Lisp Ma")
 (rear-context-string)
 (position . 1))
(#("Operating System.org" 0 1
   (idx 367))
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Operating System.org")
 (front-context-string . "#+TITLE: Operati")
 (rear-context-string)
 (position . 1))
(#("Buddhism.org" 0 1
   (idx 374))
 (filename . "~/Org/Wiki/Religion/Buddhism/Buddhism.org")
 (front-context-string . "#+TITLE: Buddhis")
 (rear-context-string)
 (position . 1))
(#("Incanter.org" 0 1
   (idx 376))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Incanter.org")
 (front-context-string . "#+TITLE: Incante")
 (rear-context-string)
 (position . 1))
(#("IRC.org" 0 1
   (idx 378))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/IRC/IRC.org")
 (front-context-string . "#+TITLE: IRC\n\n* ")
 (rear-context-string)
 (position . 1))
(#("JavaScript Packages.org" 0 1
   (idx 383))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/JavaScript Packages/JavaScript Packages.org")
 (front-context-string . "#+TITLE: JavaScr")
 (rear-context-string)
 (position . 1))
(#("Processing.org" 0 1
   (idx 384))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Processing/Processing.org")
 (front-context-string . "#+TITLE: Process")
 (rear-context-string)
 (position . 1))
(#("Matlab.org" 0 1
   (idx 389))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Matlab/Matlab.org")
 (front-context-string . "#+TITLE: Matlab ")
 (rear-context-string)
 (position . 1))
(#("Julia Packages.org" 0 1
   (idx 390))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Julia/Data/Julia Packages/Julia Packages.org")
 (front-context-string . "#+TITLE: Julia P")
 (rear-context-string)
 (position . 1))
(#("JSON.org" 0 1
   (idx 392))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JSON/JSON.org")
 (front-context-string . "#+TITLE: JSON\n\n*")
 (rear-context-string)
 (position . 1))
(#("XML.org" 0 1
   (idx 393))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/XML/XML.org")
 (front-context-string . "#+TITLE: XML\n\n* ")
 (rear-context-string)
 (position . 1))
(#("NewSQL.org" 0 1
   (idx 396))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/NewSQL/NewSQL.org")
 (front-context-string . "#+TITLE: NewSQL\n")
 (rear-context-string)
 (position . 1))
(#("Java Packages.org" 0 1
   (idx 398))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Java/Data/Java Packages/Java Packages.org")
 (front-context-string . "#+TITLE: Java Pa")
 (rear-context-string)
 (position . 1))
(#("Rust Packages.org" 0 1
   (idx 402))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Rust/Data/Rust Packages/Rust Packages.org")
 (front-context-string . "#+TITLE: Rust Pa")
 (rear-context-string)
 (position . 1))
(#("Go Packages.org" 0 1
   (idx 403))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Go/Data/Go Packages/Go Packages.org")
 (front-context-string . "#+TITLE: Go Pack")
 (rear-context-string)
 (position . 1))
(#("Perl.org" 0 1
   (idx 405))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Perl/Perl.org")
 (front-context-string . "#+TITLE: Perl Pr")
 (rear-context-string)
 (position . 1))
(#("Common Lisp Packages.org" 0 1
   (idx 408))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Common Lisp/Data/Common Lisp Packages/Common Lisp Packages.org")
 (front-context-string . "#+TITLE: Common ")
 (rear-context-string)
 (position . 1))
(#("Python Packages.org" 0 1
   (idx 410))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Data/Python Packages/Python Packages.org")
 (front-context-string . "#+TITLE: Python ")
 (rear-context-string)
 (position . 1))
(#("Ruby Packages.org" 0 1
   (idx 411))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Ruby/Data/Ruby Packages/Ruby Packages.org")
 (front-context-string . "#+TITLE: Ruby Pa")
 (rear-context-string)
 (position . 1))
(#("Clojure Packages.org" 0 1
   (idx 412))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Clojure Packages.org")
 (front-context-string . "#+TITLE: Clojure")
 (rear-context-string)
 (position . 1))
(#("Regular Expressions.org" 0 1
   (idx 417))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Regular Expressions/Regular Expressions.org")
 (front-context-string . "#+TITLE: Regular")
 (rear-context-string)
 (position . 1))
(#("My Docker Reference.org" 0 1
   (idx 418))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Docker/Data/Manuals/My Docker Reference/My Docker Reference.org")
 (front-context-string . "#+TITLE: My Dock")
 (rear-context-string)
 (position . 1))
(#("My Evil Hack Manual.org" 0 1
   (idx 422))
 (filename . "~/Org/Wiki/Computer Technology/Hack/Data/Manuals/My Evil Hack Manual/My Evil Hack Manual.org")
 (front-context-string . "#+TITLE: My Evil")
 (rear-context-string)
 (position . 1))
(#("PowerShell.org" 0 1
   (idx 423))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/PowerShell/PowerShell.org")
 (front-context-string . "#+TITLE: PowerSh")
 (rear-context-string)
 (position . 1))
(#("systemd.org" 0 1
   (idx 425))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/systemd/systemd.org")
 (front-context-string . "#+TITLE: systemd")
 (rear-context-string)
 (position . 1))
(#("Novel Books.org" 0 1
   (idx 426))
 (filename . "~/Org/Wiki/Literature/Novels/Data/Novel Books/Novel Books.org")
 (front-context-string . "#+TITLE: Novel B")
 (rear-context-string)
 (position . 1))
(#("Self Enhancement.org" 0 1
   (idx 428))
 (filename . "~/Org/Wiki/Self Enhancement/Self Enhancement.org")
 (front-context-string . "#+TITLE: Self En")
 (rear-context-string)
 (position . 1))
(#("Kotlin.org" 0 1
   (idx 438))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Kotlin/Kotlin.org")
 (front-context-string . "#+TITLE: Kotlin ")
 (rear-context-string)
 (position . 1))
(#("Porn Novel Books.org" 0 1
   (idx 440))
 (filename . "~/Org/Wiki/Pornography/Porn/Porn Novels/Data/Porn Novel Books/Porn Novel Books.org")
 (front-context-string . "#+TITLE: Porn No")
 (rear-context-string)
 (position . 1))
(#("Statistics.org" 0 1
   (idx 444))
 (filename . "~/Org/Wiki/Mathematics/Statistics/Statistics.org")
 (front-context-string . "#+TITLE: Statist")
 (rear-context-string)
 (position . 1))
(#("Internet Marketing.org" 0 1
   (idx 445))
 (filename . "~/Org/Wiki/Commercial Science/Marketing/Internet Marketing/Internet Marketing.org")
 (front-context-string . "#+TITLE: Interne")
 (rear-context-string)
 (position . 1))
(#("Politics.org" 0 1
   (idx 447))
 (filename . "~/Org/Wiki/Politics/Politics.org")
 (front-context-string . "#+TITLE: Politic")
 (rear-context-string)
 (position . 1))
(#("Conky.org" 0 1
   (idx 448))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Conky/Conky.org")
 (front-context-string . "* Intro\n\n\n** Fea")
 (rear-context-string)
 (position . 1))
(#("Functional Programming.org" 0 1
   (idx 449))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Programming Paradigms/Functional Programming/Functional Programming.org")
 (front-context-string . "#+TITLE: Functio")
 (rear-context-string)
 (position . 1))
(#("Literate Programming.org" 0 1
   (idx 451))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Programming Paradigms/Literate Programming/Literate Programming.org")
 (front-context-string . "#+TITLE: Literat")
 (rear-context-string)
 (position . 1))
(#("Programming Paradigms.org" 0 1
   (idx 452))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Programming Paradigms/Programming Paradigms.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
(#("Library of Babel.org" 0 1
   (idx 457))
 (filename . "~/.emacs.d/Org-mode/Library of Babel/Library of Babel.org")
 (front-context-string . "#+TITLE: Library")
 (rear-context-string)
 (position . 1))
(#("Spiritual.org" 0 1
   (idx 461))
 (filename . "~/Org/Wiki/Spiritual/Spiritual.org")
 (front-context-string . "* Intro\n\n** \"灵修\"")
 (rear-context-string)
 (position . 1))
(#("Vagrant.org" 0 1
   (idx 468))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Vagrant/Vagrant.org")
 (front-context-string . "* Intro\n\nVagrant")
 (rear-context-string)
 (position . 1))
(#("Japanese.org" 0 1
   (idx 469))
 (filename . "~/Org/Wiki/Linguistics/Japanese/Japanese.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
(#("English.org" 0 1
   (idx 470))
 (filename . "~/Org/Wiki/Linguistics/English/English.org")
 (front-context-string . "#+TITLE: English")
 (rear-context-string)
 (position . 1))
(#("诸子百家.org" 0 1
   (idx 475))
 (filename . "~/Org/Wiki/Thought/诸子百家/诸子百家.org")
 (front-context-string . "* Intro\n\n** 沿革\n\n")
 (rear-context-string)
 (position . 1))
(#("My Emacs Lisp Regexp Reference.org" 0 1
   (idx 476))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs Lisp/Data/Manuals/My Emacs Lisp Regexp Reference.org")
 (front-context-string . "\n\n* Demo\n\n** mat")
 (rear-context-string . "Regexp Reference")
 (position . 40))
(#("My Emacs Lisp Examples.org" 0 1
   (idx 477))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs Lisp/Data/Manuals/My Emacs Lisp Examples/My Emacs Lisp Examples.org")
 (front-context-string . "\n\n* Command\n\n** ")
 (rear-context-string . "cs Lisp Examples")
 (position . 32))
(#("My Emacs Lisp Syntax Reference.org" 0 1
   (idx 478))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs Lisp/Data/Manuals/My Emacs Lisp Syntax Reference/My Emacs Lisp Syntax Reference.org")
 (front-context-string . "#+TITLE: My Emac")
 (rear-context-string)
 (position . 1))
(#("Redis.org" 0 1
   (idx 479))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/NoSQL/Redis/Redis.org")
 (front-context-string . "* Intro\n\nRedis i")
 (rear-context-string)
 (position . 1))
(#("MongoDB.org" 0 1
   (idx 480))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/NoSQL/MongoDB/MongoDB.org")
 (front-context-string . "* Intro\n\nA high-")
 (rear-context-string)
 (position . 1))
(#("Git.org" 0 1
   (idx 482))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Git/Git.org")
 (front-context-string . "#+TITLE: Git\n\n* ")
 (rear-context-string)
 (position . 1))
(#("Assembly.org" 0 1
   (idx 483))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Assembly/Assembly.org")
 (front-context-string . "#+TITLE: Assembl")
 (rear-context-string)
 (position . 1))
(#("PHP.org" 0 1
   (idx 484))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/PHP/PHP.org")
 (front-context-string . "#+TITLE: PHP Pro")
 (rear-context-string)
 (position . 1))
(#("Physics.org" 0 1
   (idx 485))
 (filename . "~/Org/Wiki/Physics/Physics.org")
 (front-context-string . "#+TITLE: Physics")
 (rear-context-string)
 (position . 1))
(#("My Git Usage Reference.org" 0 1
   (idx 486))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Git/Data/Manuals/My Git Usage Reference/My Git Usage Reference.org")
 (front-context-string . "#+TITLE: My Git ")
 (rear-context-string)
 (position . 1))
(#("Yi Learning.org" 0 1
   (idx 487))
 (filename . "~/Org/Wiki/Mysterious Culture/Yi Learning/Yi Learning.org")
 (front-context-string . "#+TITLE: Yi Lear")
 (rear-context-string)
 (position . 1))
(#("Emacs Lisp.org" 0 1
   (idx 489))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs Lisp/Emacs Lisp.org")
 (front-context-string . "* Intro\n\n\n** Fea")
 (rear-context-string)
 (position . 1))
(#("Common Lisp.org" 0 1
   (idx 492))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Common Lisp/Common Lisp.org")
 (front-context-string . "#+TITLE: Common ")
 (rear-context-string)
 (position . 1))
(#("My ClojureScript Examples.org" 0 1
   (idx 497))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/Data/Manuals/My ClojureScript Examples/My ClojureScript Examples.org")
 (front-context-string . "#+TITLE: My Cloj")
 (rear-context-string)
 (position . 1))
(#("My ClojureScript's Standard Library.org" 0 1
   (idx 498))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/Data/Manuals/My ClojureScript's Standard Library/My ClojureScript's Standard Library.org")
 (front-context-string . "#+TITLE: My Cloj")
 (rear-context-string)
 (position . 1))
(#("My ClojureScript Language Syntax Reference.org" 0 1
   (idx 499))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/Data/Manuals/My ClojureScript Language Syntax Reference/My ClojureScript Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Cloj")
 (rear-context-string)
 (position . 1))
(#("Crack Methods.org" 0 1
   (idx 500))
 (filename . "~/Org/Wiki/Computer Technology/Crack/Data/Crack Methods/Crack Methods.org")
 (front-context-string . "#+TITLE: Crack M")
 (rear-context-string)
 (position . 1))
(#("My Docker Manual.org" 0 1
   (idx 501))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Docker/Data/Manuals/My Docker Manual/My Docker Manual.org")
 (front-context-string . "#+TITLE: My Dock")
 (rear-context-string)
 (position . 1))
(#("Docker.org" 0 1
   (idx 502))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Docker/Docker.org")
 (front-context-string . "#+TITLE: Docker\n")
 (rear-context-string)
 (position . 1))
(#("Prolog.org" 0 1
   (idx 505))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Prolog/Prolog.org")
 (front-context-string . "#+TITLE: Prolog ")
 (rear-context-string)
 (position . 1))
(#("Lua.org" 0 1
   (idx 506))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lua/Lua.org")
 (front-context-string . "#+TITLE: Lua Pro")
 (rear-context-string)
 (position . 1))
(#("LaTeX.org" 0 1
   (idx 507))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/TeX/LaTeX/LaTeX.org")
 (front-context-string . "#+TITLE: LaTeX\n\n")
 (rear-context-string)
 (position . 1))
(#("HTML5.org" 0 1
   (idx 508))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/HTML/HTML5/HTML5.org")
 (front-context-string . "#+TITLE: HTML5\n\n")
 (rear-context-string)
 (position . 1))
(#("Programmer.org" 0 1
   (idx 511))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programmer/Programmer.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
(#("Open Source.org" 0 1
   (idx 512))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Open Source/Open Source.org")
 (front-context-string . "#+TITLE: Open So")
 (rear-context-string)
 (position . 1))
(#("Programming Concepts.org" 0 1
   (idx 513))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Concepts/Programming Concepts.org")
 (front-context-string . "* Introspection ")
 (rear-context-string)
 (position . 1))
(#("My Data Structures Reference.org" 0 1
   (idx 514))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Data Structure/Data/Manuals/My Data Structures Reference/My Data Structures Reference.org")
 (front-context-string . "#+TITLE: My Data")
 (rear-context-string)
 (position . 1))
(#("Data Structure.org" 0 1
   (idx 515))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Data Structure/Data Structure.org")
 (front-context-string . "#+TITLE: Data St")
 (rear-context-string)
 (position . 1))
(#("My Algorithms Reference.org" 0 1
   (idx 516))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Algorithm/Data/Manuals/My Algorithms Reference/My Algorithms Reference.org")
 (front-context-string . "#+TITLE: My Algo")
 (rear-context-string)
 (position . 1))
(#("Algorithm.org" 0 1
   (idx 517))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Algorithm/Algorithm.org")
 (front-context-string . "#+TITLE: Algorit")
 (rear-context-string)
 (position . 1))
(#("Mathematics Formula Reference.org" 0 1
   (idx 519))
 (filename . "~/Org/Wiki/Mathematics/Data/Manuals/Mathematics Formula Reference/Mathematics Formula Reference.org")
 (front-context-string . "#+TITLE: Mathema")
 (rear-context-string)
 (position . 1))
(#("Mathematics Terms Reference.org" 0 1
   (idx 520))
 (filename . "~/Org/Wiki/Mathematics/Data/Manuals/Mathematics Terms Reference/Mathematics Terms Reference.org")
 (front-context-string . "#+TITLE: Mathema")
 (rear-context-string)
 (position . 1))
(#("Internet Censorship.org" 0 1
   (idx 526))
 (filename . "~/Org/Wiki/Computer Technology/Internet Censorship/Internet Censorship.org")
 (front-context-string . "#+TITLE: Interne")
 (rear-context-string)
 (position . 1))
(#("My Clojure Examples.org" 0 1
   (idx 532))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Manuals/My Clojure Examples/My Clojure Examples.org")
 (front-context-string . "* Print\n\n** form")
 (rear-context-string . "cumentation]]\n\n\n")
 (position . 1154))
(#("My Clojure Language Syntax Reference.org" 0 1
   (idx 533))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Manuals/My Clojure Language Syntax Reference/My Clojure Language Syntax Reference.org")
 (front-context-string . "\n\n** nil, truth ")
 (rear-context-string . " Data Structures")
 (position . 33303))
(#("CSS.org" 0 1
   (idx 535))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/CSS/CSS.org")
 (front-context-string . "#+TITLE: CSS Pro")
 (rear-context-string)
 (position . 1))
(#("My CSS Language Syntax Reference.org" 0 1
   (idx 536))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/CSS/Data/Manuals/My CSS Language Syntax Reference/My CSS Language Syntax Reference.org")
 (front-context-string . "* Concepts\n\n** A")
 (rear-context-string)
 (position . 1))
(#("HTML.org" 0 1
   (idx 537))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/HTML/HTML.org")
 (front-context-string . "#+TITLE: HTML Pr")
 (rear-context-string)
 (position . 1))
(#("My JavaScript Language Examples.org" 0 1
   (idx 538))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Manuals/My JavaScript Language Examples/My JavaScript Language Examples.org")
 (front-context-string . "* Intro\n\n\n* Java")
 (rear-context-string)
 (position . 1))
(#("My JavaScript Language Syntax Reference.org" 0 1
   (idx 539))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Manuals/My JavaScript Language Syntax Reference/My JavaScript Language Syntax Reference.org")
 (front-context-string . "* How JavaScript")
 (rear-context-string)
 (position . 1))
(#("JavaScript.org" 0 1
   (idx 540))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/JavaScript.org")
 (front-context-string . "#+TITLE: JavaScr")
 (rear-context-string)
 (position . 1))
(#("My C Examples.org" 0 1
   (idx 541))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C/Data/Manuals/My C Examples/My C Examples.org")
 (front-context-string . "* Libraries\n\n** ")
 (rear-context-string)
 (position . 1))
(#("My C Language Syntax Reference.org" 0 1
   (idx 542))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C/Data/Manuals/My C Language Syntax Reference/My C Language Syntax Reference.org")
 (front-context-string . "* Intro\n\n** Comp")
 (rear-context-string)
 (position . 1))
(#("C Programming Language" 0 1
   (idx 543))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C/C.org")
 (front-context-string . "* Intro\n\n** Abou")
 (rear-context-string)
 (position . 1))
(#("GitHub.org" 0 1
   (idx 544))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Git/GitHub.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
(#("My Go Language Examples.org" 0 1
   (idx 545))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Go/Data/Manuals/My Go Language Examples/My Go Language Examples.org")
 (front-context-string . "#+TITLE: My Go L")
 (rear-context-string)
 (position . 1))
(#("My Go Language Syntax Reference.org" 0 1
   (idx 546))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Go/Data/Manuals/My Go Language Syntax Reference/My Go Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Go L")
 (rear-context-string)
 (position . 1))
(#("Go.org" 0 1
   (idx 547))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Go/Go.org")
 (front-context-string . "#+TITLE: Go Prog")
 (rear-context-string)
 (position . 1))
(#("My Julia Language Examples.org" 0 1
   (idx 549))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Julia/Data/Manuals/My Julia Language Examples/My Julia Language Examples.org")
 (front-context-string . "* System\n\n** Inv")
 (rear-context-string)
 (position . 1))
(#("My Julia Language Syntax Reference.org" 0 1
   (idx 550))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Julia/Data/Manuals/My Julia Language Syntax Reference/My Julia Language Syntax Reference.org")
 (front-context-string . "* Variables -- ~")
 (rear-context-string)
 (position . 1))
(#("Julia.org" 0 1
   (idx 551))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Julia/Julia.org")
 (front-context-string . "#+TITLE: Julia P")
 (rear-context-string)
 (position . 1))
(#("Looks.org" 0 1
   (idx 552))
 (filename . "~/Org/Wiki/Looks/Looks.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
(#("Swift.org" 0 1
   (idx 553))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Swift/Swift.org")
 (front-context-string . "#+TITLE: Swift P")
 (rear-context-string)
 (position . 1))
(#("Rust.org" 0 1
   (idx 557))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Rust/Rust.org")
 (front-context-string . "#+TITLE: Rust Pr")
 (rear-context-string)
 (position . 1))
(#("NoSQL.org" 0 1
   (idx 558))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/NoSQL/NoSQL.org")
 (front-context-string . "#+TITLE: NoSQL\n\n")
 (rear-context-string)
 (position . 1))
(#("PostgresQL.org" 0 1
   (idx 559))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/PostgresQL/PostgresQL.org")
 (front-context-string . "* Intro\n\n*A soph")
 (rear-context-string)
 (position . 1))
(#("MariaDB.org" 0 1
   (idx 560))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/MariaDB/MariaDB.org")
 (front-context-string . "#+TITLE: MariaDB")
 (rear-context-string)
 (position . 1))
(#("MySQL.org" 0 1
   (idx 561))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/MySQL/MySQL.org")
 (front-context-string . "#+TITLE: MySQL\n\n")
 (rear-context-string)
 (position . 1))
(#("Database.org" 0 1
   (idx 563))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/Database.org")
 (front-context-string . "#+TITLE: Databas")
 (rear-context-string)
 (position . 1))
(#("My Java Examples.org" 0 1
   (idx 564))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Java/Data/Manuals/My Java Examples/My Java Examples.org")
 (front-context-string . "#+TITLE: My Java")
 (rear-context-string)
 (position . 1))
(#("My Java Language Syntax Reference.org" 0 1
   (idx 565))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Java/Data/Manuals/My Java Language Syntax Reference/My Java Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Java")
 (rear-context-string)
 (position . 1))
(#("Java.org" 0 1
   (idx 566))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Java/Java.org")
 (front-context-string . "#+TITLE: Java Pr")
 (rear-context-string)
 (position . 1))
(#("The Sex Mechanism.org" 0 1
   (idx 567))
 (filename . "~/Org/Wiki/Sexology/Data/Manuals/The Sex Mechanism/The Sex Mechanism.org")
 (front-context-string)
 (rear-context-string)
 (position . 1))
(#("My Bash Syntax Reference.org" 0 1
   (idx 569))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/Bash/Data/Manuals/My Bash Syntax Reference/My Bash Syntax Reference.org")
 (front-context-string . "* Common Environ")
 (rear-context-string)
 (position . 1))
(#("Shell.org" 0 1
   (idx 571))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/Shell.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
(#("Ruby.org" 0 1
   (idx 573))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Ruby/Ruby.org")
 (front-context-string . "#+TITLE: Ruby Pr")
 (rear-context-string)
 (position . 1))
(#("Hacker.org" 0 1
   (idx 574))
 (filename . "~/Org/Wiki/Computer Technology/Hack/Hacker/Hacker.org")
 (front-context-string . "* Hacker Ethic\n\n")
 (rear-context-string)
 (position . 1))
(#("Dark Net.org" 0 1
   (idx 575))
 (filename . "~/Org/Wiki/Computer Technology/Crack/Dark Net/Dark Net.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
(#("ClojureScript.org" 0 1
   (idx 576))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/ClojureScript.org")
 (front-context-string . "#+TITLE: Clojure")
 (rear-context-string)
 (position . 1))
(#("Startup.org" 0 1
   (idx 579))
 (filename . "~/Org/Wiki/Commercial Science/Startup/Startup.org")
 (front-context-string . "#+TITLE: Startup")
 (rear-context-string)
 (position . 1))
(#("ASCII.org" 0 1
   (idx 583))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/ASCII/ASCII.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
(#("Crack.org" 0 1
   (idx 584))
 (filename . "~/Org/Wiki/Computer Technology/Crack/Crack.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
(#("Hack.org" 0 1
   (idx 585))
 (filename . "~/Org/Wiki/Computer Technology/Hack/Hack.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
(#("Python.org" 0 1
   (idx 586))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Python.org")
 (front-context-string . "* Intro\n\n** Logo")
 (rear-context-string)
 (position . 1))
(#("Emacs.org" 0 1
   (idx 588))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs.org")
 (front-context-string . "#+TITLE: Emacs\n\n")
 (rear-context-string)
 (position . 1))
(#("Firefox.org" 0 1
   (idx 589))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Firefox/Firefox.org")
 (front-context-string . "#+TITLE: Firefox")
 (rear-context-string)
 (position . 1))
(#("Chrome.org" 0 1
   (idx 590))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Chrome/Chrome.org")
 (front-context-string . "* Intro\n\n\n\n** Sc")
 (rear-context-string)
 (position . 1))
(#("Pornography.org" 0 1
   (idx 592))
 (filename . "~/Org/Wiki/Pornography/Pornography.org")
 (front-context-string . "#+TITLE: Pornogr")
 (rear-context-string)
 (position . 1))
(#("Freelancer.org" 0 1
   (idx 593))
 (filename . "~/Org/Wiki/Work/Freelancer/Freelancer.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
(#("SQLite.org" 0 1
   (idx 594))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/SQLite/SQLite.org")
 (front-context-string . "#+TITLE: SQLite\n")
 (rear-context-string)
 (position . 1))
(#("Clojure.org" 0 1
   (idx 595))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Clojure.org")
 (front-context-string . "#+TITLE: Clojure")
 (rear-context-string)
 (position . 1))
(#("R.org" 0 1
   (idx 596))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/R/R.org")
 (front-context-string . "*** Manuals\n\n***")
 (rear-context-string . "S:\n: linux-gnu\n\n")
 (position . 14299))
(#("Learning.org" 0 1
   (idx 597))
 (filename . "~/Org/Wiki/Learning/Learning.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
(#("My Haskell Language Syntax Reference.org" 0 1
   (idx 598))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Haskell/Data/Manuals/My Haskell Language Syntax Reference/My Haskell Language Syntax Reference.org")
 (front-context-string . "* Expression\n\n* ")
 (rear-context-string)
 (position . 1))
(#("My Haskell Examples.org" 0 1
   (idx 599))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Haskell/Data/Manuals/My Haskell Examples/My Haskell Examples.org")
 (front-context-string . "** Prelude\n\nThe ")
 (rear-context-string)
 (position . 12))
(#("Haskell.org" 0 1
   (idx 600))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Haskell/Haskell.org")
 (front-context-string . "Haskell Data Ana")
 (rear-context-string . "is [0/1]\n\n- [ ] ")
 (position . 10457))
(#("Love.org" 0 1
   (idx 602))
 (filename . "~/Org/Wiki/Love/Love.org")
 (front-context-string . "#+TITLE: Love\n\n*")
 (rear-context-string)
 (position . 1))
(#("TeX Macro Packages.org" 0 1
   (idx 604))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/TeX/Data/TeX Macro Packages/TeX Macro Packages.org")
 (front-context-string . "#+TITLE: TeX Mac")
 (rear-context-string)
 (position . 1))
(#("Lisp.org" 0 1
   (idx 605))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Lisp.org")
 (front-context-string . "#+TITLE: Lisp\n\n*")
 (rear-context-string)
 (position . 1))
(#("Commands.org" 0 1
   (idx 606))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Commands.org")
 (front-context-string . "#+TITLE: Command")
 (rear-context-string)
 (position . 1))
(#("Softwares.org" 0 1
   (idx 609))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Softwares.org")
 (front-context-string . "#+TITLE: Softwar")
 (rear-context-string)
 (position . 1))
(#("Programming.org" 0 1
   (idx 611))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
(#("Computer Technology.org" 0 1
   (idx 612))
 (filename . "~/Org/Wiki/Computer Technology/Computer Technology.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
(#("Poem.org" 0 1
   (idx 613))
 (filename . "~/Org/Wiki/Literature/Poem/Poem.org")
 (front-context-string . "* Intro\n\n\n\n\n* Da")
 (rear-context-string)
 (position . 1))
(#("Internet.org" 0 1
   (idx 615))
 (filename . "~/Org/Wiki/Internet/Internet.org")
 (front-context-string . "#+TITLE: Interne")
 (rear-context-string)
 (position . 1))
(#("Kindle.org" 0 1
   (idx 618))
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Kindle/Kindle.org")
 (front-context-string . "#+TITLE: Kindle\n")
 (rear-context-string)
 (position . 1))
(#("Novels.org" 0 1
   (idx 621))
 (filename . "~/Org/Wiki/Literature/Novels/Novels.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
(#("Beauty.org" 0 1
   (idx 623))
 (filename . "~/Org/Beauty/Beauty.org")
 (front-context-string . "#+TITLE: Beauty\n")
 (rear-context-string)
 (position . 1))
(#("Experience" 0 1
   (idx 626))
 (filename . "~/Org/Experience/Experience.org")
 (front-context-string . "* Life Feeling\n\n")
 (rear-context-string)
 (position . 1))
(#("Myself" 0 1
   (idx 627))
 (filename . "~/Org/Myself/Myself.org")
 (front-context-string . "* My Info\n\n[[fil")
 (rear-context-string)
 (position . 1))
(#("Strategy" 0 1
   (idx 629))
 (filename . "~/Org/Wiki/Strategy/Strategy.org")
 (front-context-string . "* Intro\n\n** 名句思想")
 (rear-context-string)
 (position . 1))
(#("Travel" 0 1
   (idx 630))
 (filename . "~/Org/Wiki/Travel/Travel.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
(#("Law" 0 1
   (idx 632))
 (filename . "~/Org/Wiki/Law/Law.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
(#("My Applied Mathematics Formula Reference.org" 0 1
   (idx 633))
 (filename . "~/Org/Wiki/Mathematics/Data/Manuals/My Applied Mathematics Formula Reference/My Applied Mathematics Formula Reference.org")
 (front-context-string . "#+TITLE: Applied")
 (rear-context-string)
 (position . 1))
(#("Bookmarks (Org)" 0 1
   (idx 637))
 (filename . "~/Org/Bookmarks/Bookmarks.org")
 (front-context-string . "* Intro\n\n** TODO")
 (rear-context-string)
 (position . 1))
(#("Diary.org" 0 1
   (idx 638))
 (filename . "~/Org/Diary/Diary.org")
 (front-context-string . "#+CATEGORY: Diar")
 (rear-context-string)
 (position . 1))
(#("Accounts" 0 1
   (idx 640))
 (filename . "~/Org/Accounts/accounts.org.gpg")
 (front-context-string . "* Nick\n\nstardivi")
 (rear-context-string)
 (position . 1))
(#("Contacts.org" 0 1
   (idx 641))
 (filename . "~/Org/Contacts/Contacts.org")
 (front-context-string . "#+TITLE: Contact")
 (rear-context-string)
 (position . 1))
(#("Arch install.sh" 0 1
   (idx 643))
 (filename . "~/Git/Arch/install.sh")
 (front-context-string . "#!/usr/bin/env b")
 (rear-context-string)
 (position . 1))
(#("Writing" 0 1
   (idx 645))
 (filename . "~/Org/Wiki/Writing/Writing.org")
 (front-context-string . "* Words (文字)\n\n[[")
 (rear-context-string)
 (position . 1))
(#("Investing & Financing (Org)" 0 1
   (idx 649))
 (filename . "~/Org/Wiki/Investing and Financing/Investing and Financing.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
(#("Mathematics (Org)" 0 1
   (idx 651))
 (filename . "~/Org/Wiki/Mathematics/Mathematics.org")
 (front-context-string . "  - [ ] [[file+s")
 (rear-context-string . "学 同济大学数学系 [0/4]\n")
 (position . 156))
(#("Psychology (Org)" 0 1
   (idx 652))
 (filename . "~/Org/Wiki/Psychology/Psychology.org")
 (front-context-string . " Tips\n\n- 心怀期待更快乐")
 (rear-context-string . "* Books\n\n* Small")
 (position . 36))
(#("Literature (Org)" 0 1
   (idx 653))
 (filename . "~/Org/Wiki/Literature/Literature.org")
 (front-context-string)
 (rear-context-string . "* Data\n\n** Books")
 (position . 27))
(#("Kung Fu (Org)" 0 1
   (idx 654))
 (filename . "~/Org/Wiki/Kung Fu/Kung Fu.org")
 (front-context-string . "* Urgent 易筋经 (mu")
 (rear-context-string)
 (position . 1))
(#("Reading (Org)" 0 1
   (idx 657))
 (filename . "~/Org/Wiki/Reading/Reading.org")
 (front-context-string . "[[file:Literatur")
 (rear-context-string . "Literature (文学)\n")
 (position . 30))
(#("Wiki (Org)" 0 1
   (idx 659))
 (filename . "~/Org/Wiki/Wiki.org")
 (front-context-string . "[[file:Reading/R")
 (rear-context-string . "\n* Reading (阅读)\n")
 (position . 59))
(#("INDEX (Org)" 0 1
   (idx 660))
 (filename . "~/Org/INDEX.org")
 (front-context-string . "* Learning (学习)\n")
 (rear-context-string . "  =精于心, 简于形.=\n\n\n")
 (position . 164))
(#("Programming Language Design.org<2>" 0 1
   (idx 53))
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Programming Language Design/Programming Language Design.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
(#("Quantum Information System.org<2>" 0 1
   (idx 168))
 (filename . "~/Org/Wiki/Physics/Quantum Theory/Quantum Information System/Quantum Information System.org")
 (front-context-string . "#+TITLE: Quantum")
 (rear-context-string)
 (position . 1))
)