;;;; Emacs Bookmark Format Version 1 ;;;; -*- coding: utf-8 -*- 
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Crack/Data/Books/An Augmented Penetration Testing Framework for Mobile Devices on 802.11 ac Wireless Networks.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Crack/Data/Books/An Augmented Penetration Testing Framework for Mobile Devices on 802.11 ac Wireless Networks.pdf")
 (position . 1)
 (page . 50)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("My China Government Administration Manual.org"
 (filename . "~/Org/Wiki/Government/Data/Manuals/My China Government Administration Manual/My China Government Administration Manual.org")
 (front-context-string . "#+TITLE: My Chin")
 (rear-context-string)
 (position . 1))
("Security.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Security/Security.org")
 (front-context-string . "#+TITLE: Securit")
 (rear-context-string)
 (position . 1))
("Product.org"
 (filename . "~/Org/Wiki/Commercial Science/Product/Product.org")
 (front-context-string . "#+TITLE: Product")
 (rear-context-string)
 (position . 1))
("Command Line.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Command Line/Command Line.org")
 (front-context-string . "#+TITLE: Command")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Implementations/DevOps/Data/Books/Infrastructure as Code.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/DevOps/Data/Books/Infrastructure as Code.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.6214039125431531)
 (handler . pdf-view-bookmark-jump-handler))
("Reverse Engineering.org"
 (filename . "~/Org/Wiki/Computer Technology/Hack/Reverse Engineering/Reverse Engineering.org")
 (front-context-string . "#+TITLE: Reverse")
 (rear-context-string)
 (position . 1))
("Data Visualization.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Data Science/Data Visualization/Data Visualization.org")
 (front-context-string . "#+TITLE: Data Vi")
 (rear-context-string)
 (position . 1))
("Nmap.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Nmap/Nmap.org")
 (front-context-string . "#+TITLE: Nmap\n\n*")
 (rear-context-string)
 (position . 1))
("Sexology.org"
 (filename . "~/Org/Wiki/Sexology/Sexology.org")
 (front-context-string . "#+TITLE: Sexolog")
 (rear-context-string)
 (position . 1))
("PUA.org"
 (filename . "~/Org/Wiki/Love/Love Theories/PUA/PUA.org")
 (front-context-string . "#+TITLE: Pick-Up")
 (rear-context-string)
 (position . 1))
("My Genetics Reference.org"
 (filename . "~/Org/Wiki/Biology/Genetics/Data/Manuals/My Genetics Reference/My Genetics Reference.org")
 (front-context-string . "#+TITLE: My Gene")
 (rear-context-string)
 (position . 1))
("Genetics.org"
 (filename . "~/Org/Wiki/Biology/Genetics/Genetics.org")
 (front-context-string . "#+TITLE: Genetic")
 (rear-context-string)
 (position . 1))
("Numerology.org"
 (filename . "~/Org/Wiki/Mysterious Culture/Numerology/Numerology.org")
 (front-context-string . "#+TITLE: Numerol")
 (rear-context-string)
 (position . 1))
("codox.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/codox.org")
 (front-context-string . "#+TITLE: codox\n\n")
 (rear-context-string)
 (position . 1))
("Jupyter.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Jupyter.org")
 (front-context-string . "#+TITLE: Jupyter")
 (rear-context-string)
 (position . 1))
("IPython.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Data/Python Packages/IPython/IPython.org")
 (front-context-string . "#+TITLE: IPython")
 (rear-context-string)
 (position . 1))
("History.org"
 (filename . "~/Org/Wiki/History/History.org")
 (front-context-string . "#+TITLE: History")
 (rear-context-string)
 (position . 1))
("Arduino.org"
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Dev Board/Arduino/Arduino.org")
 (front-context-string . "#+TITLE: Arduino")
 (rear-context-string)
 (position . 1))
("Raspberry Pi.org"
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Dev Board/Raspberry Pi/Raspberry Pi.org")
 (front-context-string . "#+TITLE: Raspber")
 (rear-context-string)
 (position . 1))
("Open Source Hardware.org"
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Open Source Hardware/Open Source Hardware.org")
 (front-context-string . "#+TITLE: Open So")
 (rear-context-string)
 (position . 1))
("Programming Mathematics.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Programming Mathematics/Programming Mathematics.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
("Thinking.org"
 (filename . "~/Org/Wiki/Self Enhancement/Thinking/Thinking.org")
 (front-context-string . "#+TITLE: Thinkin")
 (rear-context-string)
 (position . 1))
("Blockchain.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Blockchain/Blockchain.org")
 (front-context-string . "#+TITLE: Blockch")
 (rear-context-string)
 (position . 1))
("Civilization.org"
 (filename . "~/Org/Wiki/Civilization/Civilization.org")
 (front-context-string . "#+TITLE: Civiliz")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/incanter-xy-line.pdf"
 (filename . "~/incanter-xy-line.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("xargs.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/xargs.org")
 (front-context-string . "#+TITLE: xargs\n\n")
 (rear-context-string)
 (position . 1))
("Interpersonal Relationship.org"
 (filename . "~/Org/Wiki/Sociology/Social Intercourse/Interpersonal Relationship/Interpersonal Relationship.org")
 (front-context-string . "#+TITLE: Interpe")
 (rear-context-string)
 (position . 1))
("Unicode.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Unicode/Unicode.org")
 (front-context-string . "#+TITLE: Unicode")
 (rear-context-string)
 (position . 1))
("Apache Spark.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Apache Spark/Apache Spark.org")
 (front-context-string . "#+TITLE: Apache ")
 (rear-context-string)
 (position . 1))
("WeChat bot.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Communication/Projects/WeChat/WeChat bot/WeChat bot.org")
 (front-context-string . "#+TITLE: WeChat ")
 (rear-context-string)
 (position . 1))
("Hardware Programming.org"
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Hardware Programming/Hardware Programming.org")
 (front-context-string . "#+TITLE: Hardwar")
 (rear-context-string)
 (position . 1))
("Computer Architecture.org"
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Computer Architecture/Computer Architecture.org")
 (front-context-string . "#+TITLE: Compute")
 (rear-context-string)
 (position . 1))
("Hardware.org"
 (filename . "~/Org/Wiki/Computer Technology/Hardware/Hardware.org")
 (front-context-string . "#+TITLE: Hardwar")
 (rear-context-string)
 (position . 1))
("Culture.org"
 (filename . "~/Org/Wiki/Culture/Culture.org")
 (front-context-string . "#+TITLE: Culture")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Philosophy/Data/Books/中国哲学简史.pdf"
 (filename . "~/Org/Wiki/Philosophy/Data/Books/中国哲学简史.pdf")
 (position . 1)
 (page . 1)
 (slice 0 0 1 1)
 (size . fit-width)
 (origin 0.0 . 0.8402777777777778)
 (handler . pdf-view-bookmark-jump-handler))
("find.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/find.org")
 (front-context-string . "#+TITLE: find\n\n*")
 (rear-context-string)
 (position . 1))
("Graphviz.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Graphviz/Graphviz.org")
 (front-context-string . "#+TITLE: Graphvi")
 (rear-context-string)
 (position . 1))
("My RDF Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/RDF/Data/Manuals/My RDF Syntax Reference/My RDF Syntax Reference.org")
 (front-context-string . "#+TITLE: My RDF ")
 (rear-context-string)
 (position . 1))
("Systems Science.org"
 (filename . "~/Org/Wiki/Systems Science/Systems Science.org")
 (front-context-string . "#+TITLE: Systems")
 (rear-context-string)
 (position . 1))
("Communication Studies.org"
 (filename . "~/Org/Wiki/Communication Studies/Communication Studies.org")
 (front-context-string . "#+TITLE: Communi")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Algorithm/Data/Books/程序员的数学.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Algorithm/Data/Books/程序员的数学.pdf")
 (position . 1)
 (page . 88)
 (slice 0 0 1 1)
 (size . fit-width)
 (origin 0.0 . 0.45454545454545453)
 (handler . pdf-view-bookmark-jump-handler))
("API.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/API/API.org")
 (front-context-string . "#+TITLE: API\n\n* ")
 (rear-context-string)
 (position . 1))
("Network.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Network/Network.org")
 (front-context-string . "#+TITLE: Network")
 (rear-context-string)
 (position . 1))
("Cloud.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Cloud/Cloud.org")
 (front-context-string . "#+TITLE: Cloud\n\n")
 (rear-context-string)
 (position . 1))
("Mobile Development.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Mobile Development/Mobile Development.org")
 (front-context-string . "#+TITLE: Mobile ")
 (rear-context-string)
 (position . 1))
("Programmable Music.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Electric Music/Programmable Music/Programmable Music.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
("Electric Music.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Electric Music/Electric Music.org")
 (front-context-string . "#+TITLE: Electri")
 (rear-context-string)
 (position . 1))
("Natural Language Processing.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Natural Language Processing/Natural Language Processing.org")
 (front-context-string . "#+TITLE: Natural")
 (rear-context-string)
 (position . 1))
("Artificial Intelligence.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Artificial Intelligence/Artificial Intelligence.org")
 (front-context-string . "#+TITLE: Artific")
 (rear-context-string)
 (position . 1))
("GTK+.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/GUI/frameworks/GTK+/GTK+.org")
 (front-context-string . "#+TITLE: GTK+\n\n*")
 (rear-context-string)
 (position . 1))
("Qt.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/GUI/frameworks/Qt/Qt.org")
 (front-context-string . "#+TITLE: Qt\n\n* I")
 (rear-context-string)
 (position . 1))
("GUI.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/GUI/GUI.org")
 (front-context-string . "#+TITLE: GUI Imp")
 (rear-context-string)
 (position . 1))
("Data Science.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Data Science/Data Science.org")
 (front-context-string . "#+TITLE: Data Sc")
 (rear-context-string)
 (position . 1))
("Web.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Web/Web.org")
 (front-context-string . "#+TITLE: Web Imp")
 (rear-context-string)
 (position . 1))
("Implementations.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Implementations.org")
 (front-context-string . "#+TITLE: Impleme")
 (rear-context-string)
 (position . 1))
("GnuPG.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/GnuPG.org")
 (front-context-string . "#+TITLE: GnuPG\n\n")
 (rear-context-string)
 (position . 1))
("Markdown.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Markdown/Markdown.org")
 (front-context-string . "#+TITLE: Markdow")
 (rear-context-string)
 (position . 1))
("adb.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/adb.org")
 (front-context-string . "#+TITLE: ADB\n\n* ")
 (rear-context-string)
 (position . 1))
("ffmpeg.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/ffmpeg.org")
 (front-context-string . "#+TITLE: ffmpeg\n")
 (rear-context-string)
 (position . 1))
("Unit Testing.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Testing/Unit Testing/Unit Testing.org")
 (front-context-string . "#+TITLE: Unit Te")
 (rear-context-string)
 (position . 1))
("Behavior-Driven Development.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Testing/Behavior-Driven Development/Behavior-Driven Development.org")
 (front-context-string . "#+TITLE: Behavio")
 (rear-context-string)
 (position . 1))
("Test-Driven Development.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Testing/Test-Driven Development/Test-Driven Development.org")
 (front-context-string . "#+TITLE: Test-Dr")
 (rear-context-string)
 (position . 1))
("Testing.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Testing/Testing.org")
 (front-context-string . "#+TITLE: Testing")
 (rear-context-string)
 (position . 1))
("Program Design.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Program Design/Program Design.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
("Programming Glossary.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Data/Manuals/Programming Glossary/Programming Glossary.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
("ledger.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/ledger.org")
 (front-context-string . "#+TITLE: ledger\n")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Reading/Data/Manuals/My Reading Manual/Data/Docs/Read before you cite.pdf"
 (filename . "~/Org/Wiki/Reading/Data/Manuals/My Reading Manual/Data/Docs/Read before you cite.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Reading/Data/Manuals/My Reading Manual/Data/Docs/How to Read a Paper.pdf"
 (filename . "~/Org/Wiki/Reading/Data/Manuals/My Reading Manual/Data/Docs/How to Read a Paper.pdf")
 (position . 1)
 (page . 2)
 (slice 0.06323499999999999 0.046970000000000005 0.9013070000000001 0.885858)
 (size . fit-width)
 (origin 0.0 . 0.6073943661971831)
 (handler . pdf-view-bookmark-jump-handler))
("pdf-tools.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/pdf-tools.org")
 (front-context-string . "* Intro\n\n** Abou")
 (rear-context-string)
 (position . 1))
("Distributed Programming.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Programming Paradigms/Distributed Programming/Distributed Programming.org")
 (front-context-string . "#+TITLE: Distrib")
 (rear-context-string)
 (position . 1))
("My Reading Manual.org"
 (filename . "~/Org/Wiki/Reading/Data/Manuals/My Reading Manual/My Reading Manual.org")
 (front-context-string . "#+TITLE: My Read")
 (rear-context-string)
 (position . 1))
("gnuplot.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/gnuplot/gnuplot.org")
 (front-context-string . "#+TITLE: gnuplot")
 (rear-context-string)
 (position . 1))
("Overtone.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Overtone.org")
 (front-context-string . "#+TITLE: Overton")
 (rear-context-string)
 (position . 1))
("Investing and Financing.org"
 (filename . "~/Org/Wiki/Investing and Financing/Investing and Financing.org")
 (front-context-string . "#+TITLE: Investi")
 (rear-context-string)
 (position . 1))
("Metaphysics.org"
 (filename . "~/Org/Wiki/Philosophy/Metaphysics/Metaphysics.org")
 (front-context-string . "#+TITLE: Metaphy")
 (rear-context-string)
 (position . 1))
("Argumentation.org"
 (filename . "~/Org/Wiki/Reasoning Science/Logic/Argumentation/Argumentation.org")
 (front-context-string . "#+TITLE: Argumen")
 (rear-context-string)
 (position . 1))
("My Argumentation Manual.org"
 (filename . "~/Org/Wiki/Reasoning Science/Logic/Argumentation/Data/Manuals/My Argumentation Manual/My Argumentation Manual.org")
 (front-context-string . "#+TITLE: My Argu")
 (rear-context-string)
 (position . 1))
("Complexity.org"
 (filename . "~/Org/Wiki/Complexity/Complexity.org")
 (front-context-string . "#+TITLE: Complex")
 (rear-context-string)
 (position . 1))
("Gorilla REPL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Gorilla REPL.org")
 (front-context-string . "#+TITLE: Gorilla")
 (rear-context-string)
 (position . 1))
("Boy's Love.org"
 (filename . "~/Org/Wiki/LGBTQ/Boy's Love/Boy's Love.org")
 (front-context-string . "#+TITLE: Boy's L")
 (rear-context-string)
 (position . 1))
("Make Love.org"
 (filename . "~/Org/Wiki/Love/Make Love/Make Love.org")
 (front-context-string . "#+TITLE: Make Lo")
 (rear-context-string)
 (position . 1))
("Photograph.org"
 (filename . "~/Org/Wiki/Photograph/Photograph.org")
 (front-context-string . "#+TITLE: Photogr")
 (rear-context-string)
 (position . 1))
("Theology.org"
 (filename . "~/Org/Wiki/Religion/Theology/Theology.org")
 (front-context-string . "#+TITLE: Theolog")
 (rear-context-string)
 (position . 1))
("Religion.org"
 (filename . "~/Org/Wiki/Religion/Religion.org")
 (front-context-string . "#+TITLE: Religio")
 (rear-context-string)
 (position . 1))
("Logic.org"
 (filename . "~/Org/Wiki/Reasoning Science/Logic/Logic.org")
 (front-context-string . "#+TITLE: Logic\n\n")
 (rear-context-string)
 (position . 1))
("Reasoning Science.org"
 (filename . "~/Org/Wiki/Reasoning Science/Reasoning Science.org")
 (front-context-string . "#+TITLE: Reasoni")
 (rear-context-string)
 (position . 1))
("Trade.org"
 (filename . "~/Org/Wiki/Economy/Trade/Trade.org")
 (front-context-string . "#+TITLE: Trade\n\n")
 (rear-context-string)
 (position . 1))
("Indium.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/Indium.org")
 (front-context-string . "#+TITLE: Indium\n")
 (rear-context-string)
 (position . 1))
("ssh.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/ssh.org")
 (front-context-string . "#+TITLE: SSH\n\n* ")
 (rear-context-string)
 (position . 1))
("Linux Distributions.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Distributions/Linux Distributions.org")
 (front-context-string . "#+TITLE: Linux D")
 (rear-context-string)
 (position . 1))
("Workplace.org"
 (filename . "~/Org/Wiki/Work/Workplace/Workplace.org")
 (front-context-string . "#+TITLE: Workpla")
 (rear-context-string)
 (position . 1))
("Work.org"
 (filename . "~/Org/Wiki/Work/Work.org")
 (front-context-string . "#+TITLE: Work\n\n*")
 (rear-context-string)
 (position . 1))
("Influence.org"
 (filename . "~/Org/Wiki/Self Enhancement/Leadership/Influence/Influence.org")
 (front-context-string . "#+TITLE: Influen")
 (rear-context-string)
 (position . 1))
("DevOps.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/DevOps/DevOps.org")
 (front-context-string . "#+TITLE: DevOps\n")
 (rear-context-string)
 (position . 1))
("People Management.org"
 (filename . "~/Org/Wiki/Commercial Science/Management/People Management/People Management.org")
 (front-context-string . "#+TITLE: People ")
 (rear-context-string)
 (position . 1))
("Willpower.org"
 (filename . "~/Org/Wiki/Self Enhancement/Willpower/Willpower.org")
 (front-context-string . "#+TITLE: Willpow")
 (rear-context-string)
 (position . 1))
("Female.org"
 (filename . "~/Org/Wiki/Sociology/Male and Female/Female/Female.org")
 (front-context-string . "#+TITLE: Female\n")
 (rear-context-string)
 (position . 1))
("Male.org"
 (filename . "~/Org/Wiki/Sociology/Male and Female/Male/Male.org")
 (front-context-string . "#+TITLE: Male\n\n*")
 (rear-context-string)
 (position . 1))
("Male and Female.org"
 (filename . "~/Org/Wiki/Sociology/Male and Female/Male and Female.org")
 (front-context-string . "#+TITLE: Male an")
 (rear-context-string)
 (position . 1))
("Sociology.org"
 (filename . "~/Org/Wiki/Sociology/Sociology.org")
 (front-context-string . "#+TITLE: Sociolo")
 (rear-context-string)
 (position . 1))
("Knowledge Management.org"
 (filename . "~/Org/Wiki/Self Enhancement/Knowledge Management/Knowledge Management.org")
 (front-context-string . "#+TITLE: Knowled")
 (rear-context-string)
 (position . 1))
("Reading.org"
 (filename . "~/Org/Wiki/Reading/Reading.org")
 (front-context-string . "#+TITLE: Reading")
 (rear-context-string)
 (position . 1))
("Management.org"
 (filename . "~/Org/Wiki/Commercial Science/Management/Management.org")
 (front-context-string . "#+TITLE: Managem")
 (rear-context-string)
 (position . 1))
("Self Marketing.org"
 (filename . "~/Org/Wiki/Self Enhancement/Self Marketing/Self Marketing.org")
 (front-context-string . "#+TITLE: Self Ma")
 (rear-context-string)
 (position . 1))
("Personal Life.org"
 (filename . "~/Org/Wiki/Self Enhancement/Personal Life/Personal Life.org")
 (front-context-string . "#+TITLE: Persona")
 (rear-context-string)
 (position . 1))
("Time Management.org"
 (filename . "~/Org/Wiki/Self Enhancement/Time Management/Time Management.org")
 (front-context-string . "#+TITLE: Time Ma")
 (rear-context-string)
 (position . 1))
("Leadership.org"
 (filename . "~/Org/Wiki/Self Enhancement/Leadership/Leadership.org")
 (front-context-string . "#+TITLE: Leaders")
 (rear-context-string)
 (position . 1))
("My Problem Solving Manual.org"
 (filename . "~/Org/Wiki/Thinking/Data/Manuals/My Problem Solving Manual/My Problem Solving Manual.org")
 (front-context-string . "#+TITLE: My Prob")
 (rear-context-string)
 (position . 1))
("Matrix.org"
 (filename . "~/Org/Wiki/Mathematics/Algebra/Linear Algebra/Matrix/Matrix.org")
 (front-context-string . "#+TITLE: Matrix\n")
 (rear-context-string)
 (position . 1))
("My Mathematics Manual.org"
 (filename . "~/Org/Wiki/Mathematics/Data/Manuals/My Mathematics Manual/My Mathematics Manual.org")
 (front-context-string . "#+TITLE: My Math")
 (rear-context-string)
 (position . 1))
("My Algorithm Manual.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Algorithm/Data/Manuals/My Algorithm Manual/My Algorithm Manual.org")
 (front-context-string . "#+TITLE: My Algo")
 (rear-context-string)
 (position . 1))
("Algorithm Complexity.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Algorithm/Data/Manuals/Algorithm Complexity/Algorithm Complexity.org")
 (front-context-string . "#+TITLE: Algorit")
 (rear-context-string)
 (position . 1))
("Mind Growth.org"
 (filename . "~/Org/Wiki/Self Enhancement/Mind Growth/Mind Growth.org")
 (front-context-string . "#+TITLE: Mind Gr")
 (rear-context-string)
 (position . 1))
("Sinology.org"
 (filename . "~/Org/Wiki/Culture/Countries Culture/China Culture/Sinology/Sinology.org")
 (front-context-string . "#+TITLE: Sinolog")
 (rear-context-string)
 (position . 1))
("Negotiate.org"
 (filename . "~/Org/Wiki/Self Enhancement/Communication/Negotiate/Negotiate.org")
 (front-context-string . "#+TITLE: Negotia")
 (rear-context-string)
 (position . 1))
("Boot.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Boot.org")
 (front-context-string . "#+TITLE: Boot\n\n*")
 (rear-context-string)
 (position . 1))
("Leiningen.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Leiningen.org")
 (front-context-string . "#+TITLE: Leining")
 (rear-context-string)
 (position . 1))
("Life Science.org"
 (filename . "~/Org/Wiki/Life Science/Life Science.org")
 (front-context-string . "#+TITLE: Life Sc")
 (rear-context-string)
 (position . 1))
("Life.org"
 (filename . "~/Org/Wiki/Life/Life.org")
 (front-context-string . "#+TITLE: Life\n\n*")
 (rear-context-string)
 (position . 1))
("Science.org"
 (filename . "~/Org/Wiki/Science/Science.org")
 (front-context-string . "#+TITLE: Science")
 (rear-context-string)
 (position . 1))
("Astronomy.org"
 (filename . "~/Org/Wiki/Astronomy/Astronomy.org")
 (front-context-string . "#+TITLE: Astrono")
 (rear-context-string)
 (position . 1))
("ClojureScript Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/Data/ClojureScript Packages/ClojureScript Packages.org")
 (front-context-string . "#+TITLE: Clojure")
 (rear-context-string)
 (position . 1))
("Electricity.org"
 (filename . "~/Org/Wiki/Physics/Electricity/Electricity.org")
 (front-context-string . "#+TITLE: Electri")
 (rear-context-string)
 (position . 1))
("Mechanics.org"
 (filename . "~/Org/Wiki/Physics/Mechanics/Mechanics.org")
 (front-context-string . "#+TITLE: Mechani")
 (rear-context-string)
 (position . 1))
("Quantum Theory.org"
 (filename . "~/Org/Wiki/Physics/Quantum Theory/Quantum Theory.org")
 (front-context-string . "#+TITLE: Quantum")
 (rear-context-string)
 (position . 1))
("Consciousness.org"
 (filename . "~/Org/Wiki/Brain Science/Consciousness/Consciousness.org")
 (front-context-string . "#+TITLE: Conscio")
 (rear-context-string)
 (position . 1))
("Brain Science.org"
 (filename . "~/Org/Wiki/Brain Science/Brain Science.org")
 (front-context-string . "#+TITLE: Brain S")
 (rear-context-string)
 (position . 1))
("Dired.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/Dired/Dired.org")
 (front-context-string . "#+TITLE: Dired\n\n")
 (rear-context-string)
 (position . 1))
("Cosmology.org"
 (filename . "~/Org/Wiki/Physics/Cosmology/Cosmology.org")
 (front-context-string . "#+TITLE: Cosmolo")
 (rear-context-string)
 (position . 1))
("Philosophy.org"
 (filename . "~/Org/Wiki/Philosophy/Philosophy.org")
 (front-context-string . "#+TITLE: Philoso")
 (rear-context-string)
 (position . 1))
("心学.org"
 (filename . "~/Org/Wiki/Thought/诸子百家/儒家/心学/心学.org")
 (front-context-string . "#+TITLE: 心学\n\n* I")
 (rear-context-string)
 (position . 1))
("儒家.org"
 (filename . "~/Org/Wiki/Thought/诸子百家/儒家/儒家.org")
 (front-context-string . "#+TITLE: 儒家\n\n* I")
 (rear-context-string)
 (position . 1))
("My OpenGL Manual.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/OpenGL/Data/Manuals/My OpenGL Manual/My OpenGL Manual.org")
 (front-context-string . "#+TITLE: My Open")
 (rear-context-string)
 (position . 1))
("OpenGL.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/OpenGL/OpenGL.org")
 (front-context-string . "#+TITLE: OpenGL\n")
 (rear-context-string)
 (position . 1))
("KDE.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/KDE/KDE.org")
 (front-context-string . "#+TITLE: KDE\n\n* ")
 (rear-context-string)
 (position . 1))
("My Lua Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lua/Data/Manuals/My Lua Language Syntax Reference/My Lua Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Lua ")
 (rear-context-string)
 (position . 1))
("Software Development Method.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Software Development/Software Development Method/Software Development Method.org")
 (front-context-string . "#+TITLE: Softwar")
 (rear-context-string)
 (position . 1))
("Software Development.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Software Development/Software Development.org")
 (front-context-string . "#+TITLE: Softwar")
 (rear-context-string)
 (position . 1))
("Microsoft Windows Kernel.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Microsoft Windows/Microsoft Windows Kernel/Microsoft Windows Kernel.org")
 (front-context-string . "#+TITLE: Microso")
 (rear-context-string)
 (position . 1))
("BSD Kernel.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/BSD/BSD Kernel/BSD Kernel.org")
 (front-context-string . "#+TITLE: BSD Ker")
 (rear-context-string)
 (position . 1))
("Linux Kernel.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux Kernel/Linux Kernel.org")
 (front-context-string . "#+TITLE: Linux K")
 (rear-context-string)
 (position . 1))
("Kernels.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Kernels/Kernels.org")
 (front-context-string . "#+TITLE: Kernels")
 (rear-context-string)
 (position . 1))
("OpenWrt.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/OpenWrt/OpenWrt.org")
 (front-context-string . "#+TITLE: OpenWrt")
 (rear-context-string)
 (position . 1))
("iOS.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/iOS/iOS.org")
 (front-context-string . "#+TITLE: iOS\n\n* ")
 (rear-context-string)
 (position . 1))
("Android.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Android/Android.org")
 (front-context-string . "#+TITLE: Android")
 (rear-context-string)
 (position . 1))
("Microsoft Windows.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Microsoft Windows/Microsoft Windows.org")
 (front-context-string . "#+TITLE: Microso")
 (rear-context-string)
 (position . 1))
("GNU.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/GNU/GNU.org")
 (front-context-string . "#+TITLE: GNU Ope")
 (rear-context-string)
 (position . 1))
("macOS.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/macOS/macOS.org")
 (front-context-string . "#+TITLE: macOS\n\n")
 (rear-context-string)
 (position . 1))
("BSD.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/BSD/BSD.org")
 (front-context-string . "#+TITLE: BSD\n\n* ")
 (rear-context-string)
 (position . 1))
("Linux.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Linux/Linux.org")
 (front-context-string . "#+TITLE: GNU/Lin")
 (rear-context-string)
 (position . 1))
("UNIX.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/UNIX/UNIX.org")
 (front-context-string . "#+TITLE: UNIX\n\n*")
 (rear-context-string)
 (position . 1))
("Lisp Machines.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Lisp Machines/Lisp Machines.org")
 (front-context-string . "#+TITLE: Lisp Ma")
 (rear-context-string)
 (position . 1))
("Operating System.org"
 (filename . "~/Org/Wiki/Computer Technology/Operating System/Operating System.org")
 (front-context-string . "#+TITLE: Operati")
 (rear-context-string)
 (position . 1))
("Magit.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/Magit/Magit.org")
 (front-context-string . "#+TITLE: Magit\n\n")
 (rear-context-string)
 (position . 1))
("ERC.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/ERC.org")
 (front-context-string . "#+TITLE: ERC\n\n* ")
 (rear-context-string)
 (position . 1))
("Apache Hadoop.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Apache Hadoop/Apache Hadoop.org")
 (front-context-string . "#+TITLE: Apache ")
 (rear-context-string)
 (position . 1))
("Debug.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Debug/Debug.org")
 (front-context-string . "#+TITLE: Debug\n\n")
 (rear-context-string)
 (position . 1))
("youtube-dl.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/youtube-dl.org")
 (front-context-string . "#+TITLE: youtube")
 (rear-context-string)
 (position . 1))
("China Law Database.org"
 (filename . "~/Org/Wiki/Law/Data/Law Databases/China Law Database/China Law Database.org")
 (front-context-string . "#+TITLE: China L")
 (rear-context-string)
 (position . 1))
("org-ref.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/org-ref.org")
 (front-context-string . "* Intro\n\ncitatio")
 (rear-context-string)
 (position . 1))
("Buddhism.org"
 (filename . "~/Org/Wiki/Religion/Buddhism/Buddhism.org")
 (front-context-string . "#+TITLE: Buddhis")
 (rear-context-string)
 (position . 1))
("Chestnut.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Chestnut.org")
 (front-context-string . "#+TITLE: Chestnu")
 (rear-context-string)
 (position . 1))
("Incanter.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Incanter.org")
 (front-context-string . "#+TITLE: Incante")
 (rear-context-string)
 (position . 1))
("Accost.org"
 (filename . "~/Org/Wiki/Love/Accost/Accost.org")
 (front-context-string . "#+TITLE: Accost\n")
 (rear-context-string)
 (position . 1))
("IRC.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/IRC/IRC.org")
 (front-context-string . "#+TITLE: IRC\n\n* ")
 (rear-context-string)
 (position . 1))
("Language Server Protocol.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Coding IDE/Code IDE Technologies/Language Server Protocol/Language Server Protocol.org")
 (front-context-string . "#+TITLE: Languag")
 (rear-context-string)
 (position . 1))
("Scala Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Scala/Data/Scala Packages/Scala Packages.org")
 (front-context-string . "#+TITLE: Scala P")
 (rear-context-string)
 (position . 1))
("Datalog.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Datalog/Datalog.org")
 (front-context-string . "#+TITLE: Datalog")
 (rear-context-string)
 (position . 1))
("SuperCollider.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/SuperCollider/SuperCollider.org")
 (front-context-string . "#+TITLE: SuperCo")
 (rear-context-string)
 (position . 1))
("JavaScript Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/JavaScript Packages/JavaScript Packages.org")
 (front-context-string . "#+TITLE: JavaScr")
 (rear-context-string)
 (position . 1))
("Processing.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Processing/Processing.org")
 (front-context-string . "#+TITLE: Process")
 (rear-context-string)
 (position . 1))
("Octave Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Octave/Data/Octave Packages/Octave Packages.org")
 (front-context-string . "#+TITLE: Octave ")
 (rear-context-string)
 (position . 1))
("Octave.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Octave/Octave.org")
 (front-context-string . "#+TITLE: Octave ")
 (rear-context-string)
 (position . 1))
("Matlab Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Matlab/Data/Matlab Packages/Matlab Packages.org")
 (front-context-string . "#+TITLE: Matlab ")
 (rear-context-string)
 (position . 1))
("My Matlab Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Matlab/Data/Manuals/My Matlab Language Syntax Reference/My Matlab Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Matl")
 (rear-context-string)
 (position . 1))
("Matlab.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Matlab/Matlab.org")
 (front-context-string . "#+TITLE: Matlab ")
 (rear-context-string)
 (position . 1))
("Julia Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Julia/Data/Julia Packages/Julia Packages.org")
 (front-context-string . "#+TITLE: Julia P")
 (rear-context-string)
 (position . 1))
("XPath.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/XPath/XPath.org")
 (front-context-string . "#+TITLE: XPath\n\n")
 (rear-context-string)
 (position . 1))
("JSON.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JSON/JSON.org")
 (front-context-string . "#+TITLE: JSON\n\n*")
 (rear-context-string)
 (position . 1))
("XML.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/XML/XML.org")
 (front-context-string . "#+TITLE: XML\n\n* ")
 (rear-context-string)
 (position . 1))
("GraphQL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/GraphQL/GraphQL.org")
 (front-context-string . "#+TITLE: GraphQL")
 (rear-context-string)
 (position . 1))
("CQL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/CQL/CQL.org")
 (front-context-string . "#+TITLE: CQL\n\n* ")
 (rear-context-string)
 (position . 1))
("NewSQL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/NewSQL/NewSQL.org")
 (front-context-string . "#+TITLE: NewSQL\n")
 (rear-context-string)
 (position . 1))
("Kotlin Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Kotlin/Data/Kotlin Packages/Kotlin Packages.org")
 (front-context-string . "#+TITLE: Kotlin ")
 (rear-context-string)
 (position . 1))
("Java Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Java/Data/Java Packages/Java Packages.org")
 (front-context-string . "#+TITLE: Java Pa")
 (rear-context-string)
 (position . 1))
("Lua Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lua/Data/Lua Packages/Lua Packages.org")
 (front-context-string . "#+TITLE: Lua Pac")
 (rear-context-string)
 (position . 1))
("C# Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C#/Data/C# Packages/C# Packages.org")
 (front-context-string . "#+TITLE: C# Pack")
 (rear-context-string)
 (position . 1))
("Swift Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Swift/Data/Swift Packages/Swift Packages.org")
 (front-context-string . "#+TITLE: Swift P")
 (rear-context-string)
 (position . 1))
("Rust Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Rust/Data/Rust Packages/Rust Packages.org")
 (front-context-string . "#+TITLE: Rust Pa")
 (rear-context-string)
 (position . 1))
("Go Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Go/Data/Go Packages/Go Packages.org")
 (front-context-string . "#+TITLE: Go Pack")
 (rear-context-string)
 (position . 1))
("PHP Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/PHP/Data/PHP Packages/PHP Packages.org")
 (front-context-string . "#+TITLE: PHP Pac")
 (rear-context-string)
 (position . 1))
("Perl.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Perl/Perl.org")
 (front-context-string . "#+TITLE: Perl Pr")
 (rear-context-string)
 (position . 1))
("Haskell Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Haskell/Data/Haskell Packages/Haskell Packages.org")
 (front-context-string . "#+TITLE: Haskell")
 (rear-context-string)
 (position . 1))
("Smalltalk.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Smalltalk/Smalltalk.org")
 (front-context-string . "Smalltalk Progra")
 (rear-context-string)
 (position . 10))
("Common Lisp Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Common Lisp/Data/Common Lisp Packages/Common Lisp Packages.org")
 (front-context-string . "#+TITLE: Common ")
 (rear-context-string)
 (position . 1))
("C++ Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C++/Data/C++ Packages/C++ Packages.org")
 (front-context-string . "#+TITLE: C++ Pac")
 (rear-context-string)
 (position . 1))
("Python Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Data/Python Packages/Python Packages.org")
 (front-context-string . "#+TITLE: Python ")
 (rear-context-string)
 (position . 1))
("Ruby Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Ruby/Data/Ruby Packages/Ruby Packages.org")
 (front-context-string . "#+TITLE: Ruby Pa")
 (rear-context-string)
 (position . 1))
("Clojure Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Clojure Packages/Clojure Packages.org")
 (front-context-string . "#+TITLE: Clojure")
 (rear-context-string)
 (position . 1))
("My Wolfram Language Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Wolfram/Data/Manuals/My Wolfram Language Examples/My Wolfram Language Examples.org")
 (front-context-string . "#+TITLE: My Wolf")
 (rear-context-string)
 (position . 1))
("My Wolfram Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Wolfram/Data/Manuals/My Wolfram Language Syntax Reference/My Wolfram Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Wolf")
 (rear-context-string)
 (position . 1))
("Wolfram.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Wolfram/Wolfram.org")
 (front-context-string . "#+TITLE: Wolfram")
 (rear-context-string)
 (position . 1))
("mu4e.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/mu4e.org")
 (front-context-string . "* Intro\n\nStartin")
 (rear-context-string)
 (position . 1))
("Regular Expressions.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Regular Expressions/Regular Expressions.org")
 (front-context-string . "#+TITLE: Regular")
 (rear-context-string)
 (position . 1))
("My Docker Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Docker/Data/Manuals/My Docker Reference/My Docker Reference.org")
 (front-context-string . "#+TITLE: My Dock")
 (rear-context-string)
 (position . 1))
("Social Intercourse.org"
 (filename . "~/Org/Wiki/Sociology/Social Intercourse/Social Intercourse.org")
 (front-context-string . "#+TITLE: Social ")
 (rear-context-string)
 (position . 1))
("paredit.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/paredit.org")
 (front-context-string . "#+TITLE: paredit")
 (rear-context-string)
 (position . 1))
("pacman.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/pacman.org")
 (front-context-string . "#+TITLE: pacman ")
 (rear-context-string)
 (position . 1))
("My Evil Hack Manual.org"
 (filename . "~/Org/Wiki/Computer Technology/Hack/Data/Manuals/My Evil Hack Manual/My Evil Hack Manual.org")
 (front-context-string . "#+TITLE: My Evil")
 (rear-context-string)
 (position . 1))
("PowerShell.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/PowerShell/PowerShell.org")
 (front-context-string . "#+TITLE: PowerSh")
 (rear-context-string)
 (position . 1))
("Anime.org"
 (filename . "~/Org/Wiki/ACG/Anime/Anime.org")
 (front-context-string . "#+TITLE: Anime\n\n")
 (rear-context-string)
 (position . 1))
("ACG.org"
 (filename . "~/Org/Wiki/ACG/ACG.org")
 (front-context-string . "#+TITLE: ACG\n\n* ")
 (rear-context-string)
 (position . 1))
("systemd.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/systemd/systemd.org")
 (front-context-string . "#+TITLE: systemd")
 (rear-context-string)
 (position . 1))
("Novel Books.org"
 (filename . "~/Org/Wiki/Literature/Novels/Data/Novel Books/Novel Books.org")
 (front-context-string . "#+TITLE: Novel B")
 (rear-context-string)
 (position . 1))
("Communication.org"
 (filename . "~/Org/Wiki/Self Enhancement/Communication/Communication.org")
 (front-context-string . "#+TITLE: Communi")
 (rear-context-string)
 (position . 1))
("Self Enhancement.org"
 (filename . "~/Org/Wiki/Self Enhancement/Self Enhancement.org")
 (front-context-string . "#+TITLE: Self En")
 (rear-context-string)
 (position . 1))
("My Thought Manuals.org"
 (filename . "~/Org/Wiki/Thought/Data/Manuals/My Thought Manuals/My Thought Manuals.org")
 (front-context-string . "#+TITLE: My Thou")
 (rear-context-string)
 (position . 1))
("Operations Research.org"
 (filename . "~/Org/Wiki/Mathematics/Applied Mathematics/Operations Research/Operations Research.org")
 (front-context-string . "#+TITLE: Operati")
 (rear-context-string)
 (position . 1))
("Atom.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Atom/Atom.org")
 (front-context-string . "* Intro\n\nThe Hac")
 (rear-context-string)
 (position . 1))
("My Rust Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Rust/Data/Manuals/My Rust Language Syntax Reference/My Rust Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Rust")
 (rear-context-string)
 (position . 1))
("My Rust Library Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Rust/Data/Manuals/My Rust Library Examples/My Rust Library Examples.org")
 (front-context-string . "#+TITLE: My Rust")
 (rear-context-string)
 (position . 1))
("My Rust Language Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Rust/Data/Manuals/My Rust Language Examples/My Rust Language Examples.org")
 (front-context-string . "#+TITLE: My Rust")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Code/learning/TeX/test.pdf"
 (filename . "~/Code/learning/TeX/test.pdf")
 (position . 1)
 (page . 2)
 (slice 0.19395400000000002 0.132828 0.358824 0.7797980000000001)
 (size . fit-width)
 (origin 0.0 . 0.048283261802575105)
 (handler . pdf-view-bookmark-jump-handler))
("My Ruby Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Ruby/Data/Manuals/My Ruby Examples/My Ruby Examples.org")
 (front-context-string . "#+TITLE: My Ruby")
 (rear-context-string)
 (position . 1))
("My Ruby Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Ruby/Data/Manuals/My Ruby Language Syntax Reference/My Ruby Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Ruby")
 (rear-context-string)
 (position . 1))
("Kotlin.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Kotlin/Kotlin.org")
 (front-context-string . "#+TITLE: Kotlin ")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Packages/Data/Docs/incanter-charts-custom.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Packages/Data/Docs/incanter-charts-custom.pdf")
 (position . 1)
 (page . 1)
 (slice)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("Porn Novel Books.org"
 (filename . "~/Org/Wiki/Pornography/Porn/Porn Novels/Data/Porn Novel Books/Porn Novel Books.org")
 (front-context-string . "#+TITLE: Porn No")
 (rear-context-string)
 (position . 1))
("Sex Knowledge.org"
 (filename . "~/Org/Wiki/Sexology/Sexual Intercourse/Sex Knowledge/Sex Knowledge.org")
 (front-context-string . "#+TITLE: Sex Kno")
 (rear-context-string)
 (position . 1))
("Sexual Intercourse.org"
 (filename . "~/Org/Wiki/Sexology/Sexual Intercourse/Sexual Intercourse.org")
 (front-context-string . "#+TITLE: Sexual ")
 (rear-context-string)
 (position . 1))
("Sex Toys.org"
 (filename . "~/Org/Wiki/Sexology/Masturbation/Sex Toys/Sex Toys.org")
 (front-context-string . "#+TITLE: Sex Toy")
 (rear-context-string)
 (position . 1))
("Statistics.org"
 (filename . "~/Org/Wiki/Mathematics/Statistics/Statistics.org")
 (front-context-string . "#+TITLE: Statist")
 (rear-context-string)
 (position . 1))
("Internet Marketing.org"
 (filename . "~/Org/Wiki/Commercial Science/Marketing/Internet Marketing/Internet Marketing.org")
 (front-context-string . "#+TITLE: Interne")
 (rear-context-string)
 (position . 1))
("Creativity.org"
 (filename . "~/Org/Wiki/Thinking/Creativity/Creativity.org")
 (front-context-string . "#+TITLE: Creativ")
 (rear-context-string)
 (position . 1))
("World History.org"
 (filename . "~/Org/Wiki/History/Country's History/World History/World History.org")
 (front-context-string . "#+TITLE: World H")
 (rear-context-string)
 (position . 1))
("Politics.org"
 (filename . "~/Org/Wiki/Politics/Politics.org")
 (front-context-string . "#+TITLE: Politic")
 (rear-context-string)
 (position . 1))
("Conky.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Conky/Conky.org")
 (front-context-string . "* Intro\n\n\n** Fea")
 (rear-context-string)
 (position . 1))
("Functional Programming.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Programming Paradigms/Functional Programming/Functional Programming.org")
 (front-context-string . "#+TITLE: Functio")
 (rear-context-string)
 (position . 1))
("Object-Oriented Programming.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Programming Paradigms/Object-Oriented Programming/Object-Oriented Programming.org")
 (front-context-string . "#+TITLE: Object-")
 (rear-context-string)
 (position . 1))
("Literate Programming.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Programming Paradigms/Literate Programming/Literate Programming.org")
 (front-context-string . "#+TITLE: Literat")
 (rear-context-string)
 (position . 1))
("Programming Paradigms.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Coding/Programming Paradigms/Programming Paradigms.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Code/learning/Emacs/Org-mode/landscape-view.pdf"
 (filename . "~/Code/learning/Emacs/Org-mode/landscape-view.pdf")
 (position . 1)
 (page . 2)
 (slice 0.092424 0.187418 0.13080799999999998 0.339216)
 (size . fit-width)
 (origin 0.0 . 0.4562798092209857)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Softwares/data/docs/Tmux: Productive Mouse-Free Development.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/data/docs/Tmux: Productive Mouse-Free Development.pdf")
 (position . 1)
 (page . 60)
 (slice 0 0.019753 1 1)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Softwares/data/8f/21e898-cc7f-4454-a1cc-b7f30c053280/ledger-mode.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/data/8f/21e898-cc7f-4454-a1cc-b7f30c053280/ledger-mode.pdf")
 (position . 1)
 (page . 3)
 (slice 0.122059 0.038131000000000005 0.7558819999999999 0.890909)
 (size . fit-width)
 (origin 0.0 . 0.0)
 (handler . pdf-view-bookmark-jump-handler))
("use-package.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/use-package.org")
 (front-context-string . "* Intro\n\nA use-p")
 (rear-context-string)
 (position . 1))
("Library of Babel.org"
 (filename . "~/.emacs.d/Org-mode/Library of Babel/Library of Babel.org")
 (front-context-string . "#+TITLE: Library")
 (rear-context-string)
 (position . 1))
("Erlang.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Erlang/Erlang.org")
 (front-context-string . "#+TITLE: Erlang ")
 (rear-context-string)
 (position . 1))
("My Sex Positions Reference.org"
 (filename . "~/Org/Wiki/Sexology/Sexual Intercourse/Sex Positions/Data/Manuals/My Sex Positions Reference/My Sex Positions Reference.org")
 (front-context-string . "#+TITLE: My Sex ")
 (rear-context-string)
 (position . 1))
("LGBTQ.org"
 (filename . "~/Org/Wiki/LGBTQ/LGBTQ.org")
 (front-context-string . "#+TITLE: LGBTQ\n\n")
 (rear-context-string)
 (position . 1))
("Spiritual.org"
 (filename . "~/Org/Wiki/Spiritual/Spiritual.org")
 (front-context-string . "* Intro\n\n** \"灵修\"")
 (rear-context-string)
 (position . 1))
("Design.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Implementations/Design/Design.org")
 (front-context-string . "#+TITLE: Design\n")
 (rear-context-string)
 (position . 1))
("Digital Design.org"
 (filename . "~/Org/Wiki/Computer Technology/Digital Design/Digital Design.org")
 (front-context-string . "* Intro\n\n** Desi")
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Softwares/Data/Books/Slack Hacks, Early Release.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Data/Books/Slack Hacks, Early Release.pdf")
 (position . 1)
 (page . 5)
 (slice)
 (size . fit-width)
 (origin)
 (handler . pdf-view-bookmark-jump-handler))
("Alda.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Alda/Alda.org")
 (front-context-string . "* Intro\n\n#+BEGIN")
 (rear-context-string)
 (position . 1))
("侠.org"
 (filename . "~/Org/Wiki/Kung Fu/侠/侠.org")
 (front-context-string)
 (rear-context-string)
 (position . 1))
("PDF-LAST-VIEWED: /home/stardiviner/Org/Wiki/Computer Technology/Programming/Emacs/Data/Books/GNU Emacs Manual.pdf"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Books/GNU Emacs Manual.pdf")
 (position . 1)
 (page . 4)
 (slice 0.122059 0.477525 0.7558819999999999 0.44898999999999994)
 (size . fit-width)
 (origin 0.0 . 0.5511811023622047)
 (handler . pdf-view-bookmark-jump-handler))
("Vagrant.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Vagrant/Vagrant.org")
 (front-context-string . "* Intro\n\nVagrant")
 (rear-context-string)
 (position . 1))
("Japanese.org"
 (filename . "~/Org/Wiki/Linguistics/Japanese/Japanese.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
("English.org"
 (filename . "~/Org/Wiki/Linguistics/English/English.org")
 (front-context-string . "* Intro\n\n\n** Eng")
 (rear-context-string)
 (position . 1))
("Chinese.org"
 (filename . "~/Org/Wiki/Linguistics/Chinese/Chinese.org")
 (front-context-string . "* Intro\n\n\n** Chi")
 (rear-context-string)
 (position . 1))
("Linguistics.org"
 (filename . "~/Org/Wiki/Linguistics/Linguistics.org")
 (front-context-string . "#+TITLE: Linguis")
 (rear-context-string)
 (position . 1))
("Oracle SQL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/Oracle SQL/Oracle SQL.org")
 (front-context-string . "* Intro\n\n** Abou")
 (rear-context-string)
 (position . 1))
("Daoism 道家"
 (filename . "~/Org/Wiki/Thought/诸子百家/道家/道家.org")
 (front-context-string . "#+TITLE: 道家 Daoi")
 (rear-context-string)
 (position . 1))
("诸子百家.org"
 (filename . "~/Org/Wiki/Thought/诸子百家/诸子百家.org")
 (front-context-string . "* Intro\n\n** 沿革\n\n")
 (rear-context-string)
 (position . 1))
("My Emacs Lisp Regexp Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs Lisp/Data/Manuals/My Emacs Lisp Regexp Reference.org")
 (front-context-string . "\n\n* Demo\n\n** mat")
 (rear-context-string . "Regexp Reference")
 (position . 40))
("My Emacs Lisp Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs Lisp/Data/Manuals/My Emacs Lisp Examples/My Emacs Lisp Examples.org")
 (front-context-string . "\n\n* Command\n\n** ")
 (rear-context-string . "cs Lisp Examples")
 (position . 32))
("My Emacs Lisp Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs Lisp/Data/Manuals/My Emacs Lisp Syntax Reference/My Emacs Lisp Syntax Reference.org")
 (front-context-string . "#+TITLE: My Emac")
 (rear-context-string)
 (position . 1))
("Redis.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/NoSQL/Redis/Redis.org")
 (front-context-string . "* Intro\n\nRedis i")
 (rear-context-string)
 (position . 1))
("MongoDB.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/NoSQL/MongoDB/MongoDB.org")
 (front-context-string . "* Intro\n\nA high-")
 (rear-context-string)
 (position . 1))
("Zsh.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/Zsh/Zsh.org")
 (front-context-string . "* Intro\n\n\n\n** Fe")
 (rear-context-string)
 (position . 1))
("Git.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Git/Git.org")
 (front-context-string . "#+TITLE: Git\n\n* ")
 (rear-context-string)
 (position . 1))
("Assembly.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Assembly/Assembly.org")
 (front-context-string . "#+TITLE: Assembl")
 (rear-context-string)
 (position . 1))
("PHP.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/PHP/PHP.org")
 (front-context-string . "#+TITLE: PHP Pro")
 (rear-context-string)
 (position . 1))
("Physics.org"
 (filename . "~/Org/Wiki/Physics/Physics.org")
 (front-context-string . "#+TITLE: Physics")
 (rear-context-string)
 (position . 1))
("My Git Usage Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Git/Data/Manuals/My Git Usage Reference/My Git Usage Reference.org")
 (front-context-string . "#+TITLE: My Git ")
 (rear-context-string)
 (position . 1))
("Disease Database.org"
 (filename . "~/Org/Wiki/Medicine/Disease Database/Disease Database.org")
 (front-context-string . "#+TITLE: Disease")
 (rear-context-string)
 (position . 1))
("Yi Learning.org"
 (filename . "~/Org/Wiki/Mysterious Culture/Yi Learning/Yi Learning.org")
 (front-context-string . "#+TITLE: Yi Lear")
 (rear-context-string)
 (position . 1))
("My Erotic Novels Collections"
 (filename . "~/Org/Wiki/Pornography/Erotic/Erotic Literature/Erotic Literature.org")
 (front-context-string . "\n\n- [[file+sys:D")
 (rear-context-string . "vels Collections")
 (position . 1153))
("My Liked Loving.org"
 (filename . "~/Org/Wiki/Love/Data/Manuals/My Liked Loving/My Liked Loving.org")
 (front-context-string . "* 《白蛇传》\n:PROPERT")
 (rear-context-string)
 (position . 1))
("Emacs Lisp.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs Lisp/Emacs Lisp.org")
 (front-context-string . "* Intro\n\n\n** Fea")
 (rear-context-string)
 (position . 1))
("Mysterious Culture.org"
 (filename . "~/Org/Wiki/Mysterious Culture/Mysterious Culture.org")
 (front-context-string . "#+TITLE: Mysteri")
 (rear-context-string)
 (position . 1))
("Eshell.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/Eshell.org")
 (front-context-string . "* Intro\n\nThere a")
 (rear-context-string)
 (position . 1))
("Common Lisp.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Common Lisp/Common Lisp.org")
 (front-context-string . "#+TITLE: Common ")
 (rear-context-string)
 (position . 1))
("C#.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C#/C#.org")
 (front-context-string . "#+TITLE: C# Prog")
 (rear-context-string)
 (position . 1))
("My Favourite Foods.org"
 (filename . "~/Org/Wiki/Recipes/Data/Manuals/My Favourite Foods/My Favourite Foods.org")
 (front-context-string . "#+TITLE: My Favo")
 (rear-context-string)
 (position . 1))
("My Recipes Reference.org"
 (filename . "~/Org/Wiki/Recipes/Data/Manuals/My Recipes Reference/My Recipes Reference.org")
 (front-context-string . "#+TITLE: My Reci")
 (rear-context-string)
 (position . 1))
("Recipes.org"
 (filename . "~/Org/Wiki/Recipes/Recipes.org")
 (front-context-string . "* Breakfast\n\n* L")
 (rear-context-string)
 (position . 1))
("My ClojureScript Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/Data/Manuals/My ClojureScript Examples/My ClojureScript Examples.org")
 (front-context-string . "#+TITLE: My Cloj")
 (rear-context-string)
 (position . 1))
("My ClojureScript's Standard Library.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/Data/Manuals/My ClojureScript's Standard Library/My ClojureScript's Standard Library.org")
 (front-context-string . "#+TITLE: My Cloj")
 (rear-context-string)
 (position . 1))
("My ClojureScript Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/Data/Manuals/My ClojureScript Language Syntax Reference/My ClojureScript Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Cloj")
 (rear-context-string)
 (position . 1))
("Crack Methods.org"
 (filename . "~/Org/Wiki/Computer Technology/Crack/Data/Crack Methods/Crack Methods.org")
 (front-context-string . "#+TITLE: Crack M")
 (rear-context-string)
 (position . 1))
("My Docker Manual.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Docker/Data/Manuals/My Docker Manual/My Docker Manual.org")
 (front-context-string)
 (rear-context-string)
 (position . 1))
("Docker.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Docker/Docker.org")
 (front-context-string . "#+TITLE: Docker\n")
 (rear-context-string)
 (position . 1))
("Scala.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Scala/Scala.org")
 (front-context-string . "#+TITLE: Scala P")
 (rear-context-string)
 (position . 1))
("My R Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/R/Data/Manuals/My R Language Syntax Reference/My R Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My R La")
 (rear-context-string)
 (position . 1))
("Prolog.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Prolog/Prolog.org")
 (front-context-string . "#+TITLE: Prolog ")
 (rear-context-string)
 (position . 1))
("Lua.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lua/Lua.org")
 (front-context-string . "#+TITLE: Lua Pro")
 (rear-context-string)
 (position . 1))
("LaTeX.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/TeX/LaTeX/LaTeX.org")
 (front-context-string . "#+TITLE: LaTeX\n\n")
 (rear-context-string)
 (position . 1))
("HTML5.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/HTML/HTML5/HTML5.org")
 (front-context-string . "#+TITLE: HTML5\n\n")
 (rear-context-string)
 (position . 1))
("Bash.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/Bash/Bash.org")
 (front-context-string . "#+TITLE: Bash\n\n*")
 (rear-context-string)
 (position . 1))
("C++.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C++/C++.org")
 (front-context-string . "#+TITLE: C++ Pro")
 (rear-context-string)
 (position . 1))
("Programmer.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programmer/Programmer.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
("Open Source.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Open Source/Open Source.org")
 (front-context-string . "#+TITLE: Open So")
 (rear-context-string)
 (position . 1))
("Programming Concepts.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Concepts/Programming Concepts.org")
 (front-context-string . "* Introspection ")
 (rear-context-string)
 (position . 1))
("My Data Structures Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Data Structure/Data/Manuals/My Data Structures Reference/My Data Structures Reference.org")
 (front-context-string . "#+TITLE: My Data")
 (rear-context-string)
 (position . 1))
("Data Structure.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Data Structure/Data Structure.org")
 (front-context-string . "#+TITLE: Data St")
 (rear-context-string)
 (position . 1))
("My Algorithms Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Algorithm/Data/Manuals/My Algorithms Reference/My Algorithms Reference.org")
 (front-context-string . "#+TITLE: My Algo")
 (rear-context-string)
 (position . 1))
("Algorithm.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Algorithm/Algorithm.org")
 (front-context-string . "#+TITLE: Algorit")
 (rear-context-string)
 (position . 1))
("Talents.org"
 (filename . "~/Org/Wiki/Talents/Talents.org")
 (front-context-string . "#+TITLE: Talents")
 (rear-context-string)
 (position . 1))
("Mathematics Formula Reference.org"
 (filename . "~/Org/Wiki/Mathematics/Data/Manuals/Mathematics Formula Reference/Mathematics Formula Reference.org")
 (front-context-string . "#+TITLE: Mathema")
 (rear-context-string)
 (position . 1))
("Mathematics Terms Reference.org"
 (filename . "~/Org/Wiki/Mathematics/Data/Manuals/Mathematics Terms Reference/Mathematics Terms Reference.org")
 (front-context-string . "#+TITLE: Mathema")
 (rear-context-string)
 (position . 1))
("My Swift Programming Language Practical Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Swift/Data/Manuals/My Swift Programming Language Practical Examples/My Swift Programming Language Practical Examples.org")
 (front-context-string)
 (rear-context-string)
 (position . 1))
("My Swift Programming Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Swift/Data/Manuals/My Swift Programming Language Syntax Reference/My Swift Programming Language Syntax Reference.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("org-capture-last-stored-marker"
 (filename . "~/Org/Contacts/Contacts.org")
 (front-context-string . "** 郭铁勇\n:PROPERTI")
 (rear-context-string . "姐姐的女儿\"\n:END:\n\n\n\n")
 (position . 84505))
("org-refile-last-stored"
 (filename . "~/Org/Contacts/Contacts.org")
 (front-context-string . "** 郭铁勇\n:PROPERTI")
 (rear-context-string . "姐姐的女儿\"\n:END:\n\n\n\n")
 (position . 84505))
("Vim.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Vim/Vim.org")
 (front-context-string . "* Intro\n\n*神之编辑器*")
 (rear-context-string)
 (position . 1))
("Internet Censorship.org"
 (filename . "~/Org/Wiki/Computer Technology/Internet Censorship/Internet Censorship.org")
 (front-context-string . "* Intro\n\n** Chin")
 (rear-context-string)
 (position . 1))
("Computer Machine.org"
 (filename . "~/Org/Wiki/Computer Technology/Computer Machine/Computer Machine.org")
 (front-context-string . "* Data\n\n** Help\n")
 (rear-context-string)
 (position . 13))
("Computer Forensics.org"
 (filename . "~/Org/Wiki/Computer Technology/Computer Forensics/Computer Forensics.org")
 (front-context-string . "* Intro\n\n\n\n\n\n* D")
 (rear-context-string)
 (position . 1))
("Imperial Study.org"
 (filename . "~/Org/Wiki/Imperial Study/Imperial Study.org")
 (front-context-string . "出鳞片、尾巴和触角，，最终英雄变")
 (rear-context-string . "身上，看着闪烁的黄金，慢慢地长\n")
 (position . 220))
("My Python Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Data/Manuals/My Python Examples/My Python Examples.org")
 (front-context-string . "* System\n\n** she")
 (rear-context-string)
 (position . 1))
("My Python Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Data/Manuals/My Python Language Syntax Reference/My Python Language Syntax Reference.org")
 (front-context-string . "* Data Types\n\n\n*")
 (rear-context-string)
 (position . 1))
("My Clojure Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Manuals/My Clojure Examples/My Clojure Examples.org")
 (front-context-string . "* Print\n\n** form")
 (rear-context-string . "cumentation]]\n\n\n")
 (position . 1154))
("My Clojure Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Data/Manuals/My Clojure Language Syntax Reference/My Clojure Language Syntax Reference.org")
 (front-context-string . "\n\n** nil, truth ")
 (rear-context-string . " Data Structures")
 (position . 33303))
("My SQL Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/Data/Manuals/My SQL Language Syntax Reference/My SQL Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My SQL ")
 (rear-context-string)
 (position . 1))
("CSS.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/CSS/CSS.org")
 (front-context-string . "#+TITLE: CSS Pro")
 (rear-context-string)
 (position . 1))
("My CSS Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/CSS/Data/Manuals/My CSS Language Syntax Reference/My CSS Language Syntax Reference.org")
 (front-context-string . "* Concepts\n\n** A")
 (rear-context-string)
 (position . 1))
("My HTML Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/HTML/Data/Manuals/My HTML Syntax Reference/My HTML Syntax Reference.org")
 (front-context-string . "* Notes\n\n** Org-")
 (rear-context-string)
 (position . 1))
("HTML.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/HTML/HTML.org")
 (front-context-string . "#+TITLE: HTML Pr")
 (rear-context-string)
 (position . 1))
("My JavaScript Language Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Manuals/My JavaScript Language Examples/My JavaScript Language Examples.org")
 (front-context-string . "* Intro\n\n\n* Java")
 (rear-context-string)
 (position . 1))
("My JavaScript Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/Data/Manuals/My JavaScript Language Syntax Reference/My JavaScript Language Syntax Reference.org")
 (front-context-string . "* How JavaScript")
 (rear-context-string)
 (position . 1))
("JavaScript.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/JavaScript/JavaScript.org")
 (front-context-string . "#+TITLE: JavaScr")
 (rear-context-string)
 (position . 1))
("My C Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C/Data/Manuals/My C Examples/My C Examples.org")
 (front-context-string . "* Libraries\n\n** ")
 (rear-context-string)
 (position . 1))
("My C Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C/Data/Manuals/My C Language Syntax Reference/My C Language Syntax Reference.org")
 (front-context-string . "* Intro\n\n** Comp")
 (rear-context-string)
 (position . 1))
("C Programming Language"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/C/C.org")
 (front-context-string . "* Intro\n\n** Abou")
 (rear-context-string)
 (position . 1))
("GitHub.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Git/GitHub.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
("My Go Language Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Go/Data/Manuals/My Go Language Examples/My Go Language Examples.org")
 (front-context-string . "#+TITLE: My Go L")
 (rear-context-string)
 (position . 1))
("My Go Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Go/Data/Manuals/My Go Language Syntax Reference/My Go Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Go L")
 (rear-context-string)
 (position . 1))
("Go.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Go/Go.org")
 (front-context-string . "#+TITLE: Go Prog")
 (rear-context-string)
 (position . 1))
("OCaml.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/OCaml/OCaml.org")
 (front-context-string . "#+TITLE: OCaml P")
 (rear-context-string)
 (position . 1))
("My Julia Language Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Julia/Data/Manuals/My Julia Language Examples/My Julia Language Examples.org")
 (front-context-string . "* System\n\n** Inv")
 (rear-context-string)
 (position . 1))
("My Julia Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Julia/Data/Manuals/My Julia Language Syntax Reference/My Julia Language Syntax Reference.org")
 (front-context-string . "* Variables -- ~")
 (rear-context-string)
 (position . 1))
("Julia.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Julia/Julia.org")
 (front-context-string . "#+TITLE: Julia P")
 (rear-context-string)
 (position . 1))
("Looks.org"
 (filename . "~/Org/Wiki/Looks/Looks.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
("Swift.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Swift/Swift.org")
 (front-context-string . "#+TITLE: Swift P")
 (rear-context-string)
 (position . 1))
("My TeX Symbols Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/TeX/Data/Manuals/My TeX Symbols Reference/My TeX Symbols Reference.org")
 (front-context-string . "* LaTeX symbol -")
 (rear-context-string)
 (position . 1))
("My TeX Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/TeX/Data/Manuals/My TeX Syntax Reference/My TeX Syntax Reference.org")
 (front-context-string . "* Document Struc")
 (rear-context-string)
 (position . 1))
("CIDER.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/CIDER.org")
 (front-context-string . "#+TITLE: CIDER\n\n")
 (rear-context-string)
 (position . 1))
("Rust.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Rust/Rust.org")
 (front-context-string . "#+TITLE: Rust Pr")
 (rear-context-string)
 (position . 1))
("NoSQL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/NoSQL/NoSQL.org")
 (front-context-string . "#+TITLE: NoSQL\n\n")
 (rear-context-string)
 (position . 1))
("PostgresQL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/PostgresQL/PostgresQL.org")
 (front-context-string . "* Intro\n\n*A soph")
 (rear-context-string)
 (position . 1))
("MariaDB.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/MariaDB/MariaDB.org")
 (front-context-string . "#+TITLE: MariaDB")
 (rear-context-string)
 (position . 1))
("MySQL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/MySQL/MySQL.org")
 (front-context-string . "#+TITLE: MySQL\n\n")
 (rear-context-string)
 (position . 1))
("SQL.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/SQL.org")
 (front-context-string . "#+TITLE: SQL\n\n* ")
 (rear-context-string)
 (position . 1))
("Database.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/Database.org")
 (front-context-string . "#+TITLE: Databas")
 (rear-context-string)
 (position . 1))
("My Java Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Java/Data/Manuals/My Java Examples/My Java Examples.org")
 (front-context-string . "#+TITLE: My Java")
 (rear-context-string)
 (position . 1))
("My Java Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Java/Data/Manuals/My Java Language Syntax Reference/My Java Language Syntax Reference.org")
 (front-context-string . "#+TITLE: My Java")
 (rear-context-string)
 (position . 1))
("Java.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Java/Java.org")
 (front-context-string . "#+TITLE: Java Pr")
 (rear-context-string)
 (position . 1))
("The Sex Mechanism.org"
 (filename . "~/Org/Wiki/Sexology/Data/Manuals/The Sex Mechanism/The Sex Mechanism.org")
 (front-context-string)
 (rear-context-string)
 (position . 1))
("My Shell Script Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/Data/Manuals/My Shell Script Examples/My Shell Script Examples.org")
 (front-context-string . "* Linux\n\n** Dete")
 (rear-context-string)
 (position . 1))
("My Bash Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/Bash/Data/Manuals/My Bash Syntax Reference/My Bash Syntax Reference.org")
 (front-context-string . "* Common Environ")
 (rear-context-string)
 (position . 1))
("My Shell Script Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/Data/Manuals/My Shell Script Syntax Reference/My Shell Script Syntax Reference.org")
 (front-context-string . "#+TITLE: My Shel")
 (rear-context-string)
 (position . 1))
("Shell.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Shell/Shell.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("Sinatra.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Ruby/Data/Frameworks/Sinatra/Sinatra.org")
 (front-context-string . "* Intro\n\nSinatra")
 (rear-context-string)
 (position . 1))
("Ruby.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Ruby/Ruby.org")
 (front-context-string . "* Intro\n\n[[file:")
 (rear-context-string)
 (position . 1))
("Hacker.org"
 (filename . "~/Org/Wiki/Computer Technology/Hack/Hacker/Hacker.org")
 (front-context-string . "* Hacker Ethic\n\n")
 (rear-context-string)
 (position . 1))
("Dark Net.org"
 (filename . "~/Org/Wiki/Computer Technology/Crack/Dark Net/Dark Net.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
("ClojureScript.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/ClojureScript/ClojureScript.org")
 (front-context-string . "#+TITLE: Clojure")
 (rear-context-string)
 (position . 1))
("Operation.org"
 (filename . "~/Org/Wiki/Commercial Science/Operation/Operation.org")
 (front-context-string . "* Intro\n\n** Oper")
 (rear-context-string)
 (position . 1))
("Marketing.org"
 (filename . "~/Org/Wiki/Commercial Science/Marketing/Marketing.org")
 (front-context-string . "* Intro\n\n** Mark")
 (rear-context-string)
 (position . 1))
("Startup.org"
 (filename . "~/Org/Wiki/Commercial Science/Startup/Startup.org")
 (front-context-string . "#+TITLE: Startup")
 (rear-context-string)
 (position . 1))
("Company.org"
 (filename . "~/Org/Wiki/Commercial Science/Company/Company.org")
 (front-context-string . "#+TITLE: Company")
 (rear-context-string)
 (position . 1))
("Business.org"
 (filename . "~/Org/Wiki/Commercial Science/Business/Business.org")
 (front-context-string . "#+TITLE: Busines")
 (rear-context-string)
 (position . 1))
("Commercial Science.org"
 (filename . "~/Org/Wiki/Commercial Science/Commercial Science.org")
 (front-context-string . "* Intro\n\n** Sent")
 (rear-context-string)
 (position . 1))
("ASCII.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/ASCII/ASCII.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("Crack.org"
 (filename . "~/Org/Wiki/Computer Technology/Crack/Crack.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("Hack.org"
 (filename . "~/Org/Wiki/Computer Technology/Hack/Hack.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
("Python.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Python/Python.org")
 (front-context-string . "* Intro\n\n** Logo")
 (rear-context-string)
 (position . 1))
("Configurations.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Configurations.org")
 (front-context-string . "* Data\n\n- [[http")
 (rear-context-string)
 (position . 1))
("Emacs.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/Emacs.org")
 (front-context-string . "#+TITLE: Emacs\n\n")
 (rear-context-string)
 (position . 1))
("Firefox.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Firefox/Firefox.org")
 (front-context-string . "#+TITLE: Firefox")
 (rear-context-string)
 (position . 1))
("Chrome.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Chrome/Chrome.org")
 (front-context-string . "* Intro\n\n\n\n** Sc")
 (rear-context-string)
 (position . 1))
("H.org"
 (filename . "~/Org/Wiki/Pornography/H/H.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
("Pornography.org"
 (filename . "~/Org/Wiki/Pornography/Pornography.org")
 (front-context-string . "#+TITLE: Pornogr")
 (rear-context-string)
 (position . 1))
("Freelancer.org"
 (filename . "~/Org/Wiki/Work/Freelancer/Freelancer.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("SQLite.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/SQLite/SQLite.org")
 (front-context-string . "#+TITLE: SQLite\n")
 (rear-context-string)
 (position . 1))
("Clojure.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Clojure/Clojure.org")
 (front-context-string . "#+TITLE: Clojure")
 (rear-context-string)
 (position . 1))
("R.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/R/R.org")
 (front-context-string . "*** Manuals\n\n***")
 (rear-context-string . "S:\n: linux-gnu\n\n")
 (position . 14299))
("Learning.org"
 (filename . "~/Org/Wiki/Learning/Learning.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
("My Haskell Language Syntax Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Haskell/Data/Manuals/My Haskell Language Syntax Reference/My Haskell Language Syntax Reference.org")
 (front-context-string . "* Expression\n\n* ")
 (rear-context-string)
 (position . 1))
("My Haskell Examples.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Haskell/Data/Manuals/My Haskell Examples/My Haskell Examples.org")
 (front-context-string . "** Prelude\n\nThe ")
 (rear-context-string)
 (position . 12))
("Haskell.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Haskell/Haskell.org")
 (front-context-string . "Haskell Data Ana")
 (rear-context-string . "is [0/1]\n\n- [ ] ")
 (position . 10457))
("TeX.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/TeX/TeX.org")
 (front-context-string . "#+TITLE: TeX\n\n* ")
 (rear-context-string)
 (position . 1))
("Love.org"
 (filename . "~/Org/Wiki/Love/Love.org")
 (front-context-string . "#+TITLE: Love\n\n*")
 (rear-context-string)
 (position . 1))
("Health.org"
 (filename . "~/Org/Wiki/Health/Health.org")
 (front-context-string . "Nutrition]]\n\n\n* ")
 (rear-context-string . "/Nutrition.org][")
 (position . 70))
("TeX Macro Packages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/TeX/Data/TeX Macro Packages/TeX Macro Packages.org")
 (front-context-string . "* About TeX Pack")
 (rear-context-string)
 (position . 1))
("Lisp.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Lisp/Lisp.org")
 (front-context-string . "#+TITLE: Lisp\n\n*")
 (rear-context-string)
 (position . 1))
("Commands.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Commands.org")
 (front-context-string . "#+TITLE: Command")
 (rear-context-string)
 (position . 1))
("Gems.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Ruby/Data/Gems/Gems.org")
 (front-context-string . "[[file:rdefs.org")
 (rear-context-string . " definitions\n\n- ")
 (position . 5364))
("Org-mode.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/Org-mode/Org-mode.org")
 (front-context-string . "* Document Struc")
 (rear-context-string . "g-mode files.\n\n\n")
 (position . 60787))
("modes.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Emacs/modes/modes.org")
 (front-context-string . "[[file:~/Org/Wik")
 (rear-context-string . "][floobits]] :: ")
 (position . 172601))
("Softwares.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Softwares.org")
 (front-context-string . "#+TITLE: Softwar")
 (rear-context-string)
 (position . 1))
("Programming Languages.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Programming Languages.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
("Programming.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming.org")
 (front-context-string . "#+TITLE: Program")
 (rear-context-string)
 (position . 1))
("Computer Technology.org"
 (filename . "~/Org/Wiki/Computer Technology/Computer Technology.org")
 (front-context-string . "* Intro\n:PROPERT")
 (rear-context-string)
 (position . 1))
("Poem.org"
 (filename . "~/Org/Wiki/Literature/Poem/Poem.org")
 (front-context-string . "* Intro\n\n\n\n\n* Da")
 (rear-context-string)
 (position . 1))
("My SQL Reference.org"
 (filename . "~/Org/Wiki/Computer Technology/Programming/Programming Languages/Database/SQL/Data/Manuals/My SQL Reference/My SQL Reference.org")
 (front-context-string . "\n\n\n** SELECT DIS")
 (rear-context-string . "%20Joins.png]]\n\n")
 (position . 3676))
("Internet.org"
 (filename . "~/Org/Wiki/Internet/Internet.org")
 (front-context-string . "#+TITLE: Interne")
 (rear-context-string)
 (position . 1))
("My Masturbation Manual.org"
 (filename . "~/Org/Wiki/Sexology/Masturbation/Data/Manuals/My Masturbation Manual/My Masturbation Manual.org")
 (front-context-string . "#+TITLE: My Mast")
 (rear-context-string)
 (position . 1))
("Electronics.org"
 (filename . "~/Org/Wiki/Electronics/Electronics.org")
 (front-context-string)
 (rear-context-string)
 (position . 1))
("Kindle.org"
 (filename . "~/Org/Wiki/Computer Technology/Softwares/Kindle/Kindle.org")
 (front-context-string . "#+TITLE: Kindle\n")
 (rear-context-string)
 (position . 1))
("ACG"
 (filename . "~/Org/Wiki/ACG/ACG.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("Clothes.org"
 (filename . "~/Org/Wiki/Clothes/Clothes.org")
 (front-context-string . "* Clothes\n\n\n\n* P")
 (rear-context-string)
 (position . 1))
("Novels.org"
 (filename . "~/Org/Wiki/Literature/Novels/Novels.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
("Medicine.org"
 (filename . "~/Org/Wiki/Medicine/Medicine.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
("Beauty.org"
 (filename . "~/Org/Beauty/Beauty.org")
 (front-context-string . "#+TITLE: Beauty\n")
 (rear-context-string)
 (position . 1))
("Sexology"
 (filename . "~/Org/Wiki/Sexology/Sexology.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
("Recipes"
 (filename . "~/Org/Wiki/Recipes/Recipes.org")
 (front-context-string . "* Breakfast\n\n* L")
 (rear-context-string)
 (position . 1))
("Experience"
 (filename . "~/Org/Experience/Experience.org")
 (front-context-string . "* Life Feeling\n\n")
 (rear-context-string)
 (position . 1))
("Myself"
 (filename . "~/Org/Myself/Myself.org")
 (front-context-string . "* My Info\n\n[[fil")
 (rear-context-string)
 (position . 1))
("Economy.org"
 (filename . "~/Org/Wiki/Economy/Economy.org")
 (front-context-string . "#+TITLE: Economy")
 (rear-context-string)
 (position . 1))
("Strategy"
 (filename . "~/Org/Wiki/Strategy/Strategy.org")
 (front-context-string . "* Intro\n\n** 名句思想")
 (rear-context-string)
 (position . 1))
("Travel"
 (filename . "~/Org/Wiki/Travel/Travel.org")
 (front-context-string . "* Intro\n\n\n\n* Dat")
 (rear-context-string)
 (position . 1))
("Government.org"
 (filename . "~/Org/Wiki/Government/Government.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("Law"
 (filename . "~/Org/Wiki/Law/Law.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("My Applied Mathematics Formula Reference.org"
 (filename . "~/Org/Wiki/Mathematics/Data/Manuals/My Applied Mathematics Formula Reference/My Applied Mathematics Formula Reference.org")
 (front-context-string . "#+TITLE: Applied")
 (rear-context-string)
 (position . 1))
("Philosophy"
 (filename . "~/Org/Wiki/Philosophy/Philosophy.org")
 (front-context-string . "* Intro\n\n** Phil")
 (rear-context-string)
 (position . 1))
("Religion"
 (filename . "~/Org/Wiki/Religion/Religion.org")
 (front-context-string . "* Buddhism (佛教)\n")
 (rear-context-string)
 (position . 1))
("dotfiles (org-mode literate)"
 (filename . "~/Org/dotfiles/dotfiles.org")
 (front-context-string)
 (rear-context-string)
 (position . 1))
("Bookmarks (Org)"
 (filename . "~/Org/Bookmarks/Bookmarks.org")
 (front-context-string . "* Intro\n\n** TODO")
 (rear-context-string)
 (position . 1))
("Diary.org"
 (filename . "~/Org/Diary/Diary.org")
 (front-context-string . "#+CATEGORY: Diar")
 (rear-context-string)
 (position . 1))
("org-capture-last-stored"
 (filename . "~/Org/Tasks/Words.org")
 (front-context-string . "* delightful :dr")
 (rear-context-string . "/indirection/.\n\n")
 (position . 7916))
("Accounts"
 (filename . "~/Org/Accounts/accounts.org.gpg")
 (front-context-string . "* Nick\n\nstardivi")
 (rear-context-string)
 (position . 1))
("Contacts.org"
 (filename . "~/Org/Contacts/Contacts.org")
 (front-context-string . "#+TITLE: Contact")
 (rear-context-string)
 (position . 1))
("init.el"
 (filename . "~/.emacs.d/init.el")
 (front-context-string . ";; Added by Pack")
 (rear-context-string)
 (position . 1))
("Arch install.sh"
 (filename . "~/Git/Arch/install.sh")
 (front-context-string . "#!/usr/bin/env b")
 (rear-context-string)
 (position . 1))
("Revenge"
 (filename . "~/Org/Revenge/Revenge.org")
 (front-context-string . "* I Swear\n\n- 当初说")
 (rear-context-string)
 (position . 1))
("Life"
 (filename . "~/Org/Wiki/Life/Life.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("Writing"
 (filename . "~/Org/Wiki/Writing/Writing.org")
 (front-context-string . "* Words (文字)\n\n[[")
 (rear-context-string)
 (position . 1))
("Features"
 (filename . "~/Org/Projects/Projects.org")
 (front-context-string . "* TODO Features ")
 (rear-context-string . "Q voice chat.\n\n*")
 (position . 19882))
("Issues"
 (filename . "~/Org/Projects/Projects.org")
 (front-context-string . "* TODO Issues [2")
 (rear-context-string . "OGBOOK:\n:END:\n\n*")
 (position . 12268))
("Bugs"
 (filename . "~/Org/Projects/Projects.org")
 (front-context-string . "* TODO Bugs [/]\n")
 (rear-context-string . " everyday.\n\n\n\n\n*")
 (position . 12196))
("Investing & Financing (Org)"
 (filename . "~/Org/Wiki/Investing and Financing/Investing and Financing.org")
 (front-context-string . "* Intro\n\n\n* Data")
 (rear-context-string)
 (position . 1))
("Sociology (Org)"
 (filename . "~/Org/Wiki/Sociology/Sociology.org")
 (front-context-string . "\n* Sociology (社会")
 (rear-context-string . " Intro\n\n\n* Data\n")
 (position . 18))
("Mathematics (Org)"
 (filename . "~/Org/Wiki/Mathematics/Mathematics.org")
 (front-context-string . "  - [ ] [[file+s")
 (rear-context-string . "学 同济大学数学系 [0/4]\n")
 (position . 156))
("Psychology (Org)"
 (filename . "~/Org/Wiki/Psychology/Psychology.org")
 (front-context-string . " Tips\n\n- 心怀期待更快乐")
 (rear-context-string . "* Books\n\n* Small")
 (position . 36))
("Literature (Org)"
 (filename . "~/Org/Wiki/Literature/Literature.org")
 (front-context-string)
 (rear-context-string . "* Data\n\n** Books")
 (position . 27))
("Science (Org)"
 (filename . "~/Org/Wiki/Science/Science.org")
 (front-context-string . "* Science and Te")
 (rear-context-string)
 (position . 1))
("Kung Fu (Org)"
 (filename . "~/Org/Wiki/Kung Fu/Kung Fu.org")
 (front-context-string . "* Urgent 易筋经 (mu")
 (rear-context-string)
 (position . 1))
("Learning (Org)"
 (filename . "~/Org/Wiki/Learning/Learning.org")
 (front-context-string . "- [ ] [[file+sys")
 (rear-context-string . "s.org][Emacs]]\n\n")
 (position . 17461))
("Thought (Org)"
 (filename . "~/Org/Wiki/Thought/Thought.org")
 (front-context-string . "- Believe that y")
 (rear-context-string)
 (position . 12))
("Reading (Org)"
 (filename . "~/Org/Wiki/Reading/Reading.org")
 (front-context-string . "[[file:Literatur")
 (rear-context-string . "Literature (文学)\n")
 (position . 30))
("Data (Org)"
 (filename . "~/Org/Wiki/Data/Data.org")
 (front-context-string . "*** Search Engin")
 (rear-context-string . "s\n\n** Internet\n\n")
 (position . 35))
("Wiki (Org)"
 (filename . "~/Org/Wiki/Wiki.org")
 (front-context-string . "[[file:Reading/R")
 (rear-context-string . "\n* Reading (阅读)\n")
 (position . 59))
("INDEX (Org)"
 (filename . "~/Org/INDEX.org")
 (front-context-string . "* Learning (学习)\n")
 (rear-context-string . "  =精于心, 简于形.=\n\n\n")
 (position . 164))
)