;;; init-org-tag.el --- init for Org Tags
;;; -*- coding: utf-8 -*-

;;; Commentary:



;;; Code:


;;; Tags

(setq org-auto-align-tags nil)

(setq org-tag-persistent-alist
      '(("ARCHIVE" . ?A)
        ("noexport" . ?E)
        ("private" . ?P)
        ("deprecated" . ?D)
        ("outdated" . ?O)))

;; auto add tag "LOG" for [C-c C-z] add log note.
(add-to-list 'org-tag-persistent-alist '("LOG"))
(defun my/org-add-note--auto-add-tag ()
  "Auto add tag 'NOTE' when add note log."
  (org-back-to-heading)
  ;; remove multiple same "LOG" tags
  (autoload 'seq-uniq "seq.el")
  (org-set-tags (seq-uniq (cons "LOG" (org-get-tags nil t)))))
(advice-add 'org-add-note :after #'my/org-add-note--auto-add-tag)

;;; for Org Book reading journal. Mark an headline as a book
(add-to-list 'org-tag-persistent-alist '("book" . ?h))
(add-to-list 'org-default-properties "AUTHOR")
(add-to-list 'org-default-properties "PUBLISH_DATE")
(add-to-list 'org-default-properties "PRESS")

(setq org-tag-alist
      '((:startgroup) ("Org" . ?o) ("translation" . ?t) ("idea" . ?i) ("suggested") (:endgroup)

        ;; Task
        (:startgrouptag) ("@task" . nil) (:grouptags)
        ("table")
        ("event") ("check") ("alert") ("flag") ("tag") ("question") ("info") ("quote")
        ("star") ("heart") ("smile") ("like") ("trash")
        ("lock") ("unlock") ("key")
        ("refresh") ("repeat") ("inprogress") ("fragment")
        (:endgrouptag)
        
        ;; Life
        (:startgrouptag) ("@life" . nil) (:grouptags)
        ("talk") ("call") ("shopping") ("express")
        ("finance") ("money") ("credit_card") ("PayPal") ("btc")
        ("bee") ("coffee")
        ("hospital") ("medical") ("health")
        ("industry")
        ("law") ("government") ("censorship") ("complaint")
        ("watch") ("book" . ?h) ("bookmark" . ?b) ("note") ("paperclip")
        ("file") ("archive") ("document") ("word") ("excel") ("powerpoint") ("pdf")
        ("image") ("video") ("audio")
        ("search") ("download") ("upload") ("link") ("email") ("reply") ("share") ("rss")
        ("map") ("location")
        ("picture") ("music") ("film") ("headphone") ("game")
        ("camera") ("vlog") ("record")
        ("chart")
        ("bicycle") ("car") ("bus") ("subway") ("plane")
        ("travel")
        ("child")
        (:endgrouptag)
        
        ;; SEX
        (:startgrouptag) ("@SEX" . ?X) (:grouptags)
        ("date") ("pickup")
        (:endgrouptag)
        ;; Time
        (:startgroup) ("today" . nil) ("tomorrow" . nil) ("future" . nil) (:endgroup)
        ;; Places
        (:startgroup) ("company") ("home") (:endgroup)
        ;; Devices
        (:startgroup)
        ("computer") ("laptop") ("mobile")
        ("firefox") ("chrome")
        (:endgroup)
        ;; Work
        (:startgrouptag) ("@work" . ?w) (:grouptags)
        ("appointment" . ?a) ("meeting" . ?m) ("urgent" . ?u)
        (:endgrouptag)
        
        (:startgrouptag) ("@wiki" . ?k) (:grouptags)
        ("thought") ("philosophy") ("psychology") ("literature")
        ("computer_science") ("math")
        ("strategies")
        ("science") ("finance") ("business") ("economy")
        ("history") ("politics") ("society")
        ("medicine")
        (:endgrouptag)
        
        (:startgrouptag) ("@programming") (:grouptags)
        ("code" . ?C) ("source_code") ("bug") ("vulnerability") ("Emacs" . ?e) ("git" . ?G) ("GitHub") ("GitLab")
        (:startgroup)
        ("hardware") ("usb") ("disk") ("terminal") ("cloud") ("DevOps") ("docker")
        ("security")
        ("Linux" . ?L) ("Apple") ("macOS") ("Windows" . ?W) ("Android") ("iOS")
        ("LISP" . ?l) ("Common_Lisp") ("Clojure" . ?c) ("ClojureScript" . ?s)
        ("Java" . ?j) ("C") ("cpp") ("Go") ("Rust") ("Swift") ("C#" . ?#)
        ("Shell" . ?S) ("Python" . ?p) ("Ruby" . ?r)
        ("Web") ("JavaScript" . ?J) ("HTML") ("HTML5") ("CSS") ("CSS3")
        ("Firefox") ("Chrome") ("Edge") ("Safari")
        ("database" . ?d) ("SQL") ("PostgreSQL") ("MySQL") ("MariaDB") ("Oracle") ("SQLite") ("DB2")
        ("TeX") ("LaTeX") ("Markdown") ("reStructuredText") ("AsciiDoc") ("YAML") ("TOML") ("CWL")
        ;; Internet
        ("Internet") ("Google") ("Facebook") ("Twitter") ("Microsoft") ("Amazon")
        ("YouTube") ("PornHub") ("Instagram") ("Dribbble") ("Dropbox") ("whatsapp")
        ("Baidu") ("Tencent") ("weixin") ("wechat") ("weibo")
        (:endgroup)
        (:endgrouptag)
        
        (:startgroup)
        (:startgrouptag) ("@family") (:grouptags)
        ("sister") ("father") ("mother")
        (:endgrouptag)
        (:startgrouptag) ("@relative") (:endgrouptag)
        (:startgrouptag) ("@girlfriend") (:endgrouptag)
        (:startgrouptag) ("@workmate") (:endgrouptag)
        (:startgrouptag) ("@friend") (:grouptags)
        ("good_friend") ("friend") ("person_who_knows")
        (:endgrouptag)
        (:endgroup)
        
        (:startgrouptag) ("@project") (:grouptags)
        ("agriculture")
        (:endgrouptag)
        
        (:startgrouptag) ("@company") (:grouptags)
        ("users") ("promotion") ("copyright")
        (:endgrouptag)
        
        (:startgrouptag) ("country") (:grouptags)
        ("afghanistan")
        ("aland_islands")
        ("albania")
        ("algeria")
        ("american_samoa")
        ("andorra")
        ("angola")
        ("anguilla")
        ("antigua_and_barbuda")
        ("argentina")
        ("armenia")
        ("aruba")
        ("australia")
        ("austria")
        ("azerbaijan")
        ("azores_islands")
        ("bahamas")
        ("bahrain")
        ("balearic_islands")
        ("bangladesh")
        ("barbados")
        ("basque_country")
        ("belarus")
        ("belgium")
        ("belize")
        ("benin")
        ("bermuda")
        ("bhutan")
        ("bolivia")
        ("bonaire")
        ("bosnia_and_herzegovina")
        ("botswana")
        ("brazil")
        ("british_columbia")
        ("british_indian_ocean_territory")
        ("british_virgin_islands")
        ("brunei")
        ("bulgaria")
        ("burkina_faso")
        ("burundi")
        ("cambodia")
        ("cameroon")
        ("canada")
        ("canary_islands")
        ("cape_verde")
        ("cayman_islands")
        ("central_african_republic")
        ("ceuta")
        ("chad")
        ("chile")
        ("china")
        ("christmas_island")
        ("cocos_island")
        ("colombia")
        ("comoros")
        ("cook_islands")
        ("corsica")
        ("costa_rica")
        ("croatia")
        ("cuba")
        ("curacao")
        ("cyprus")
        ("czech_republic")
        ("democratic_republic_of_congo")
        ("denmark")
        ("djibouti")
        ("dominica")
        ("dominican_republic")
        ("east_timor")
        ("ecuador")
        ("egypt")
        ("el_salvador")
        ("england")
        ("equatorial_guinea")
        ("eritrea")
        ("estonia")
        ("ethiopia")
        ("european_union")
        ("falkland_islands")
        ("faroe_islands")
        ("fiji")
        ("finland")
        ("france")
        ("french_polynesia")
        ("gabon")
        ("galapagos_islands")
        ("gambia")
        ("georgia")
        ("germany")
        ("ghana")
        ("gibraltar")
        ("greece")
        ("greenland")
        ("grenada")
        ("guam")
        ("guatemala")
        ("guernsey")
        ("guinea_bissau")
        ("guinea")
        ("haiti")
        ("hawaii")
        ("honduras")
        ("hong_kong")
        ("hungary")
        ("iceland")
        ("india")
        ("indonesia")
        ("iran")
        ("iraq")
        ("ireland")
        ("isle_of_man")
        ("israel")
        ("italy")
        ("ivory_coast")
        ("jamaica")
        ("japan")
        ("jersey")
        ("jordan")
        ("kazakhstan")
        ("kenya")
        ("kiribati")
        ("kosovo")
        ("kuwait")
        ("kyrgyzstan")
        ("laos")
        ("latvia")
        ("lebanon")
        ("lesotho")
        ("liberia")
        ("libya")
        ("liechtenstein")
        ("lithuania")
        ("luxembourg")
        ("macao")
        ("madagascar")
        ("madeira")
        ("malawi")
        ("malaysia")
        ("maldives")
        ("mali")
        ("malta")
        ("marshall_island")
        ("martinique")
        ("mauritania")
        ("mauritius")
        ("melilla")
        ("mexico")
        ("micronesia")
        ("moldova")
        ("monaco")
        ("mongolia")
        ("montenegro")
        ("montserrat")
        ("morocco")
        ("mozambique")
        ("myanmar")
        ("namibia")
        ("nauru")
        ("nepal")
        ("netherlands")
        ("new_zealand")
        ("nicaragua")
        ("niger")
        ("nigeria")
        ("niue")
        ("norfolk_island")
        ("north_korea")
        ("northen_cyprus")
        ("northern_marianas_islands")
        ("norway")
        ("oman")
        ("orkney_islands")
        ("ossetia")
        ("otan")
        ("pakistan")
        ("palau")
        ("palestine")
        ("panama")
        ("papua_new_guinea")
        ("peru")
        ("philippines")
        ("pitcairn_islands")
        ("poland")
        ("portugal")
        ("puerto_rico")
        ("qatar")
        ("rapa_nui")
        ("republic_of_macedonia")
        ("republic_of_the_congo")
        ("romania")
        ("russia")
        ("rwanda")
        ("saba_island")
        ("sahrawi_arab_democratic_republic")
        ("saint_kitts_and_nevis")
        ("samoa")
        ("san_marino")
        ("sao_tome_and_principe")
        ("sardinia")
        ("saudi_arabia")
        ("scotland")
        ("senegal")
        ("serbia")
        ("seychelles")
        ("sicily")
        ("sierra_leone")
        ("singapore")
        ("sint_eustatius")
        ("sint_maarten")
        ("slovakia")
        ("slovenia")
        ("solomon_islands")
        ("somalia")
        ("somaliland")
        ("south_africa")
        ("south_korea")
        ("south_sudan")
        ("spain")
        ("sri_lanka")
        ("st_barts")
        ("st_lucia")
        ("st_vincent_and_the_grenadines")
        ("sudan")
        ("suriname")
        ("swaziland")
        ("sweden")
        ("switzerland")
        ("syria")
        ("taiwan")
        ("tajikistan")
        ("tanzania")
        ("thailand")
        ("tibet")
        ("togo")
        ("tokelau")
        ("tonga")
        ("transnistria")
        ("trinidad_and_tobago")
        ("tubalu")
        ("tunisia")
        ("turkey")
        ("turkmenistan")
        ("turks_and_caicos")
        ("uganda")
        ("ukraine")
        ("united_arab_emirates")
        ("united_kingdom")
        ("united_nations")
        ("america")
        ("uruguay")
        ("uzbekistn")
        ("vanuatu")
        ("vatican_city")
        ("venezuela")
        ("vietnam")
        ("virgin_islands")
        ("singapore")
        ("yemen")
        ("zambia")
        ("zimbabwe")
        (:endgrouptag)
        ))

(setq org-tag-faces
      '(("noexport" :foreground "DimGray" :weight bold :underline t :strike-through t)
        ("deprecated" :foreground "DimGray" :strike-through t)
        ("LOG" :foreground "DeepSkyBlue")
        ("private" :foreground "deep pink")
        ("book" :foreground "deep pink")
        ("fragment" :foreground "LightGray" :weight bold)
        ("computer" :foreground "green")
        ("@life" :foreground "black")
        ("@work" :foreground "DeepSkyBlue")
        ("@SEX" :foreground "deep pink" :weight bold)
        ("@Programming" :foreground "lawn green" :weight bold)
        ("Linux" :foreground "yellow" :weight bold)
        ("Mac" :foreground "#444444" :weight bold)
        ("Emacs" :foreground "dodger blue" :weight bold)
        ("Org" :foreground "green yellow" :weight bold)
        ("Hacker" :foreground "OrangeRed" :weight bold)
        ("LISP" :foreground "deep pink" :weight bold)
        ("Common_Lisp" :foreground "sky blue" :weight bold)
        ("Clojure" :foreground "sky blue" :weight bold)
        ("ClojureScript" :foreground "sky blue" :weight bold)
        ("Python" :foreground "yellow" :weight bold)
        ("Ruby" :foreground "red" :weight bold)
        ("Shell" :foreground "sea green")
        ("Java" :foreground "royal blue" :weight bold)
        ("C" :foreground "SaddleBrown" :weight bold)
        ("Go" :foreground "gold" :weight bold)
        ("Rust" :foreground "WhiteSmoke" :weight bold)
        ("JavaScript" :foreground "yellow" :weight bold)))

;; ;;; `org-archive-tag', `org-archived'
;; (defconst org-deprecated-tag "deprecated"
;;   "The tag that marks a subtree as archived.
;; An archived subtree does not open during visibility cycling, and does
;; not contribute to the agenda listings.")
;;
;; (defface org-deprecated '((t :inherit shadow))
;;   "Face for headline with the deprecated tag."
;;   :group 'org-faces)

;;; [ org-pretty-tags ] -- Surrogates for Org tags.

(use-package org-pretty-tags
  :ensure t
  :defer t
  :after org
  :delight org-pretty-tags-mode
  :commands (org-pretty-tags-mode org-pretty-tags-global-mode)
  :hook (after-init . org-pretty-tags-global-mode)
  :init (setq org-tag-faces nil)
  :config
  (setq org-pretty-tags-surrogate-strings
        `(("ARCHIVE" . ,(all-the-icons-faicon "archive"))
          ("noexport" . ,(all-the-icons-faicon "ban"))
          ("deprecated" . ,(all-the-icons-faicon "bell-slash-o"))
          ("crypt" . ,(all-the-icons-faicon "lock"))
          ("private" . ,(all-the-icons-faicon "eye-slash"))
          ("suggested" . ,(all-the-icons-faicon "thumbs-o-up"))
          ("idea" . ,(all-the-icons-faicon "lightbulb-o"))
          ("translation" . ,(all-the-icons-faicon "language"))
          ;; -----------------------------------------------------
          ("Org" . ,(all-the-icons-fileicon "org"))
          ("Emacs" . ,(all-the-icons-fileicon "emacs"))
          ("Wiki" . ,(all-the-icons-fileicon "mediawiki"))
          ("table" . ,(all-the-icons-faicon "table"))
          ;; -----------------------------------------------------
          ("LOG" . ,(all-the-icons-faicon "comment-o"))
          ("event" . ,(all-the-icons-faicon "calendar-check-o"))
          ("check" . ,(all-the-icons-faicon "check-square-o"))
          ("alert" . ,(all-the-icons-faicon "bell-o"))
          ("flag" . ,(all-the-icons-faicon "flag-o"))
          ("tag" . ,(all-the-icons-fileicon "tag"))
          ("question" . ,(all-the-icons-faicon "question-circle-o"))
          ("info" . ,(all-the-icons-faicon "info-circle"))
          ("quote" . ,(all-the-icons-faicon "quote-left"))
          ("lock" . ,(all-the-icons-faicon "lock"))
          ("unlock" . ,(all-the-icons-faicon "unlock"))
          ("key" . ,(all-the-icons-faicon "key"))
          ("refresh" . ,(all-the-icons-faicon "refresh"))
          ("repeat" . ,(all-the-icons-faicon "repeat"))
          ("star" . ,(all-the-icons-faicon "star"))
          ("heart" . ,(all-the-icons-faicon "heart-o"))
          ("brain" . ,(all-the-icons-fileicon "brain"))
          ("smile" . ,(all-the-icons-faicon "smile-o"))
          ("like" . ,(all-the-icons-faicon "thumbs-o-up"))
          ("trash" . ,(all-the-icons-faicon "trash-o"))
          ("inprogress" . ,(all-the-icons-faicon "spinner"))
          ;; -----------------------------------------------------
          ;; Life
          ;; ("@life" . ,(all-the-icons-faicon ""))
          ("talk" . ,(all-the-icons-faicon "comments-o"))
          ("call" . ,(all-the-icons-faicon "phone-square"))
          ("@SEX" . ,(all-the-icons-faicon "female"))
          ("female" . ,(all-the-icons-faicon "female"))
          ("male" . ,(all-the-icons-faicon "male"))
          ("neuter" . ,(all-the-icons-faicon "neuter"))
          ("venus" . ,(all-the-icons-faicon "venus"))
          ("venus_double" . ,(all-the-icons-faicon "venus-double"))
          ("venus_mars" . ,(all-the-icons-faicon "venus-mars"))
          ("meal" . ,(all-the-icons-faicon "cutlery"))
          ("home" . ,(all-the-icons-faicon "home"))
          ("repair" . ,(all-the-icons-faicon "wrench"))
          ("shopping" . ,(all-the-icons-faicon "shopping-cart"))
          ("express" . ,(all-the-icons-faicon "truck"))
          ("money" . ,(all-the-icons-faicon "money"))
          ("credit_card" . ,(all-the-icons-faicon "credit-card-alt"))
          ("visa" . ,(all-the-icons-faicon "cc-visa"))
          ("mastercard" . ,(all-the-icons-faicon "cc-mastercard"))
          ("PayPal" . ,(all-the-icons-faicon "paypal"))
          ("stripe" . ,(all-the-icons-faicon "cc-stripe"))
          ("gratipay" . ,(all-the-icons-faicon "gratipay"))
          ("btc" . ,(all-the-icons-faicon "btc"))
          ("watch" . ,(all-the-icons-faicon "eye"))
          ("hospital" . ,(all-the-icons-faicon "hospital-o"))
          ("industry" . ,(all-the-icons-faicon "industry"))
          ("doctor" . ,(all-the-icons-faicon "stethoscope"))
          ("doctor" . ,(all-the-icons-faicon "user-md"))
          ("medical" . ,(all-the-icons-faicon "medkit"))
          ("health" . ,(all-the-icons-faicon "medkit"))
          ("law" . ,(all-the-icons-faicon "gavel"))
          ("government" . ,(all-the-icons-faicon "building-o"))
          ("censorship" . ,(all-the-icons-faicon "assistive-listening-systems"))
          ("complaint" . ,(all-the-icons-faicon "bullhorn"))
          ("map" . ,(all-the-icons-faicon "map"))
          ("map_pin" . ,(all-the-icons-faicon "map-pin"))
          ("street_view" . ,(all-the-icons-faicon "street-view"))
          ("location" . ,(all-the-icons-faicon "map-marker")) ; "location-arrow", "map-o", "map-pin", "map-signs"
          ("bee" . ,(all-the-icons-faicon "beer"))
          ("coffee" . ,(all-the-icons-faicon "coffee"))
          ("bicycle" . ,(all-the-icons-faicon "bicycle"))
          ("car" . ,(all-the-icons-faicon "car"))
          ("bus" . ,(all-the-icons-faicon "bus"))
          ("taxi" . ,(all-the-icons-faicon "taxi"))
          ("subway" . ,(all-the-icons-faicon "subway"))
          ("plane" . ,(all-the-icons-faicon "plane"))
          ("travel" . ,(all-the-icons-faicon "suitcase"))
          ("child" . ,(all-the-icons-faicon "child"))
          ("recycle" . ,(all-the-icons-faicon "recycle"))
          ;; -----------------------------------------------------
          ("file" . ,(all-the-icons-faicon "file-text-o"))
          ("archive" . ,(all-the-icons-faicon "file-archive-o"))
          ("document" . ,(all-the-icons-faicon "file-text-o"))
          ("Markdown" . ,(all-the-icons-fileicon "markdownlint"))
          ("AsciiDoc" . ,(all-the-icons-fileicon "asciidoc"))
          ("OneNote" . ,(all-the-icons-fileicon "onenote"))
          ("word" . ,(all-the-icons-fileicon "word"))
          ("excel" . ,(all-the-icons-fileicon "excel"))
          ("powerpoint" . ,(all-the-icons-fileicon "powerpoint"))
          ("keynote" . ,(all-the-icons-fileicon "keynote"))
          ("access" . ,(all-the-icons-fileicon "access"))
          ("image" . ,(all-the-icons-faicon "file-image-o"))
          ("video" . ,(all-the-icons-faicon "file-video-o"))
          ("audio" . ,(all-the-icons-faicon "file-audio-o"))
          ("pdf" . ,(all-the-icons-faicon "file-pdf-o"))
          ("book" . ,(all-the-icons-faicon "book"))
          ("bookmark" . ,(all-the-icons-faicon "bookmark"))
          ("plot" . ,(all-the-icons-faicon "bar-chart"))
          ("diagram" . ,(all-the-icons-faicon "line-chart"))
          ("line_chart" . ,(all-the-icons-faicon "line-chart"))
          ("area_chart" . ,(all-the-icons-faicon "area-chart"))
          ("pie_chart" . ,(all-the-icons-faicon "pie-chart"))
          ("note" . ,(all-the-icons-faicon "pencil"))
          ("paperclip" . ,(all-the-icons-faicon "paperclip"))
          ("search" . ,(all-the-icons-faicon "search"))
          ("download" . ,(all-the-icons-faicon "download"))
          ("upload" . ,(all-the-icons-faicon "upload"))
          ("link" . ,(all-the-icons-faicon "link"))
          ("email" . ,(all-the-icons-faicon "envelope-o"))
          ("reply" . ,(all-the-icons-faicon "reply"))
          ("share" . ,(all-the-icons-faicon "share-square-o"))
          ("rss" . ,(all-the-icons-faicon "rss"))
          ("picture" . ,(all-the-icons-faicon "picture-o"))
          ("music" . ,(all-the-icons-faicon "music"))
          ("headphone" . ,(all-the-icons-faicon "headphones"))
          ("film" . ,(all-the-icons-faicon "film"))
          ("game" . ,(all-the-icons-faicon "gamepad"))
          ("steam" . ,(all-the-icons-faicon "steam"))
          ("camera" . ,(all-the-icons-faicon "camera-retro"))
          ("vlog" . ,(all-the-icons-fileicon "video"))
          ("record" . ,(all-the-icons-faicon "microphone"))
          ("news" . ,(all-the-icons-faicon "newspaper-o"))
          ;; -----------------------------------------------------
          ;; Work
          ("work" . ,(all-the-icons-faicon "black-tie"))
          ("print" . ,(all-the-icons-faicon "print"))
          ("business_trip" . ,(all-the-icons-faicon "briefcase"))
          ;; -----------------------------------------------------
          ;; Programming
          ("@programming" . ,(all-the-icons-faicon "code"))
          ("code" . ,(all-the-icons-faicon "code"))
          ("source_code" . ,(all-the-icons-faicon "file-code-o"))
          ("bug" . ,(all-the-icons-faicon "bug"))
          ("vulnerability" . ,(all-the-icons-faicon "bug"))
          ("patch" . ,(all-the-icons-fileicon "patch"))
          ("diff" . ,(all-the-icons-fileicon "diff"))
          ("coding" . ,(all-the-icons-faicon "keyboard-o"))
          ("regex" . ,(all-the-icons-fileicon "regex"))
          ("git" . ,(all-the-icons-faicon "git"))
          ("database" . ,(all-the-icons-faicon "database"))
          ("computer" . ,(all-the-icons-faicon "laptop"))
          ("laptop" . ,(all-the-icons-faicon "laptop"))
          ("mobile" . ,(all-the-icons-faicon "mobile"))
          ("phone" . ,(all-the-icons-faicon "phone"))
          ("fax" . ,(all-the-icons-faicon "fax"))
          ("TV" . ,(all-the-icons-faicon "television"))
          ("cmcc" . ,(all-the-icons-fileicon "ecere")) ; CMCC 中国移动
          ("hardware" . ,(all-the-icons-faicon "desktop"))
          ("robot" . ,(all-the-icons-fileicon "robot"))
          ("usb" . ,(all-the-icons-faicon "usb"))
          ("WiFi" . ,(all-the-icons-faicon "wifi"))
          ("Nvidia" . ,(all-the-icons-fileicon "nvidia"))
          ("Firefox" . ,(all-the-icons-faicon "firefox"))
          ("Chrome" . ,(all-the-icons-faicon "chrome"))
          ("Edge" . ,(all-the-icons-fileicon "edge"))
          ("Safari" . ,(all-the-icons-faicon "safari"))
          ("terminal" . ,(all-the-icons-faicon "terminal"))
          ("powershell" . ,(all-the-icons-fileicon "powershell"))
          ("CMake" . ,(all-the-icons-fileicon "cmake"))
          ("Tcl" . ,(all-the-icons-fileicon "tcl"))
          ("Jupyter" . ,(all-the-icons-fileicon "jupyter"))
          ("Finder" . ,(all-the-icons-fileicon "finder"))
          ("FFmpeg" . ,(all-the-icons-fileicon "ffmpeg"))
          ("Cloud" . ,(all-the-icons-faicon "cloud"))
          ("DevOps" . ,(all-the-icons-faicon "cogs")) ; "sitemap"
          ("Docker" . ,(all-the-icons-fileicon "dockerfile"))
          ("Vagrant" . ,(all-the-icons-fileicon "vagrant"))
          ("Ansible" . ,(all-the-icons-fileicon "ansible"))
          ("Puppet" . ,(all-the-icons-fileicon "puppet"))
          ("Terraform" . ,(all-the-icons-fileicon "terraform"))
          ("Nix" . ,(all-the-icons-fileicon "nix"))
          ("security" . ,(all-the-icons-faicon "shield"))
          ("hacker" . ,(all-the-icons-faicon "user-secret"))
          ("Nmap" . ,(all-the-icons-fileicon "nmap"))
          ("disk" . ,(all-the-icons-faicon "hdd-o"))
          ("Arduino" . ,(all-the-icons-fileicon "arduino"))
          ("Processing" . ,(all-the-icons-fileicon "processing"))
          ("Godot" . ,(all-the-icons-fileicon "godot"))
          ;; -----------------------------------------------------
          ;; Softwares
          ("Nginx" . ,(all-the-icons-fileicon "nginx"))
          ("Apache" . ,(all-the-icons-alltheicon "apache"))
          ("libuv" . ,(all-the-icons-fileicon "libuv"))
          ("LLVM" . ,(all-the-icons-fileicon "llvm"))
          ("GDB" . ,(all-the-icons-fileicon "gdb"))
          ("font" . ,(all-the-icons-faicon "font"))
          ("Electron" . ,(all-the-icons-fileicon "electron"))
          ("Xamarin" . ,(all-the-icons-fileicon "xamarin"))
          ("Ionic" . ,(all-the-icons-fileicon "ionic-project"))
          ;; Adobe softwares
          ("AdobePhotoshop" . ,(all-the-icons-fileicon "ps"))
          ("AdobePremiere" . ,(all-the-icons-fileicon "premiere"))
          ("AdobeAfterEffect" . ,(all-the-icons-fileicon "ae"))
          ("AdobeIllustrator" . ,(all-the-icons-fileicon "ai"))
          ("AdobeInDesign" . ,(all-the-icons-fileicon "id"))
          ("Blender" . ,(all-the-icons-fileicon "blender"))
          ("Maya" . ,(all-the-icons-fileicon "maya"))
          ;; ("CAD" . ,(all-the-icons-fileicon "kicad"))
          ("CAD" . ,(all-the-icons-fileicon "openscad"))
          ("Labview" . ,(all-the-icons-fileicon "labview"))
          ("Audacity" . ,(all-the-icons-fileicon "audacity"))
          ("Sketch" . ,(all-the-icons-fileicon "sketch"))
          ("Sketchup" . ,(all-the-icons-fileicon "sketchup-layout"))
          ("paint" . ,(all-the-icons-faicon "paint-brush"))
          ("AutoIt" . ,(all-the-icons-fileicon "autoit"))
          ("AutoHotKey" . ,(all-the-icons-fileicon "auto-hotkey"))
          ;; -----------------------------------------------------
          ;; Systems
          ("Linux" . ,(all-the-icons-faicon "linux"))
          ("ArchLinux" . ,(all-the-icons-fileicon "arch-linux"))
          ("Gentoo" . ,(all-the-icons-fileicon "gentoo"))
          ("Alpine" . ,(all-the-icons-fileicon "alpine-linux"))
          ("Apple" . ,(all-the-icons-faicon "apple"))
          ("macOS" . ,(all-the-icons-faicon "apple"))
          ("Windows" . ,(all-the-icons-faicon "windows"))
          ("Android" . ,(all-the-icons-faicon "android"))
          ("VirtualBox" . ,(all-the-icons-fileicon "virtualbox"))
          ("VMWare" . ,(all-the-icons-fileicon "vmware"))
          ("man" . ,(all-the-icons-fileicon "man-page"))
          ("config" . ,(all-the-icons-fileicon "config"))
          ;; -----------------------------------------------------
          ;; Programming Languages
          ("Shell" . ,(all-the-icons-alltheicon "script"))
          ("LISP" . ,(all-the-icons-fileicon "lisp"))
          ("Common_Lisp" . ,(all-the-icons-fileicon "clisp"))
          ("Clojure" . ,(all-the-icons-alltheicon "clojure-line" :v-adjust -0.05))
          ("ClojureScript" . ,(all-the-icons-fileicon "cljs" :v-adjust -0.01))
          ("Scheme" . ,(all-the-icons-fileicon "scheme"))
          ("Racket" . ,(all-the-icons-fileicon "racket"))
          ("EmacsLisp" . ,(all-the-icons-fileicon "elisp"))
          ("Python" . ,(all-the-icons-alltheicon "python"))
          ("Cython" . ,(all-the-icons-fileicon "cython"))
          ("Haskell" . ,(all-the-icons-alltheicon "haskell"))
          ("Julia" . ,(all-the-icons-fileicon "julia"))
          ("C" . ,(all-the-icons-alltheicon "c-line"))
          ("cpp" . ,(all-the-icons-alltheicon "cplusplus-line"))
          ("C#" . ,(all-the-icons-alltheicon "csharp-line"))
          ;; ("C#" . ,(all-the-icons-fileicon "cs-script"))
          ("nuget" . ,(all-the-icons-fileicon "nuget"))
          ("Java" . ,(all-the-icons-alltheicon "java"))
          ("Gradle" . ,(all-the-icons-fileicon "gradle"))
          ("Groovy" . ,(all-the-icons-fileicon "groovy"))
          ;; ("Scala" . ,(all-the-icons-fileicon ""))
          ("Kotlin" . ,(all-the-icons-fileicon "kotlin"))
          ("Go" . ,(all-the-icons-fileicon "go"))
          ("Rust" . ,(all-the-icons-alltheicon "rust"))
          ("Swift" . ,(all-the-icons-alltheicon "swift"))
          ("R" . ,(all-the-icons-fileicon "R"))
          ("Octave" . ,(all-the-icons-fileicon "octave"))
          ("Matlab" . ,(all-the-icons-fileicon "matlab"))
          ("Mathematica" . ,(all-the-icons-fileicon "mathematica"))
          ("Sage" . ,(all-the-icons-fileicon "sage"))
          ("Delphi" . ,(all-the-icons-fileicon "delphi"))
          ("OCaml" . ,(all-the-icons-fileicon "ocaml"))
          ("Fortran" . ,(all-the-icons-fileicon "fortran"))
          ("Coq" . ,(all-the-icons-fileicon "coq"))
          ;; ("Ruby" . ,(all-the-icons-fileicon "ruby"))
          ("MRuby" . ,(all-the-icons-fileicon "mruby"))
          ("RDoc" . ,(all-the-icons-fileicon "rdoc"))
          ("PHP" . ,(all-the-icons-fileicon "php"))
          ;; ("Perl" . ,(all-the-icons-fileicon ""))
          ("CPAN" . ,(all-the-icons-fileicon "cpan"))
          ("Lua" . ,(all-the-icons-fileicon "lua"))
          ("Io" . ,(all-the-icons-fileicon "io"))
          ("Web" . ,(all-the-icons-faicon "globe"))
          ("JavaScript" . ,(all-the-icons-alltheicon "javascript"))
          ("nodejs" . ,(all-the-icons-alltheicon "nodejs"))
          ("npm" . ,(all-the-icons-fileicon "npm-old"))
          ("TypeScript" . ,(all-the-icons-fileicon "typescript"))
          ("tsx" . ,(all-the-icons-fileicon "tsx"))
          ("jsx" . ,(all-the-icons-fileicon "jsx-2"))
          ("WebAssembly" . ,(all-the-icons-fileicon "wasm"))
          ("HTML" . ,(all-the-icons-alltheicon "html5"))
          ("HTML5" . ,(all-the-icons-alltheicon "html5"))
          ("CSS" . ,(all-the-icons-alltheicon "css3"))
          ("CSS3" . ,(all-the-icons-alltheicon "css3"))
          ("SQL" . ,(all-the-icons-faicon "database"))
          ("SQLite" . ,(all-the-icons-fileicon "sqlite"))
          ("PostgreSQL" . ,(all-the-icons-alltheicon "postgresql"))
          ("Firebase" . ,(all-the-icons-fileicon "firebase"))
          ("TeX" . ,(all-the-icons-fileicon "tex"))
          ("MathJax" . ,(all-the-icons-fileicon "mathjax"))
          ("Shen" . ,(all-the-icons-fileicon "shen"))
          ("Hacklang" . ,(all-the-icons-fileicon "hack"))
          ("VHDL" . ,(all-the-icons-fileicon "vhdl"))
          ("Verilog" . ,(all-the-icons-fileicon "verilog"))
          ("LaTeX" . ,(all-the-icons-fileicon "tex"))
          ("Spring" . ,(all-the-icons-alltheicon "spring"))
          ("Redux" . ,(all-the-icons-fileicon "redux"))
          ("AWS" . ,(all-the-icons-alltheicon "aws"))
          ("Kivy" . ,(all-the-icons-fileicon "kivy"))
          ;; ("JSON" . ,(all-the-icons-fileicon "json"))
          ("GraphQL" . ,(all-the-icons-fileicon "graphql"))
          ("OpenGL" . ,(all-the-icons-fileicon "opengl"))
          ("OpenCL" . ,(all-the-icons-fileicon "opencl"))
          ("WebGL" . ,(all-the-icons-fileicon "webgl"))
          ("Boot" . ,(all-the-icons-fileicon "build-boot"))
          ("bundler" . ,(all-the-icons-fileicon "bundler"))
          ("Graphviz" . ,(all-the-icons-fileicon "graphviz"))
          ("dylib" . ,(all-the-icons-fileicon "dylib"))
          ("V8" . ,(all-the-icons-fileicon "v8"))
          ("webpack" . ,(all-the-icons-fileicon "webpack-old"))
          ("Grunt" . ,(all-the-icons-fileicon "grunt"))
          ("Gulp" . ,(all-the-icons-fileicon "gulp"))
          ("vue" . ,(all-the-icons-fileicon "vue"))
          ("reason" . ,(all-the-icons-fileicon "reason"))
          ("d3js" . ,(all-the-icons-fileicon "d3"))
          ("chartjs" . ,(all-the-icons-fileicon "chartjs"))
          ("hoplon" . ,(all-the-icons-fileicon "hoplon"))
          ("Solidity" . ,(all-the-icons-fileicon "solidity"))
          ;; -----------------------------------------------------
          ;; Testing
          ;; ("" . ,(all-the-icons-fileicon "test-dir"))
          ;; ("" . ,(all-the-icons-fileicon "test-genertic"))
          ;; ("" . ,(all-the-icons-fileicon "test-js"))
          ;; ("" . ,(all-the-icons-fileicon "test-typescript"))
          ;; ("" . ,(all-the-icons-fileicon "test-coffeescript"))
          ;; ("" . ,(all-the-icons-fileicon "test-react"))
          ;; ("" . ,(all-the-icons-fileicon "test-python"))
          ;; ("" . ,(all-the-icons-fileicon "test-ruby"))
          ;; ("" . ,(all-the-icons-fileicon "test-perl"))
          ;; ("" . ,(all-the-icons-fileicon "phpunit"))
          ;; -----------------------------------------------------
          ;; Open Source
          ("GNU" . ,(all-the-icons-fileicon "gnu"))
          ("free" . ,(all-the-icons-fileicon "freemarker"))
          ("copyright" . ,(all-the-icons-faicon "copyright"))
          ("registered" . ,(all-the-icons-faicon "registered"))
          ("CC" . ,(all-the-icons-faicon "cc"))
          ;; -----------------------------------------------------
          ;; Project
          ("@project" . ,(all-the-icons-faicon "bolt"))
          ;; -----------------------------------------------------
          ;; Family
          ("@family" . ,(all-the-icons-material "home"))
          ;; -----------------------------------------------------
          ;; Company
          ("users" . ,(all-the-icons-faicon "users"))
          ("promotion" . ,(all-the-icons-faicon "bullhorn"))
          ;; -----------------------------------------------------
          ;; Internet
          ("Internet" . ,(all-the-icons-faicon "globe"))
          ("Google" . ,(all-the-icons-faicon "google"))
          ("Windows" . ,(all-the-icons-faicon "windows"))
          ("Microsoft" . ,(all-the-icons-faicon "windows"))
          ("Facebook" . ,(all-the-icons-faicon "facebook-official"))
          ("Twitter" . ,(all-the-icons-faicon "twitter"))
          ("Amazon" . ,(all-the-icons-faicon "amazon"))
          ("GitHub" . ,(all-the-icons-faicon "github"))
          ("GitLab" . ,(all-the-icons-fileicon "gitlab"))
          ("hacker_news" . ,(all-the-icons-faicon "hacker-news"))
          ("stack_exchange" . ,(all-the-icons-faicon "stack-exchange"))
          ("stack_overflow" . ,(all-the-icons-faicon "stack-overflow"))
          ("Wikipedia" . ,(all-the-icons-faicon "wikipedia-w"))
          ("YouTube" . ,(all-the-icons-faicon "youtube-square"))
          ;; ("PornHub" . ,(all-the-icons-faicon ""))
          ("Instagram" . ,(all-the-icons-faicon "instagram"))
          ("Dribbble" . ,(all-the-icons-faicon "dribbble"))
          ("Dropbox" . ,(all-the-icons-faicon "dropbox"))
          ("Baidu" . ,(all-the-icons-faicon "paw"))
          ("Tencent" . ,(all-the-icons-faicon "qq"))
          ("QQ" . ,(all-the-icons-faicon "qq"))
          ("weixin" . ,(all-the-icons-faicon "weixin"))
          ("wechat" . ,(all-the-icons-faicon "weixin"))
          ("weibo" . ,(all-the-icons-faicon "weibo"))
          ("whatsapp" . ,(all-the-icons-faicon "whatsapp"))
          ;; Investing & Finance
          ("finance" . ,(all-the-icons-faicon "money"))
          ("stock" . ,(all-the-icons-faicon "money"))
          ;; philosophy
          ("daoism" . ,(all-the-icons-fileicon "yin-yang"))
          ("tree" . ,(all-the-icons-fileicon "devicetree"))
          ("empire" . ,(all-the-icons-faicon "empire"))
          ;; Finance
          ("digital_currency" . ,(all-the-icons-faicon "btc"))
          ("btc" . ,(all-the-icons-faicon "btc"))
          ))

  ;; countries flags icons
  (let ((dir (concat user-emacs-directory "resources/icons/countries/")))
    (setq org-pretty-tags-surrogate-strings
          (append org-pretty-tags-surrogate-strings
                  `(("afghanistan" . ,(create-image (concat dir "afghanistan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("aland_islands" . ,(create-image (concat dir "aland-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("albania" . ,(create-image (concat dir "albania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("algeria" . ,(create-image (concat dir "algeria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("american_samoa" . ,(create-image (concat dir "american-samoa.png") nil nil :ascent 'center :height 35 :width 35))
                    ("andorra" . ,(create-image (concat dir "andorra.png") nil nil :ascent 'center :height 35 :width 35))
                    ("angola" . ,(create-image (concat dir "angola.png") nil nil :ascent 'center :height 35 :width 35))
                    ("anguilla" . ,(create-image (concat dir "anguilla.png") nil nil :ascent 'center :height 35 :width 35))
                    ("antigua_and_barbuda" . ,(create-image (concat dir "antigua-and-barbuda.png") nil nil :ascent 'center :height 35 :width 35))
                    ("argentina" . ,(create-image (concat dir "argentina.png") nil nil :ascent 'center :height 35 :width 35))
                    ("armenia" . ,(create-image (concat dir "armenia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("aruba" . ,(create-image (concat dir "aruba.png") nil nil :ascent 'center :height 35 :width 35))
                    ("australia" . ,(create-image (concat dir "australia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("austria" . ,(create-image (concat dir "austria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("azerbaijan" . ,(create-image (concat dir "azerbaijan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("azores_islands" . ,(create-image (concat dir "azores-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bahamas" . ,(create-image (concat dir "bahamas.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bahrain" . ,(create-image (concat dir "bahrain.png") nil nil :ascent 'center :height 35 :width 35))
                    ("balearic_islands" . ,(create-image (concat dir "balearic-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bangladesh" . ,(create-image (concat dir "bangladesh.png") nil nil :ascent 'center :height 35 :width 35))
                    ("barbados" . ,(create-image (concat dir "barbados.png") nil nil :ascent 'center :height 35 :width 35))
                    ("basque_country" . ,(create-image (concat dir "basque-country.png") nil nil :ascent 'center :height 35 :width 35))
                    ("belarus" . ,(create-image (concat dir "belarus.png") nil nil :ascent 'center :height 35 :width 35))
                    ("belgium" . ,(create-image (concat dir "belgium.png") nil nil :ascent 'center :height 35 :width 35))
                    ("belize" . ,(create-image (concat dir "belize.png") nil nil :ascent 'center :height 35 :width 35))
                    ("benin" . ,(create-image (concat dir "benin.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bermuda" . ,(create-image (concat dir "bermuda.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bhutan" . ,(create-image (concat dir "bhutan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bolivia" . ,(create-image (concat dir "bolivia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bonaire" . ,(create-image (concat dir "bonaire.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bosnia_and_herzegovina" . ,(create-image (concat dir "bosnia-and-herzegovina.png") nil nil :ascent 'center :height 35 :width 35))
                    ("botswana" . ,(create-image (concat dir "botswana.png") nil nil :ascent 'center :height 35 :width 35))
                    ("brazil" . ,(create-image (concat dir "brazil.png") nil nil :ascent 'center :height 35 :width 35))
                    ("british_columbia" . ,(create-image (concat dir "british-columbia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("british_indian_ocean_territory" . ,(create-image (concat dir "british-indian-ocean-territory.png") nil nil :ascent 'center :height 35 :width 35))
                    ("british_virgin_islands" . ,(create-image (concat dir "british-virgin-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("brunei" . ,(create-image (concat dir "brunei.png") nil nil :ascent 'center :height 35 :width 35))
                    ("bulgaria" . ,(create-image (concat dir "bulgaria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("burkina_faso" . ,(create-image (concat dir "burkina-faso.png") nil nil :ascent 'center :height 35 :width 35))
                    ("burundi" . ,(create-image (concat dir "burundi.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cambodia" . ,(create-image (concat dir "cambodia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cameroon" . ,(create-image (concat dir "cameroon.png") nil nil :ascent 'center :height 35 :width 35))
                    ("canada" . ,(create-image (concat dir "canada.png") nil nil :ascent 'center :height 35 :width 35))
                    ("canary_islands" . ,(create-image (concat dir "canary-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cape_verde" . ,(create-image (concat dir "cape-verde.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cayman_islands" . ,(create-image (concat dir "cayman-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("central_african_republic" . ,(create-image (concat dir "central-african-republic.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ceuta" . ,(create-image (concat dir "ceuta.png") nil nil :ascent 'center :height 35 :width 35))
                    ("chad" . ,(create-image (concat dir "chad.png") nil nil :ascent 'center :height 35 :width 35))
                    ("chile" . ,(create-image (concat dir "chile.png") nil nil :ascent 'center :height 35 :width 35))
                    ("china" . ,(create-image (concat dir "china.png") nil nil :ascent 'center :height 35 :width 35))
                    ("christmas_island" . ,(create-image (concat dir "christmas-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cocos_island" . ,(create-image (concat dir "cocos-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("colombia" . ,(create-image (concat dir "colombia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("comoros" . ,(create-image (concat dir "comoros.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cook_islands" . ,(create-image (concat dir "cook-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("corsica" . ,(create-image (concat dir "corsica.png") nil nil :ascent 'center :height 35 :width 35))
                    ("costa_rica" . ,(create-image (concat dir "costa-rica.png") nil nil :ascent 'center :height 35 :width 35))
                    ("croatia" . ,(create-image (concat dir "croatia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cuba" . ,(create-image (concat dir "cuba.png") nil nil :ascent 'center :height 35 :width 35))
                    ("curacao" . ,(create-image (concat dir "curacao.png") nil nil :ascent 'center :height 35 :width 35))
                    ("cyprus" . ,(create-image (concat dir "cyprus.png") nil nil :ascent 'center :height 35 :width 35))
                    ("czech_republic" . ,(create-image (concat dir "czech-republic.png") nil nil :ascent 'center :height 35 :width 35))
                    ("democratic_republic_of_congo" . ,(create-image (concat dir "democratic-republic-of-congo.png") nil nil :ascent 'center :height 35 :width 35))
                    ("denmark" . ,(create-image (concat dir "denmark.png") nil nil :ascent 'center :height 35 :width 35))
                    ("djibouti" . ,(create-image (concat dir "djibouti.png") nil nil :ascent 'center :height 35 :width 35))
                    ("dominica" . ,(create-image (concat dir "dominica.png") nil nil :ascent 'center :height 35 :width 35))
                    ("dominican_republic" . ,(create-image (concat dir "dominican-republic.png") nil nil :ascent 'center :height 35 :width 35))
                    ("east_timor" . ,(create-image (concat dir "east-timor.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ecuador" . ,(create-image (concat dir "ecuador.png") nil nil :ascent 'center :height 35 :width 35))
                    ("egypt" . ,(create-image (concat dir "egypt.png") nil nil :ascent 'center :height 35 :width 35))
                    ("el_salvador" . ,(create-image (concat dir "el-salvador.png") nil nil :ascent 'center :height 35 :width 35))
                    ("england" . ,(create-image (concat dir "england.png") nil nil :ascent 'center :height 35 :width 35))
                    ("equatorial_guinea" . ,(create-image (concat dir "equatorial-guinea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("eritrea" . ,(create-image (concat dir "eritrea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("estonia" . ,(create-image (concat dir "estonia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ethiopia" . ,(create-image (concat dir "ethiopia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("european_union" . ,(create-image (concat dir "european-union.png") nil nil :ascent 'center :height 35 :width 35))
                    ("falkland_islands" . ,(create-image (concat dir "falkland-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("faroe_islands" . ,(create-image (concat dir "faroe-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("fiji" . ,(create-image (concat dir "fiji.png") nil nil :ascent 'center :height 35 :width 35))
                    ("finland" . ,(create-image (concat dir "finland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("france" . ,(create-image (concat dir "france.png") nil nil :ascent 'center :height 35 :width 35))
                    ("french_polynesia" . ,(create-image (concat dir "french-polynesia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("gabon" . ,(create-image (concat dir "gabon.png") nil nil :ascent 'center :height 35 :width 35))
                    ("galapagos_islands" . ,(create-image (concat dir "galapagos-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("gambia" . ,(create-image (concat dir "gambia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("georgia" . ,(create-image (concat dir "georgia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("germany" . ,(create-image (concat dir "germany.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ghana" . ,(create-image (concat dir "ghana.png") nil nil :ascent 'center :height 35 :width 35))
                    ("gibraltar" . ,(create-image (concat dir "gibraltar.png") nil nil :ascent 'center :height 35 :width 35))
                    ("greece" . ,(create-image (concat dir "greece.png") nil nil :ascent 'center :height 35 :width 35))
                    ("greenland" . ,(create-image (concat dir "greenland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("grenada" . ,(create-image (concat dir "grenada.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guam" . ,(create-image (concat dir "guam.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guatemala" . ,(create-image (concat dir "guatemala.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guernsey" . ,(create-image (concat dir "guernsey.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guinea_bissau" . ,(create-image (concat dir "guinea-bissau.png") nil nil :ascent 'center :height 35 :width 35))
                    ("guinea" . ,(create-image (concat dir "guinea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("haiti" . ,(create-image (concat dir "haiti.png") nil nil :ascent 'center :height 35 :width 35))
                    ("hawaii" . ,(create-image (concat dir "hawaii.png") nil nil :ascent 'center :height 35 :width 35))
                    ("honduras" . ,(create-image (concat dir "honduras.png") nil nil :ascent 'center :height 35 :width 35))
                    ("hong_kong" . ,(create-image (concat dir "hong-kong.png") nil nil :ascent 'center :height 35 :width 35))
                    ("hungary" . ,(create-image (concat dir "hungary.png") nil nil :ascent 'center :height 35 :width 35))
                    ("iceland" . ,(create-image (concat dir "iceland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("india" . ,(create-image (concat dir "india.png") nil nil :ascent 'center :height 35 :width 35))
                    ("indonesia" . ,(create-image (concat dir "indonesia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("iran" . ,(create-image (concat dir "iran.png") nil nil :ascent 'center :height 35 :width 35))
                    ("iraq" . ,(create-image (concat dir "iraq.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ireland" . ,(create-image (concat dir "ireland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("isle_of_man" . ,(create-image (concat dir "isle-of-man.png") nil nil :ascent 'center :height 35 :width 35))
                    ("israel" . ,(create-image (concat dir "israel.png") nil nil :ascent 'center :height 35 :width 35))
                    ("italy" . ,(create-image (concat dir "italy.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ivory_coast" . ,(create-image (concat dir "ivory-coast.png") nil nil :ascent 'center :height 35 :width 35))
                    ("jamaica" . ,(create-image (concat dir "jamaica.png") nil nil :ascent 'center :height 35 :width 35))
                    ("japan" . ,(create-image (concat dir "japan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("jersey" . ,(create-image (concat dir "jersey.png") nil nil :ascent 'center :height 35 :width 35))
                    ("jordan" . ,(create-image (concat dir "jordan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kazakhstan" . ,(create-image (concat dir "kazakhstan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kenya" . ,(create-image (concat dir "kenya.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kiribati" . ,(create-image (concat dir "kiribati.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kosovo" . ,(create-image (concat dir "kosovo.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kuwait" . ,(create-image (concat dir "kuwait.png") nil nil :ascent 'center :height 35 :width 35))
                    ("kyrgyzstan" . ,(create-image (concat dir "kyrgyzstan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("laos" . ,(create-image (concat dir "laos.png") nil nil :ascent 'center :height 35 :width 35))
                    ("latvia" . ,(create-image (concat dir "latvia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("lebanon" . ,(create-image (concat dir "lebanon.png") nil nil :ascent 'center :height 35 :width 35))
                    ("lesotho" . ,(create-image (concat dir "lesotho.png") nil nil :ascent 'center :height 35 :width 35))
                    ("liberia" . ,(create-image (concat dir "liberia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("libya" . ,(create-image (concat dir "libya.png") nil nil :ascent 'center :height 35 :width 35))
                    ("liechtenstein" . ,(create-image (concat dir "liechtenstein.png") nil nil :ascent 'center :height 35 :width 35))
                    ("lithuania" . ,(create-image (concat dir "lithuania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("luxembourg" . ,(create-image (concat dir "luxembourg.png") nil nil :ascent 'center :height 35 :width 35))
                    ("macao" . ,(create-image (concat dir "macao.png") nil nil :ascent 'center :height 35 :width 35))
                    ("madagascar" . ,(create-image (concat dir "madagascar.png") nil nil :ascent 'center :height 35 :width 35))
                    ("madeira" . ,(create-image (concat dir "madeira.png") nil nil :ascent 'center :height 35 :width 35))
                    ("malawi" . ,(create-image (concat dir "malawi.png") nil nil :ascent 'center :height 35 :width 35))
                    ("malaysia" . ,(create-image (concat dir "malaysia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("maldives" . ,(create-image (concat dir "maldives.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mali" . ,(create-image (concat dir "mali.png") nil nil :ascent 'center :height 35 :width 35))
                    ("malta" . ,(create-image (concat dir "malta.png") nil nil :ascent 'center :height 35 :width 35))
                    ("marshall_island" . ,(create-image (concat dir "marshall-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("martinique" . ,(create-image (concat dir "martinique.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mauritania" . ,(create-image (concat dir "mauritania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mauritius" . ,(create-image (concat dir "mauritius.png") nil nil :ascent 'center :height 35 :width 35))
                    ("melilla" . ,(create-image (concat dir "melilla.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mexico" . ,(create-image (concat dir "mexico.png") nil nil :ascent 'center :height 35 :width 35))
                    ("micronesia" . ,(create-image (concat dir "micronesia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("moldova" . ,(create-image (concat dir "moldova.png") nil nil :ascent 'center :height 35 :width 35))
                    ("monaco" . ,(create-image (concat dir "monaco.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mongolia" . ,(create-image (concat dir "mongolia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("montenegro" . ,(create-image (concat dir "montenegro.png") nil nil :ascent 'center :height 35 :width 35))
                    ("montserrat" . ,(create-image (concat dir "montserrat.png") nil nil :ascent 'center :height 35 :width 35))
                    ("morocco" . ,(create-image (concat dir "morocco.png") nil nil :ascent 'center :height 35 :width 35))
                    ("mozambique" . ,(create-image (concat dir "mozambique.png") nil nil :ascent 'center :height 35 :width 35))
                    ("myanmar" . ,(create-image (concat dir "myanmar.png") nil nil :ascent 'center :height 35 :width 35))
                    ("namibia" . ,(create-image (concat dir "namibia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("nauru" . ,(create-image (concat dir "nauru.png") nil nil :ascent 'center :height 35 :width 35))
                    ("nepal" . ,(create-image (concat dir "nepal.png") nil nil :ascent 'center :height 35 :width 35))
                    ("netherlands" . ,(create-image (concat dir "netherlands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("new_zealand" . ,(create-image (concat dir "new-zealand.png") nil nil :ascent 'center :height 35 :width 35))
                    ("nicaragua" . ,(create-image (concat dir "nicaragua.png") nil nil :ascent 'center :height 35 :width 35))
                    ("niger" . ,(create-image (concat dir "niger.png") nil nil :ascent 'center :height 35 :width 35))
                    ("nigeria" . ,(create-image (concat dir "nigeria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("niue" . ,(create-image (concat dir "niue.png") nil nil :ascent 'center :height 35 :width 35))
                    ("norfolk_island" . ,(create-image (concat dir "norfolk-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("north_korea" . ,(create-image (concat dir "north-korea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("northen_cyprus" . ,(create-image (concat dir "northen-cyprus.png") nil nil :ascent 'center :height 35 :width 35))
                    ("northern_marianas_islands" . ,(create-image (concat dir "northern-marianas-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("norway" . ,(create-image (concat dir "norway.png") nil nil :ascent 'center :height 35 :width 35))
                    ("oman" . ,(create-image (concat dir "oman.png") nil nil :ascent 'center :height 35 :width 35))
                    ("orkney_islands" . ,(create-image (concat dir "orkney-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ossetia" . ,(create-image (concat dir "ossetia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("otan" . ,(create-image (concat dir "otan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("pakistan" . ,(create-image (concat dir "pakistan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("palau" . ,(create-image (concat dir "palau.png") nil nil :ascent 'center :height 35 :width 35))
                    ("palestine" . ,(create-image (concat dir "palestine.png") nil nil :ascent 'center :height 35 :width 35))
                    ("panama" . ,(create-image (concat dir "panama.png") nil nil :ascent 'center :height 35 :width 35))
                    ("papua_new_guinea" . ,(create-image (concat dir "papua-new-guinea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("peru" . ,(create-image (concat dir "peru.png") nil nil :ascent 'center :height 35 :width 35))
                    ("philippines" . ,(create-image (concat dir "philippines.png") nil nil :ascent 'center :height 35 :width 35))
                    ("pitcairn_islands" . ,(create-image (concat dir "pitcairn-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("poland" . ,(create-image (concat dir "poland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("portugal" . ,(create-image (concat dir "portugal.png") nil nil :ascent 'center :height 35 :width 35))
                    ("puerto_rico" . ,(create-image (concat dir "puerto-rico.png") nil nil :ascent 'center :height 35 :width 35))
                    ("qatar" . ,(create-image (concat dir "qatar.png") nil nil :ascent 'center :height 35 :width 35))
                    ("rapa_nui" . ,(create-image (concat dir "rapa-nui.png") nil nil :ascent 'center :height 35 :width 35))
                    ("republic_of_macedonia" . ,(create-image (concat dir "republic-of-macedonia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("republic_of_the_congo" . ,(create-image (concat dir "republic-of-the-congo.png") nil nil :ascent 'center :height 35 :width 35))
                    ("romania" . ,(create-image (concat dir "romania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("russia" . ,(create-image (concat dir "russia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("rwanda" . ,(create-image (concat dir "rwanda.png") nil nil :ascent 'center :height 35 :width 35))
                    ("saba_island" . ,(create-image (concat dir "saba-island.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sahrawi_arab_democratic_republic" . ,(create-image (concat dir "sahrawi-arab-democratic-republic.png") nil nil :ascent 'center :height 35 :width 35))
                    ("saint_kitts_and_nevis" . ,(create-image (concat dir "saint-kitts-and-nevis.png") nil nil :ascent 'center :height 35 :width 35))
                    ("samoa" . ,(create-image (concat dir "samoa.png") nil nil :ascent 'center :height 35 :width 35))
                    ("san_marino" . ,(create-image (concat dir "san-marino.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sao_tome_and_principe" . ,(create-image (concat dir "sao-tome-and-principe.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sardinia" . ,(create-image (concat dir "sardinia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("saudi_arabia" . ,(create-image (concat dir "saudi-arabia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("scotland" . ,(create-image (concat dir "scotland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("senegal" . ,(create-image (concat dir "senegal.png") nil nil :ascent 'center :height 35 :width 35))
                    ("serbia" . ,(create-image (concat dir "serbia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("seychelles" . ,(create-image (concat dir "seychelles.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sicily" . ,(create-image (concat dir "sicily.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sierra_leone" . ,(create-image (concat dir "sierra-leone.png") nil nil :ascent 'center :height 35 :width 35))
                    ("singapore" . ,(create-image (concat dir "singapore.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sint_eustatius" . ,(create-image (concat dir "sint-eustatius.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sint_maarten" . ,(create-image (concat dir "sint-maarten.png") nil nil :ascent 'center :height 35 :width 35))
                    ("slovakia" . ,(create-image (concat dir "slovakia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("slovenia" . ,(create-image (concat dir "slovenia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("solomon_islands" . ,(create-image (concat dir "solomon-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("somalia" . ,(create-image (concat dir "somalia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("somaliland" . ,(create-image (concat dir "somaliland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("south_africa" . ,(create-image (concat dir "south-africa.png") nil nil :ascent 'center :height 35 :width 35))
                    ("south_korea" . ,(create-image (concat dir "south-korea.png") nil nil :ascent 'center :height 35 :width 35))
                    ("south_sudan" . ,(create-image (concat dir "south-sudan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("spain" . ,(create-image (concat dir "spain.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sri_lanka" . ,(create-image (concat dir "sri-lanka.png") nil nil :ascent 'center :height 35 :width 35))
                    ("st_barts" . ,(create-image (concat dir "st-barts.png") nil nil :ascent 'center :height 35 :width 35))
                    ("st_lucia" . ,(create-image (concat dir "st-lucia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("st_vincent_and_the_grenadines" . ,(create-image (concat dir "st-vincent-and-the-grenadines.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sudan" . ,(create-image (concat dir "sudan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("suriname" . ,(create-image (concat dir "suriname.png") nil nil :ascent 'center :height 35 :width 35))
                    ("swaziland" . ,(create-image (concat dir "swaziland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("sweden" . ,(create-image (concat dir "sweden.png") nil nil :ascent 'center :height 35 :width 35))
                    ("switzerland" . ,(create-image (concat dir "switzerland.png") nil nil :ascent 'center :height 35 :width 35))
                    ("syria" . ,(create-image (concat dir "syria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("taiwan" . ,(create-image (concat dir "taiwan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tajikistan" . ,(create-image (concat dir "tajikistan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tanzania" . ,(create-image (concat dir "tanzania.png") nil nil :ascent 'center :height 35 :width 35))
                    ("thailand" . ,(create-image (concat dir "thailand.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tibet" . ,(create-image (concat dir "tibet.png") nil nil :ascent 'center :height 35 :width 35))
                    ("togo" . ,(create-image (concat dir "togo.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tokelau" . ,(create-image (concat dir "tokelau.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tonga" . ,(create-image (concat dir "tonga.png") nil nil :ascent 'center :height 35 :width 35))
                    ("transnistria" . ,(create-image (concat dir "transnistria.png") nil nil :ascent 'center :height 35 :width 35))
                    ("trinidad_and_tobago" . ,(create-image (concat dir "trinidad-and-tobago.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tubalu" . ,(create-image (concat dir "tubalu.png") nil nil :ascent 'center :height 35 :width 35))
                    ("tunisia" . ,(create-image (concat dir "tunisia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("turkey" . ,(create-image (concat dir "turkey.png") nil nil :ascent 'center :height 35 :width 35))
                    ("turkmenistan" . ,(create-image (concat dir "turkmenistan.png") nil nil :ascent 'center :height 35 :width 35))
                    ("turks_and_caicos" . ,(create-image (concat dir "turks-and-caicos.png") nil nil :ascent 'center :height 35 :width 35))
                    ("uganda" . ,(create-image (concat dir "uganda.png") nil nil :ascent 'center :height 35 :width 35))
                    ("ukraine" . ,(create-image (concat dir "ukraine.png") nil nil :ascent 'center :height 35 :width 35))
                    ("united_arab_emirates" . ,(create-image (concat dir "united-arab-emirates.png") nil nil :ascent 'center :height 35 :width 35))
                    ("united_kingdom" . ,(create-image (concat dir "united-kingdom.png") nil nil :ascent 'center :height 35 :width 35))
                    ("united_nations" . ,(create-image (concat dir "united-nations.png") nil nil :ascent 'center :height 35 :width 35))
                    ("america" . ,(create-image (concat dir "united-states-of-america.png") nil nil :ascent 'center :height 35 :width 35))
                    ("uruguay" . ,(create-image (concat dir "uruguay.png") nil nil :ascent 'center :height 35 :width 35))
                    ("uzbekistn" . ,(create-image (concat dir "uzbekistn.png") nil nil :ascent 'center :height 35 :width 35))
                    ("vanuatu" . ,(create-image (concat dir "vanuatu.png") nil nil :ascent 'center :height 35 :width 35))
                    ("vatican_city" . ,(create-image (concat dir "vatican-city.png") nil nil :ascent 'center :height 35 :width 35))
                    ("venezuela" . ,(create-image (concat dir "venezuela.png") nil nil :ascent 'center :height 35 :width 35))
                    ("vietnam" . ,(create-image (concat dir "vietnam.png") nil nil :ascent 'center :height 35 :width 35))
                    ("virgin_islands" . ,(create-image (concat dir "virgin-islands.png") nil nil :ascent 'center :height 35 :width 35))
                    ("singapore" . ,(create-image (concat dir "singapore.png") nil nil :ascent 'center :height 35 :width 35))
                    ("yemen" . ,(create-image (concat dir "yemen.png") nil nil :ascent 'center :height 35 :width 35))
                    ("zambia" . ,(create-image (concat dir "zambia.png") nil nil :ascent 'center :height 35 :width 35))
                    ("zimbabwe" . ,(create-image (concat dir "zimbabwe.png") nil nil :ascent 'center :height 35 :width 35))))))
  )


(provide 'init-org-tag)

;;; init-org-tag.el ends here
